### PR TITLE
fix(graphql-elasticsearch-transformer): support del in sync enabled API

### LINKED ISSUE #4228: DataStore/Conflict Detection not support _TTL in ElasticSearch
**Describe the bug**
The new 4.19.0 version of the CLI implemented a fix to allow DynamoDB records with a _version field to stream to ElasticSearch by enabling external versioning. I tested created and update and this works fine.

However, when we delete a record in AppSync it adds a _deleted=true field and a _ttl field with an epoch time 30 days out. The _ttl field is, similar to _version, a meta_data field in ElasticSearch so the deleted record does not stream to ElasticSearch so the record remains "undeleted" in ElasticSearch forever.

In CloudWatch the following error shows up when you try to stream a deleted record:

            "status": 400,
            "error": {
                "type": "mapper_parsing_exception",
                "reason": "Field [_ttl] is a metadata field and cannot be added inside a document. Use the index API request parameters."
            }

**Amplify CLI Version**
 4.19.0

**To Reproduce**
With conflict detection enabled use the delete*( ) resolver to delete a record - the deleted record will fail to stream to ElasticSearch

**Expected behavior**

I expect the deleted record to stream to ElasticSearch. We can't have a record that is flagged as deleted in DynamoDB showing as not deleted in ElasticSearch.

This is related to issue #3796 that has been closed.

### PR DESCRIPTION
**Pull request by yuth**
AppSync does an soft delete an API is sync enabled. Streaming lambda function should delete this
from index when its a soft delete

fix #4228

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by SwaySway** [comment]
Initial Changes LGTM added a few things on top
- E2E test
- Fixed `@auth` + `@searchable` to include `_version` as well
- Scoped the datastore check to also include resolver configs with just models

File: packages/graphql-transformer-core/src/TransformerContext.ts [hunk 1]
```diff
@@ -722,11 +722,6 @@ export class TransformerContext {
   }
 
   public isProjectUsingDataStore(): boolean {
-    return (
-      this.resolverConfig &&
-      this.resolverConfig.project &&
-      this.resolverConfig.project.ConflictDetection === 'VERSION' &&
-      this.resolverConfig.project.ConflictHandler === 'AUTOMERGE'
-    );
+    return this.resolverConfig && (typeof this.resolverConfig.project !== undefined || typeof this.resolverConfig.models !== undefined);
```
Comment (edwardfoyle) [inline packages/graphql-transformer-core/src/TransformerContext.ts:725]: do the values of ConflictDetection and ConflictHandler matter in the check?

File: packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts [hunk 2]
```diff
@@ -818,6 +838,87 @@ test('query for books by Agatha Christie with model using @key', async () => {
...
+  expect(updateTodoResponse.data.updateTodo._version).toEqual(todoVersion);
+
+  // Wait for the Todo to sync to Elasticsearch
+  await cf.wait(10, () => Promise.resolve());
+
+  searchTodoResponse = await searchTodos();
+  expect(searchTodoResponse.data.items.length).toEqual(1);
+  expect(searchTodoResponse.data.searchTodos.items[0].name).toEqual(todoName);
+  expect(searchTodoResponse.data.searchTodo.items[0]._version).toEqual(todoVersion);
+});
```
Comment (edwardfoyle) [inline packages/graphql-transformers-e2e-tests/src/__tests__/SearchableModelTransformer.e2e.test.ts:870]: would be nice to extend this test to also set _deleted to true and check that the search does not include it anymore. I think this would require updating the entry in ddb rather than through appsync though.
