### PR TITLE
fix: validation for s3 bucketname in s3-cli walkthrough

### LINKED ISSUE #9542: 'amplify add storage' allows uppercase characters, then fails when pushing to cloud
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

_No response_

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

`amplify version` => 7.6.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

storage

### Amplify Commands

add, push

### Describe the bug

When adding an S3 bucket, amplify cli allowed me to enter an uppercase character for the bucket name. When I eventually tried to push my changes to the cloud it failed because buckets can't have uppercase characters. Also cli didn't allow me to use a '-' even though I'm pretty sure you can use hyphens when naming buckets.

Just making an issue of this because it is annoying, spent a bit of time configuring storage and pushing and have to do it over again.

### Expected behavior

Stop me from naming a bucket with an uppercase character before it tries to create it.

### Reproduction steps

amplify add storage                                              
? Select from one of the below mentioned services: Content (Images, audio, video, etc.)
✔ Provide a friendly name for your resource that will be used to label this category in the project: · resourcename
✔ Provide bucket name: · WishItStoppedMeIfITriedToDoSomethingLikeThis

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
Screen Shot 2022-01-15 at 1 01 30 PM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sachscode**
#### Description of changes
* Added a generic regex based validator for the prompter library. 
* Fixed S3 bucket-name walkthrough by using the correct regex pattern which allows alphanumeric chars and hyphen.
* E2E test for hyphenated bucketname

#### Issue #, if available
#9550 

#### Description of how you validated changes
1. Updated s3 bucket unit-test with a bucket-name containing alphanumeric and hyphen.
2. Unit tests for validator in prompter library
3. manual test for create+deploy s3 bucket with a hyphen in the name.

#### Checklist

- [*] PR description included
- [*] `yarn test` passes
- [*] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ export async function askBucketNameQuestion(context: $TSContext, defaultValues:
   const message = 'Provide bucket name:';
   const onErrorMsg =
     'Bucket name can only use the following characters: a-z 0-9 - and should have minimum 3 character and max of 47 character';
-  const validator = and([alphanumeric(), minLength(3), maxLength(47)], onErrorMsg);
+  const validator = and([regexValidator('Input can only contain the following characters: a-z 0-9', RegExp(/^[a-z0-9-]+$/) ),minLength(3), maxLength(47)], onErrorMsg);
```
Comment (sundersc) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: Can we double check the regex? I believe hyphen(-) has a special meaning so it may be required to escape like this `RegExp(/^[a-z0-9\-]+$/)`.

File: packages/amplify-prompts/src/validators.ts [hunk 2]
```diff
@@ -17,6 +17,11 @@ export const alphanumeric =
   (input: string) =>
     /^[a-zA-Z0-9]+$/.test(input) ? true : message;
 
+export const regexValidator =
```
Comment (edwardfoyle) [inline packages/amplify-prompts/src/validators.ts:20]: Bit: suggest naming this `matchRegex`. Also I don't think there should be a default regex. It should just be a required arg

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts (hunk 1 above)
Comment (edwardfoyle) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: Also nit: don't need to use the RegExp constructor when using slashes. I would recommend just using slashes

Comment (sachscode) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: @sundersc I have tested this both in the unit test ( s3 and validator) and manual (bucket creation). we used this regex in the inquirer library, hence its good.

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts [hunk 3]
```diff
@@ -92,7 +92,7 @@ export async function askBucketNameQuestion(context: $TSContext, defaultValues:
   const message = 'Provide bucket name:';
   const onErrorMsg =
     'Bucket name can only use the following characters: a-z 0-9 - and should have minimum 3 character and max of 47 character';
-  const validator = and([alphanumeric(), minLength(3), maxLength(47)], onErrorMsg);
+  const validator = and([matchRegex('Input can only contain the following characters: a-z 0-9', /^[a-z0-9-]+$/),minLength(3), maxLength(47)], onErrorMsg);
```
Comment (edwardfoyle) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]:
```suggestion
  const validator = and([matchRegex('Input can only contain lowercase characters, numbers, and hyphens', /^[a-z0-9-]+$/),minLength(3), maxLength(47)], onErrorMsg);
```

File: packages/amplify-prompts/src/validators.ts [hunk 4]
```diff
@@ -17,6 +17,11 @@ export const alphanumeric =
   (input: string) =>
     /^[a-zA-Z0-9]+$/.test(input) ? true : message;
 
+export const matchRegex =
+  (message: string = 'Input must satisfy regular expression', validatorRegex : RegExp): Validator =>
```
Comment (edwardfoyle) [inline packages/amplify-prompts/src/validators.ts:21]: Not sure this default message is very useful. If you feel a default is necessary, perhaps default to: `Input must match regular expression ${validatorRegex}`

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts (hunk 3 above)
Comment (sachscode) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: Although this is more readable , it sort of increases the scope of the validator function . It would be correct to say: 
"Input can only contain lowercase characters, numbers, and hyphens. It cannot start or end with hyphens and should be between 3 and 47 chars long".

Comment (sachscode) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: another option is "Input can only contain the characters: a to z numbers: 0 to 9 and optionally - as a separator"

Comment (sachscode) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: Actually it should use the onErrorMsg variable instead of a custom string.

File: packages/amplify-prompts/src/validators.ts (hunk 4 above)
Comment (sachscode) [reply packages/amplify-prompts/src/validators.ts:21]: 1. validatorRegex is the second parameter. It cannot be referenced in the default first parameter.
2.  The second parameter to the function is the validatorRegex. The error is saying that the first parameter should satisfy the regex validation. match seems like a better term.

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts (hunk 3 above)
Comment (sachscode) [reply packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: Actually the validate function ignores the message if an onError is passed into a compound statement. 
In const validator = and([matchRegex('Input can only contain lowercase characters, numbers, and hyphens', /^[a-z0-9-]+$/),minLength(3), maxLength(47)], onErrorMsg);
The first error-string is ignored if an error is encountered. Hence the change may not be of consequence.

**Review by sundersc — APPROVED** [review]
LGTM.

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts [hunk 5]
```diff
@@ -92,7 +92,7 @@ export async function askBucketNameQuestion(context: $TSContext, defaultValues:
   const message = 'Provide bucket name:';
   const onErrorMsg =
     'Bucket name can only use the following characters: a-z 0-9 - and should have minimum 3 character and max of 47 character';
-  const validator = and([alphanumeric(), minLength(3), maxLength(47)], onErrorMsg);
+  const validator = and([matchRegex(onErrorMsg, /^[a-z0-9-]+$/ ),minLength(3), maxLength(47)], onErrorMsg);
```
Comment (danielleadams) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: nit: there seems to be an extra space and missing space here.
```suggestion
  const validator = and([matchRegex(onErrorMsg, /^[a-z0-9-]+$/), minLength(3), maxLength(47)], onErrorMsg);
```

**Review by danielleadams — APPROVED** [review]
Looks good, I think you just need to run lint on the PR.

File: packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts [hunk 6]
```diff
@@ -57,6 +59,14 @@ describe('amplify add/update storage(S3)', () => {
     await validate(projRoot);
   });
 
+  it('init a project and add S3 bucket with hyphenated-name and Auth only access', async () => {
```
Comment (edwardfoyle) [inline packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts:62]: I don't think we should get in the habit of writing an e2e test for input validation. A unit test should be sufficient for this

File: packages/amplify-prompts/src/validators.ts (hunk 4 above)
Comment (edwardfoyle) [reply packages/amplify-prompts/src/validators.ts]: You can reference the validatorRegex if you print the message similar to this: https://github.com/aws-amplify/amplify-cli/pull/9555/files/a34ab8f1c50d9494d3bae6c47b26a1b973aa91fd#diff-cc22b4670cb62aadca66250c5c585c16ceb5d570eebd4792f6363540a2df764dR33
To be consistent with the other validators I would make the regex the first input and then the message an optional second parameter

**Comment by edwardfoyle** [comment]
left a couple follow up comments

File: packages/amplify-prompts/src/validators.ts (hunk 4 above)
Comment (sachscode) [reply packages/amplify-prompts/src/validators.ts]: Thats a good point, maxLength seems to have the length part first, will make the change to keep it consistent!

File: packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts (hunk 6 above)
Comment (sachscode) [reply packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts:62]: This test is to ensure that the hyphenated bucket names created through amplify are correctly pushed. Do you feel it's better to remove this E2E to reduce the amount of time spent in the deployment pipelines?

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts [hunk 7]
```diff
@@ -92,7 +92,7 @@ export async function askBucketNameQuestion(context: $TSContext, defaultValues:
   const message = 'Provide bucket name:';
   const onErrorMsg =
     'Bucket name can only use the following characters: a-z 0-9 - and should have minimum 3 character and max of 47 character';
-  const validator = and([alphanumeric(), minLength(3), maxLength(47)], onErrorMsg);
+  const validator = and([matchRegex( /^[a-z0-9-]+$/ , onErrorMsg ),minLength(3), maxLength(47)], onErrorMsg);
```
Comment (edwardfoyle) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-questions.ts:95]: super nit:
```suggestion
  const validator = and([matchRegex( /^[a-z0-9-]+$/ ),minLength(3), maxLength(47)], onErrorMsg);
```

File: packages/amplify-prompts/src/validators.ts [hunk 8]
```diff
@@ -17,6 +17,11 @@ export const alphanumeric =
   (input: string) =>
     /^[a-zA-Z0-9]+$/.test(input) ? true : message;
 
+export const matchRegex =
+  (validatorRegex : RegExp, message?: string): Validator =>
+  (input: string) =>
+    validatorRegex.test(input) ? true : message || `Input '${message}' does not match the regular expression ${validatorRegex}`;
```
Comment (edwardfoyle) [inline packages/amplify-prompts/src/validators.ts:23]:
```suggestion
    validatorRegex.test(input) ? true : message || `Input does not match the regular expression ${validatorRegex}`;
```

**Review by edwardfoyle — APPROVED** [review]

File: packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts (hunk 6 above)
Comment (danielleadams) [reply packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts:62]: I agree with @edwardfoyle - I think that this is logic that can be tested by a unit test. The behavior isn't impacted by integration of other amplify commands/AWS services, so a unit test should suffice.

Comment (sachscode) [reply packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts:62]: This particular test was added because, there is some logic in the S3 workflow (legacy) which appends information prior to writing to Cloudformation by using hyphens as delimiters in the bucket name. Any future change to this part  of the code will not get caught with Snapshot tests . I can remove this if it feels not required.

File: packages/amplify-prompts/src/validators.ts [hunk 9]
```diff
@@ -17,6 +17,11 @@ export const alphanumeric =
   (input: string) =>
     /^[a-zA-Z0-9]+$/.test(input) ? true : message;
 
+export const matchRegex =
+  (validatorRegex : RegExp, message?: string): Validator =>
+  (input: string) =>
+    validatorRegex.test(input) ? true : message || `Input does not match the regular expression ${validatorRegex}`;
```
Comment (cjihrig) [inline packages/amplify-prompts/src/validators.ts:23]: `test()` returns a boolean, so the ternary here is redundant. However, it looks like that is how the surrounding code is written, so no need to update this.

File: packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts [hunk 10]
```diff
@@ -18,6 +19,7 @@ import {
 } from 'amplify-e2e-core';
 import * as fs from 'fs-extra';
 import * as path from 'path';
+import { getShortId } from '../import-helpers';
```
Comment (cjihrig) [inline packages/amplify-e2e-tests/src/__tests__/storage-1.test.ts:22]: It doesn't look like this is being used either.

File: packages/amplify-e2e-core/src/categories/storage.ts [hunk 11]
```diff
@@ -410,7 +410,7 @@ export function addS3AndAuthWithAuthOnlyAccess(cwd: string, settings: any): Prom
       .wait('Provide a friendly name for your resource')
       .sendCarriageReturn() // Default name
       .wait('Provide bucket name')
-      .sendCarriageReturn() // Default name
+      .sendLine( settings?.bucketName || RETURN )
```
Comment (cjihrig) [inline packages/amplify-e2e-core/src/categories/storage.ts:413]: Is `settings.bucketName` used?

Comment (sachscode) [reply packages/amplify-e2e-core/src/categories/storage.ts:413]: This is an option required if we were to pass a test specific bucketName. This was added to support an E2E test ( to test hyphenated names) which has been removed.

Comment (sachscode) [reply packages/amplify-e2e-core/src/categories/storage.ts:413]: can we keep this in , in case we require test specific bucket-names. ?

Comment (sachscode) [reply packages/amplify-e2e-core/src/categories/storage.ts:413]: removing this.

**Review by cjihrig — APPROVED** [review]
LGTM, just waiting on the CI before merging.
