### PR TITLE
fix: get the defaultEditor value from the localEnvInfo context variable

### LINKED ISSUE #8356: Default editor is shown as `undefined` after project initialization
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.10.0

### Amplify CLI Version

v6.1.1

### What operating system are you using?

mac

### Amplify Categories

Not applicable

### Amplify Commands

init

### Describe the bug

Default editor choice is shown as `undefined` and developers are prompted to choose an editor upon choosing to edit a newly-created resource. In the example shown below, project files are created as expected though without the editor-specific settings file (in this case, `.vscode/settings.json`). This does not have an impact other than requiring the developer to choose an editor upon choosing to edit a newly-created resource.

**NOTE:** after creating a resource (function), choosing to edit, and selecting the editor the editor-specific settings file is created

```shell
> amplify init -y
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
Note: It is recommended to run this command from the root of your app directory
The following configuration will be applied:

Project information
| Name: test
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

Using default provider  awscloudformation
```

If we then run `amplify configure project` we see `undefined` for the default editor:

```shell
> amplify configure project
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.

Project information
| Name: test
| Environment: dev
| Default editor: undefined
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build
| Start Command: npm run-script start

AWS Profile setting
| Selected profile: default

Advanced: Container-based deployments
| Leverage container-based deployments: No
```

Example prompt showcasing the additional prompt for selecting an editor when creating new resources:

```shell
> amplify add function
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
? Select which capability you want to add: Lambda function (serverless function)
? Provide an AWS Lambda function name: teste2662eb6
? Choose the runtime that you want to use: NodeJS
? Choose the function template that you want to use: Hello World

Available advanced settings:
- Resource access permissions
- Scheduled recurring invocation
- Lambda layers configuration
- Environment variables configuration
- Secret values configuration

? Do you want to configure advanced settings? No
? Do you want to edit the local lambda function now? Yes
? Choose your default editor: Visual Studio Code
Edit the file in your editor: /Users/josef/Documents/projects/aws-amplify/reproductions/test/amplify/backend/function/teste2662eb6/src/index.js
? Press enter to continue 
Successfully added resource teste2662eb6 locally.
```

### Expected behavior

- CLI creates editor-specific settings files on init
- CLI retains editor selections and does not subsequently prompt for editor upon resource creation and choice to edit

### Reproduction steps

1. `amplify init -y`
2. `amplify configure project`
3. Observe missing editor-specific settings file and `undefined` for default editor

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flozender**
#### Description of changes
Get the default editor value from the context variable when the `local-env-info.json` file has not been created yet.

#### Issue #, if available
Closes #8356

#### Description of how you validated changes
The default editor now shows up on running `amplify configure project` since the `local-env-info.json` file now has the `defaultEditor` key. `yarn test` also passes.
#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by flozender** [comment]
Ah, yes - that should be better!

**Review by danielleadams — APPROVED** [review]
Looks good. Thanks!

**Comment by danielleadams** [comment]
I was just looking at [this test](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/__tests__/init-steps/s1-initFrontend.test.ts), and it looks like it may be easy to stub the context out and write a unit test. Do you mind adding one? You can add a `s0-analyzeProject.test.ts` to the same directory as the test I linked.

**Comment by flozender** [comment]
Sure, I can get that done!

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts [hunk 1]
```diff
@@ -191,6 +191,10 @@ async function getEditor(context: $TSContext) {
     editor = await editorSelection(editor);
   }
 
+  if (!editor) {
+    editor = context.exeInfo.localEnvInfo.defaultEditor;
```
Comment (danielleadams) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:195]: Last thing - but `exeInfo` has a type `any`, so I think `localEnvInfo` would benefit from optional chaining in the event that it's undefined.

**Review by danielleadams — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

File: packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        name: 'amplify-frontend-flutter',
+        pluginType: 'frontend',
+        pluginName: 'flutter',
+        directory: 'amplify-frontend-flutter',
+      },
+    ];
+    mockContext.exeInfo = {
+      inputParams: {},
+      localEnvInfo: {
+        defaultEditor: 'Visual Studio Code',
```
Comment (sachscode) [inline packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts:35]: Could you please use a defaultEditor value from this list https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/src/extensions/amplify-helpers/editor-selection.ts#L5-L42 . ( please use the value "vscode" instead of the name "Visual Studio Code" in this test)

Comment (flozender) [reply packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts:35]: Sure! I just want to let you know that I modeled my `mockContext.exeInfo` object by capturing at the attribute during `amplify init -y` and I found the `defaultEditor` value to be `Visual Studio Code`, which is why I used the same. 

image

If you'd still like, please let me know and I can change it to `vscode`.

Comment (sachscode) [reply packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts:35]: Thanks! 
it could be that on Windows the executable is named "Visual Studio Code". no need to change then.
