### PR TITLE
fix(amplify-console-hosting): added a null check for prefix on domain

### LINKED ISSUE #4737: amplify status shows hosting subdomain url as null.domain.com
**Describe the bug**

`amplify status` on a webapp that is hosted with amplify returns 
```
Amplify hosting urls: 
┌──────────────┬──────────────────────────────────────────────┐
│ FrontEnd Env │ Domain                                       │
├──────────────┼──────────────────────────────────────────────┤
│ master       │ https://master.mydomain.amplifyapp.com       │
│              ├──────────────────────────────────────────────┤
│              │ https://null.mydomain.com                    │
│              ├──────────────────────────────────────────────┤
│              │ https://www.mydomain.com                     │
└──────────────┴──────────────────────────────────────────────┘
```
From the AWS Console
```
URL | Branch | Redirects to
https://mydomain.com | master | https://www.mydomain.com
https://www.mydomain.com | master | -

```

**Amplify CLI Version**
4.22.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
I expect it to say `https://mydomain.com` instead of `https://null.mydomain.com`

### PR DESCRIPTION
**Pull request by Zanndorin**
added a null check for prefix on domain so that it no longer prints null when not existing

fix #4737

*Issue #, if available:*
#4737
*Description of changes:*
Added a simple null check that should avoid the error described in the issue.

PS: I only changed rows 44-48 the rest I assume was auto-linted on commit/push?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-console-hosting/utils/table-utils.js [hunk 1]
```diff
@@ -37,7 +41,11 @@ async function generateTableContentForApp(context, appId) {
           if (!domainMap[branchName]) {
             domainMap[branchName] = [];
           }
-          domainMap[branchName].push(`https://${prefix}.${domainName}`);
+          if (prefix === null) {
```
Comment (jhockett) [inline packages/amplify-console-hosting/utils/table-utils.js:44]: Change to `if (prefix === null || prefix === undefined) {`
