### PR TITLE
fix: #9341 - handle auth and api dependency in state files correctly

### LINKED ISSUE #9341: "Template error: instance of Fn::GetAtt references undefined resource" when using AdminUI/Studio for changes on Auth.
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d34ljddyp2gbsz

### Region

us-east-1

### Environment name

Staging

### Amplify CLI Version

7.6.3

### If applicable, what version of Node.js are you using?

v17.0.1

### What operating system are you using?

Ubuntu through Windows Linux Subsystem 

### Browser type?

Google Chrome

### Describe the bug

I deployed a very very rudimentary Authentication setup using the AdminUI/Studio. Later I wanted to update the authentication signup flow, so I clicked "Reset all authentication settings and users", with the hopes of updating the sign up flow after.

When the Admin Studio tries to run the deploy to delete the existing auth settings and users, it results in a deployment failure.

These are the logs: 
`Command failed with exit code 1: amplify push --yes --allow-destructive-graphql-schema-updates - Fetching updates to backend environment: staging from the cloud. - Building resource api/Backend ✔ Successfully pulled backend environment staging from the cloud. - Building resource api/Backend - Updating resources in the cloud. This may take a few minutes... ✖ An error occurred when pushing the resources to the cloud ⚠️ Amplify command hooks are disabled in the current execution environment. ⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information. [32mGraphQL schema compiled successfully.[39m [32mEdit your schema at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema[39m [0m[0m [0m Current Environment: staging[0m [0m [0m [90m┌──────────[39m[90m┬───────────────[39m[90m┬───────────[39m[90m┬───────────────────┐[39m [90m│[39m Category [90m│[39m Resource name [90m│[39m Operation [90m│[39m Provider plugin [90m│[39m [90m├──────────[39m[90m┼───────────────[39m[90m┼───────────[39m[90m┼───────────────────┤[39m [90m│[39m Auth [90m│[39m Backend [90m│[39m Delete [90m│[39m awscloudformation [90m│[39m [90m├──────────[39m[90m┼───────────────[39m[90m┼───────────[39m[90m┼───────────────────┤[39m [90m│[39m Api [90m│[39m Backend [90m│[39m No Change [90m│[39m awscloudformation [90m│[39m [90m└──────────[39m[90m┴───────────────[39m[90m┴───────────[39m[90m┴───────────────────┘[39m [32mGraphQL schema compiled successfully.[39m [32mEdit your schema at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /tmp/amplify-d5867ac5-4ff1-4cf1-9d46-188c7b4aa5a7/amplify/backend/api/Backend/schema[39m 🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authBackend.`

When I try to do this operation using `amplify remove auth` and then `amplify push`, 

I get the same final error: 

> Building resource api/BackendGraphQL schema compiled successfully.
> Edit your schema at /mnt/c/Users/Parth/Documents/project/amplify/backend/api/Backend/schema.graphql or place .graphql files in a directory at /mnt/c/Users/Parth/Documents/project/amplify/backend/api/Backend/schema
> ✖ An error occurred when pushing the resources to the cloud
> 🛑 An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authBackend

### Expected behavior

The deployment would complete properly and Amplify AdminUI would delete all users and previous settings, allowing me to revamp my auth flow.

### Reproduction steps

1. Go to Amplify AdminUI/Studio
2. Click Authentication 
3. Scroll to the bottom and click "Reset all authentication settings and users"
4. Click confirm.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by attilah**
#### Description of changes

When a GraphQL API is added/updated in a project, currently there is no `dependsOn` managed between the two resources,  and then the `auth` resource was removed, the `push` operation failed.

This PR updates the `add` and `update` functionality to properly manage the `dependsOn` between the two resources if the API has Cognito auth mode configured.

This PR also updates the `remove` behavior to list all the dependent resources, not just the first one in the error message.

#### Issue #, if available

Fixes #9341
 
#### Description of how you validated changes

Manual testing, updated unit test for remove

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts [hunk 1]
```diff
@@ -140,6 +148,45 @@ class CfnApiArtifactHandler implements ApiArtifactHandler {
 
     this.context.amplify.updateamplifyMetaAfterResourceUpdate(category, apiName, 'output', { authConfig });
     this.context.amplify.updateBackendConfigAfterResourceUpdate(category, apiName, 'output', { authConfig });
+
+    // If we have cognito configured no but before update it was not there then add dependsOn for the API
```
Comment (cjihrig) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts:152]:
```suggestion
    // If we have cognito configured now but before update it was not there then add dependsOn for the API
```

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts [hunk 2]
```diff
@@ -10,7 +10,7 @@ import {
 import { printer } from 'amplify-prompts';
 import * as fs from 'fs-extra';
 import { readTransformerConfiguration, TRANSFORM_CURRENT_VERSION, writeTransformerConfiguration } from 'graphql-transformer-core';
-import _ from 'lodash';
+import _, { has } from 'lodash';
```
Comment (cjihrig) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cfn-api-artifact-handler.ts:13]: LGTM bot is complaining about this being unused.

**Review by yuth — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]
