### PR TITLE
fix: print table summary on verbose status

### LINKED ISSUE #11126: `amplify status -v` returns an empty table
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.2.2

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Amplify Categories

Not applicable

### Amplify Commands

status

### Describe the bug

`amplify status -v` outputs the following.

image

The command previously returned a detailed view of the resources changes.

### Expected behavior

The command is expected to return detailed information on the resources changed.

### Reproduction steps

1. amplify status -v
on latest cli

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

_No response_

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pavellazar**
#### Description of changes
- fix status summary when -v flag is used

#### Description of how you validated changes
- manual test and unit test added

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/input-manager.ts [hunk 1]
```diff
@@ -206,3 +211,47 @@ function aliasArgs(argv: string[]) {
...
+  Object.entries(obj).forEach(([key, value]) => { newObj[key.toLowerCase()] = value; });
+  return newObj;
+};
+
+const normalizeStatusCommandOptions = (input: Input): Input => {
+  const options = input.options ? input.options : {};
+  const allowedVerboseIndicators = [constants.VERBOSE, 'v'];
+  // Normalize 'amplify status -v' to verbose, since -v is interpreted as 'version'
+  allowedVerboseIndicators.forEach(verboseFlag => {
+    if (options[verboseFlag] !== undefined) {
```
Comment (lazpavel) [inline packages/amplify-cli/src/input-manager.ts:226]: main change was changing from `options.verboseFlag` to `options[verboseFlag]`, everything else is just moving the method to another file to keep input logic in a single file

**Review by jhockett — APPROVED** [review]

**Review by danielleadams — APPROVED** [review]
LGTM
