### PR TITLE
fix(auth): standardize CloudFormation trigger templates, prevent errors at runtime

### LINKED ISSUE #4341: cognito trigger postConfirmation template causes `Invalid lambda function output : Invalid JSON` for async handler, works after removing the generated code in index.js
CLI version:
4.20.0

I use Amplify CLI to generate a `postConfirmation` cognito trigger, 

```javascript
exports.handler = async (event) => {
  try {
    // doing some async stuff
  } catch (e) {
    console.log('error', JSON.stringify(e))
    throw e
  }
  console.log('event2', JSON.stringify(event))

  return event
}
```

Every time I `confirmSignUp`, I received a 400 code on the clientside `Invalid lambda function output: Invalid JSON`

Spent a whole night, then this morning I decide to remove all the code in the index.js generated by amplify-cli:

```javascript
exports.handler = (event, context, callback) => {
  const modules = process.env.MODULES.split(',');
  for (let i = 0; i < modules.length; i += 1) {
    const { handler } = require(`./${modules[i]}`);
    handler(event, context, callback);
  }
};
```

As the line here worries me: `handler(event, context, callback)`, as you can see it doesn't have the `await` tag when calling lambda, and I don't know why we need this code in the 1st place, it might be better to explain the `why` part at the top rather than the logic, the logic is straightforward to understand.

I completely removed this part, and moved my handler here, everything works like a charm now. 

As a rough guess, I think the current for loop doesn't compatible with `async` handler. 

Maybe we should just remove it, and replace it with whatever `blahblah.js` which is the main js the user needs to edit.

So:

1. to prevent things like this to happen
1. remove logic that is not user's concern unless it solves some problems (but i definitely don't need this when using serverless framework)
1. the user does not need to figure out which `.js` file to edit.

Thanks :)

### LINKED ISSUE #7179: add-to-group PostConfirmation Lambda fails to return valid JSON with async exit
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

4.48.0

### What operating system are you using?

Ubuntu

### Amplify Categories

auth, function

### Amplify Commands

add, push

### Describe the bug

I ran into this by enabling the "Add User to Groups" functionality in `amplify add auth`. It is an async Lambda hook that is, according to [this page](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html), supposed to be able to just return a value or throw an error, but this is not the case.

I am opening this as an issue in this repo because I intend to send a PR in with a workaround so that this option is at least *more functional* than it is now, as it currently just breaks the sign-up process as the user confirms their email and then Cognito returns a code 400.

See: #2735  #4341

### Expected behavior

The add-to-group PostConfirmation Lambda should not fail.

### Reproduction steps

1. Enable "Add Users to Groups" in `amplify auth`
2. Deploy with `amplify push`
3. Sign ups will throw after a successful email confirmation, when PostConfirmation script fails to return valid JSON

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ctjlewis**
When using the "Add User to Group" functionality with `amplify add auth`, the sign-up process would throw `400` at the `PostConfirmation` Lambda ("Invalid JSON"), where the user was to be added to a given group (see #7179).

After working on this for a day or two and speaking with @edwardfoyle, it seemed there were two issues here:

1. The triggers (`index-trigger.js` in various `template-dir/` directories) did not support async/await, which had multiple implications given that many of these Lambdas used async/await syntax.
2. The top-level Lambda function in `index-trigger.js`, which loads various modules in the same directory (`./verification-link.js`), was **not returning anything**, which was what appears to actually have been causing the "Invalid JSON" error. Sadly, this was present across *all* of the top-level CloudFormation triggers (at least related to auth), which would imply that any `amplify add auth` stack with more than one "advanced feature" enabled would be broken by default. This appears to have been an issue for some time.

This PR addresses both issues. All of the hardcoded `index-trigger.js` files were manually overwritten to use the updated source, and return the `event` that triggered them. Ideally, there would not be duplicate copies of files across directories as that invites bugs like this, but simply getting this working should be a priority for now IMO.

**This issue causes runtime failures in Lambda for any user who enables more than one "advanced feature" in the Amplify CLI ("Add User to Group", etc.).**

#### Description of changes

Before, each template directory had the same `trigger-index.js` copy-pasted into it. It had been edited in a few places to use the async handler format, and this inconsistency is what is causing this/these errors.

Now, there is a `_default` template, and if it is not overridden in the given template, it will pull from the default, meaning there will no longer be redundant/inconsistent copies of `trigger-index.js`, and they will all follow the async handler format. 

#### Issue #, if available

See PR #7180
Closes #7179, closes #4341, #2735 (closed)

#### Description of how you validated changes
I created [ctjlewis/amplify-dev](https://github.com/ctjlewis/amplify-dev) to test the CLI for now; the relevant branch for this issue is [@cloudformation-trigger](https://github.com/ctjlewis/amplify-dev/tree/cloudformation-trigger). 

The `amplify/` directory was deleted, and then the updated `amplify-dev` used to add the Verification Link and Add User to Group features, pushed with `amplify push`, and worked as expected out-of-the-box; this can be found on the [@cloudformation-triggers-patched](https://github.com/ctjlewis/amplify-dev/tree/cloudformation-triggers-patched) branch. I plan to enable all other "advanced features" for auth with `amplify update auth` to test that their updated templates also work as expected.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ctjlewis** [comment]
This also explains why the "Add CAPTCHA" never worked for me, and always just let me through - as an async function, it would never throw because it would immediately resolve without being `await`ed.

**Comment by ctjlewis** [comment]
@edwardfoyle Hate to bug you, but are there any updates on this, regarding our understanding of the CF stands, whether or not the handler should return, etc?

I understand this will take weeks to review, but this was not easy to flesh out (let alone implement) and would appreciate Amplify CLI team at least acknowledging and giving initial comments.

I know we talked in the other thread about Add to Group but I went down the rabbit hole for this PR and am very curious about what everyone's thoughts are.

**Comment by ctjlewis** [comment]
Cold-shouldering contributions for weeks/months makes for a very one-sided open source relationship.  Hate to do it, but if I can't get some notes by next week, I will be retracting these PRs, reserving the copyright, and forbidding derivative work from the previously contributed source code.

I understand that this team has its own priorities, but I do not want to contribute to this library if this is the approach that is taken to PR review. I have spoken with multiple people whose workflow has been derailed by this bug, it is many users' first experience with the CLI, and I am just looking to get some initial notes from this team since my own are the only thing I have to rely on so far.

cc @edwardfoyle @jhockett

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js [hunk 1]
```diff
@@ -1,14 +1,58 @@
...
+ * @param {object} event
+ *
+ * The event that triggered this Lambda.
+ *
+ * @param {object} context
+ *
+ * The context for this Lambda. See:
+ * https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html
+ *
+ * @param {function} callback
```
Comment (cjihrig) [inline packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js:41]: Since this PR is migrating to `async/await` style, are the leftover callbacks still needed?

Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js:41]: I left it in for backwards compatibility. In the linked issues, the way we all worked around was with a `context.done()` call, so there is utility in not immediately ripping it out IMO. If someone passes a `callback`, it will work as expected - I see no reason to violate that.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/function-template-dir/trigger-index.js [hunk 2]
```diff
@@ -1,14 +1,58 @@
...
+ * The event that triggered this Lambda.
+ *
+ * @param {object} context
+ *
+ * The context for this Lambda. See:
+ * https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html
+ *
+ * @param {function} callback
+ *
+ * A deprecated way to send a response synchronously. See:
```
Comment (cjihrig) [inline packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/function-template-dir/trigger-index.js:43]: I don't think we should use "synchronously" here. The linked documentation refers to them as "non-async."

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js [hunk 3]
```diff
@@ -1,14 +1,58 @@
...
+ * @returns
+ *
+ * The CloudFormation trigger event.
+ */
+exports.handler = async (event, context, callback) => {
+  /**
+   * Instead of naively iterating over all handlers, run them concurrently with
+   * `await Promise.all(...)`. This would otherwise just be determined by the
+   * order of names in the `MODULES` var.
+   */
```
Comment (cjihrig) [inline packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js:55]: I think this comment can be removed as well. The legacy implementation would behave the same way if it was calling asynchronous code.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js [hunk 4]
```diff
@@ -2,23 +2,16 @@
...
+  const response = await axios.post(
+    `https://www.google.com/recaptcha/api/siteverify?secret=${process.env.RECAPTCHASECRET}&response=${event.request.challengeAnswer}`,
+    {},
+  );
+
+  if (!(response && response.data && response.data.success)) {
+    event.response.answerCorrect = false;
+    throw new Error('captcha verification error');
+  }
+
```
[the remark this answers is not in the document]
Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js:15]: So in an async handler, we are good to just throw any errors that come up. Before, the logic would resolve with `callback()` if the response was in the correct form. Here, we flip the logic - if the response is *not* correct, throw, otherwise proceed as usual.

I should have documented this, that is my fault, I will also make what is happening here clearer.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js (hunk 3 above)
Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js:55]: This is just clarifying that instead of `for ... of`, we're using `await Promise.all(...)`. I would leave it in, but I will defer to your judgment.

Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js]: See:

https://github.com/aws-amplify/amplify-cli/blob/63e647bb257b8bee4a5bdc12d6902b1375a4da12/packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js#L10-L21

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js]: See:

https://github.com/aws-amplify/amplify-cli/blob/63e647bb257b8bee4a5bdc12d6902b1375a4da12/packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/captcha-verify.js#L10-L21

**Comment by ctjlewis** [comment]
OK, since there were notes on the trigger template, which was pasted into 10 trigger template directories, rather than manually copy-paste the updates I just went ahead and added support for a default trigger template with https://github.com/ctjlewis/amplify-cli/pull/1/, which involved very few changes.

`addTrigger` now looks for each `templateFile` in `triggerDir`, and if it does not find one, it looks for it in the default trigger template `../_default/` (relative to `triggerDir`). Defaults will be loaded, if missing, for any of the defined `templateFiles`:

https://github.com/aws-amplify/amplify-cli/blob/63e647bb257b8bee4a5bdc12d6902b1375a4da12/packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts#L75

---

Now there is *one* `trigger-index.js` and not 10 different versions, some async / some not. I will make the changes to the `trigger-index.js` default template.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js (hunk 1 above)
Comment (cjihrig) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js]: > I left it in for backwards compatibility.

My understanding is that this code is only generated once, and that users updating their projects will not regenerate it. If that's the case, then I think we should really discourage using both callbacks and async/await.

Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js]: I don't think it's immediately obvious what we should do here:

- If we remove it, we basically kill support for any old patterns (new projects will be generated with the new template but old patterns exist in guides and blog posts published on AWS), and we'd want to make it very clear to users that the handlers generated by the CLI will use the async/await form, throw any errors, return values directly.
- If we don't remove it, old code using the callback will still work as written, but we might not be able to guarantee execution order (I think?)

Comment (cjihrig) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js]: The more I think about this, the more I think it's a bad idea to intermingle callbacks and promises like this. For example, the trigger-index files will now be expecting the modules it invokes to return a value to indicate completion. However, if one of those modules does something like this, I think it could cause problems:

```js
setTimeout(() => { callback(); }, 1000);
// Implicit return
```

**Comment by ctjlewis** [comment]
@edwardfoyle, before merging, please see @cjihrig's concerns about the async handler supporting the `callback` parameter.

We may want to remove support for this and add it to the documentation before actually modifying these templates.

**Comment by ctjlewis** [comment]
Please ignore the last comment, which I meant to post in the other PR (GitHub mobile app is awful).

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js (hunk 1 above)
Comment (cjihrig) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/function-template-dir/trigger-index.js]: Hi @ctjlewis. Just following up - are you planning to remove the callbacks in this PR?

**Comment by cjihrig** [comment]
Hi @ctjlewis. Just following up - are you planning to remove the callbacks in this PR?

**Comment by ctjlewis** [comment]
@cjihrig - Could you maybe make the change? I will be unavailable for the next few days. I would also add a comment to clarify it should not be used.

**Comment by ctjlewis** [comment]
@cjihrig Any updates?

**Comment by cjihrig** [comment]
@ctjlewis I also have not had time to work on this yet.

**Comment by ctjlewis** [comment]
@cjihrig This has been updated.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js [hunk 5]
```diff
@@ -1,34 +1,30 @@
 /* eslint-disable-line */ const aws = require('aws-sdk');
 
-exports.handler = async (event, context) => {
-  const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider({ apiVersion: '2016-04-18' });
+exports.handler = async event => {
+  const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider({
```
Comment (cjihrig) [inline packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js:4]: Could this be moved outside of the handler?

File: packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts [hunk 6]
```diff
@@ -45,6 +45,50 @@ export const addTrigger = async triggerOptions => {
...
+   * For each templateFile (i.e. trigger-index.js), use
+   * {triggerDir}/../_default/{templateFile} if {triggerDir}/{templateFile}
+   * override does not exist.
+   */
+  const templateFiles = ['trigger-index.js', 'package.json.ejs', 'event.json'];
+  const sourceFiles = templateFiles.map(file => {
+    const defaultTemplate = path.resolve(defaultRoot, file);
+    const overrideTemplate = path.resolve(sourceRoot, file);
+    const templateToUse = fs.existsSync(overrideTemplate) ? overrideTemplate : defaultTemplate;
+    return path.relative(sourceRoot, templateToUse);
```
Comment (cjihrig) [inline packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts:80]: It looks like `sourceFiles` here is a relative path, but in the previous version, it was just the file's basename. Is that intentional?

**Comment by renebrandel** [comment]
Hi @ctjlewis  - thank you again for this contribution and apologies on the turnaround time. I think we're in the final stretch of the PR here and we would be happy to finish this work during next Friday's bug bash session. Please let us know if you are okay with that.

**Comment by ctjlewis** [comment]
Yes, thanks @renebrandel, that sounds good.

Look forward to seeing it merged, there are users in the various linked issues who I would tag and update once it's fixed.

**Comment by ctjlewis** [comment]
And no worries. It's not the team's fault. Executives are not giving you the resources you need and Amplify is resultantly struggling to survive as a product.

I guarantee the impact of this merge will be measurable if Amplify has any sort of telemetry. 

Please pass my comments along to the person allocating your budget.

**Comment by cjihrig** [comment]
Just a heads up, I'm going to start working on this today. Sorry for the delay.

**Comment by ctjlewis** [comment]
No worries. I just stopped using the product when I ran into this, like most other users in that thread.

And like I said, not you who should be apologizing.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/boilerplate-create-challenge.js [hunk 7]
```diff
@@ -1,12 +1,12 @@
 /* tslint:disable */
 /* eslint-disable */
 
-exports.handler = (event, context) => {
+exports.handler = async (event, context) => {
```
Comment (edwardfoyle) [inline packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/boilerplate-create-challenge.js:4]: nit: could remove context as it's not used anymore (applies to all template functions)

**Review by edwardfoyle — APPROVED** [review]
one nit, otherwise LGTM

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/boilerplate-create-challenge.js (hunk 7 above)
Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/boilerplate-create-challenge.js:4]: I would also recommend adding a small amount of documentation to the README. Link to the async handler docs on AWS and clarify that Amplify generates modern async handlers by default.

File: packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js [hunk 8]
```diff
@@ -1,34 +1,30 @@
...
-      statusCode: 200,
-      body: JSON.stringify(event)
-    }
-  } catch (error) {
-    return {
-      statusCode: 500,
-      body: JSON.stringify(error)
-    }
-  }
+  return event;
```
[the remark this answers is not in the document]
Comment (ctjlewis) [reply packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/add-to-group.js:30]: Just saw this - I don't think so. These changes were needed to get the service working for me. It was completely broken before, it would return before waiting for the result, so it can't be *more* broken in any external parts than it was before, so that could be followed up on independently IMO.

I linked the [ctjlewis/amplify-dev](https://github.com/ctjlewis/amplify-dev) repo for testing.

File: packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts (hunk 6 above)
Comment (ctjlewis) [reply packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts:79]: Yes. The comments could be updated for clarity, but it resolves each file to the default template if an override isn't found, and then resolves it relative to `sourceRoot` for the following call:

https://github.com/aws-amplify/amplify-cli/blob/56c139d31ddaa45741191461699653f96ce353c4/packages/amplify-cli/src/extensions/amplify-helpers/trigger-flow.ts#L98-L103

**Comment by fbdo** [comment]
Hi @edwardfoyle and @ctjlewis , for those (like me) that are already facing this issue, what would be steps to fix an existing project after the release of this PR?

**Comment by ctjlewis** [comment]
@fbdo - look for `trigger-index.js` in your `amplify/` directory and update it with the new version:

https://github.com/aws-amplify/amplify-cli/blob/56c139d31ddaa45741191461699653f96ce353c4/packages/amplify-category-auth/provider-utils/awscloudformation/triggers/function-template-dir/trigger-index.js

Various features (CAPTCHA, Add User to Group, etc.) also had their handlers updated, see the 24 changed files as part of this PR. They are relatively well-commented.

@renebrandel I would recommend that (even *very* light) documentation be added to the README / Amplify docs about how these triggers work. It should:

- prevent similar issues going forward
- help users self-resolve issues that are remain from this bug
- make it easier for the community to contribute fixes related to these triggers and related logic

**Comment by ctjlewis** [comment]
I recommended docs be added three or four times in this thread, but I didn't see any commits related to it.

Should I follow up on this independently? cc @renebrandel
