### PR TITLE
fix(amplify-category-function): fix ddb table name env var

### LINKED ISSUE #3737: Function environment variable for a DynamoDB table name includes "Table" in the name
**Describe the bug**
When adding a new function via `amplify add function`, you can allow access to a data source DynamoDB table. This also provides an environment variable referencing the table name. While the actual DDB table name is something like `Foo-<appsync id>`, the environment variable table name ends up being `FooTable-<appsync id>`. Note, the table ARN environment variable is correct.

**Amplify CLI Version**
4.17.1

**To Reproduce**
* Add a model to your schema.
* `$ amplify add function`
* When granting permissions, select `storage` and select a model.
* `$ amplify push`
* On the AWS console, find the Dynamo table and note the name.
* On the AWS console, find the lambda and not the table name environment variable.

**Expected behavior**
Either the lambda environment variable should drop the `Table` suffix on the table name, or the Dynamo table should be created with the `Table` suffix.

**Additional context**
You can modify the CF template so the environment variable is generated properly.

### LINKED ISSUE #3748: DynamoDB table names generated in a new lambda function are incorrect
**Describe the bug**
When creating a new lambda function and choosing to use an express template, and access other resources, then storage, then a certain table created by GraphQL schema (for example `User@model` it generates the table name in environment variables but the table name is incorrect, for example it generates `UserTable-XXXXX` (where `XXXXX` is the AppSync API ID) but the table name is `User-XXXXXX-dev` (the last word is the environment - dev/prod). So the table name it generates is incorrect.

**Amplify CLI Version**
`"@aws-amplify/cli@4.16.1"`

**Expected behavior**
Amplify CLI generates correct DynamoDB table names

### PR DESCRIPTION
**Pull request by edwardfoyle**
*Issue #, if available:*
fixes #3748 fixes #3737

*Description of changes:*
Correct the DynamoDB table name in lambdas that access model dynamo tables.
Before we were attempting to construct the table name using the naming schema. This updates it to directly reference the exported value from the GraphQL CFN.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts [hunk 1]
```diff
@@ -183,8 +183,8 @@ export async function askExecRolePermissionsQuestions(context, allDefaultValues,
   }
 
   allDefaultValues.categoryPolicies = categoryPolicies;
-  const resourceProperties = [];
-  const resourcePropertiesJSON = {};
+  let resourceProperties = [];
+  let resourcePropertiesJSON = {};
```
Comment (attilah) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts]: put these back to const please, then LGTM.

Comment (edwardfoyle) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts]: fixed
