### PR TITLE
fix(graphql-elasticsearch-transformer): add layer based on region

### LINKED ISSUE #2386: [SEVERE]: Updates to default Botocore Version in AWS Lambda for Python 3.6 BREAKS Amplify ElasticSearch Lambda Streaming Function
**Describe the bug**
Root cause of the symptoms discussed in https://github.com/aws-amplify/amplify-js/issues/4058

I have performed a local test of Python 3.6 Lambda Execution environment to confirm:

printing BOTOCORE version available by default in lambda
according to AWS Docs, this should be 1.10.74 for Python 3.6
ACTUAL BOTOCORE VERSION:
1.12.221

In this botocore version, attempts to import the following module from botocore.endpoint fail:
from botocore.endpoint import BotocoreHTTPSession

This in turn cause every write to ElasticSearch from DDB Stream functions to fail, for all tables. 

**To Reproduce**
In any current amplify environment, visit the logs for the ES Streaming function and confirm that they indicate an error when importing BotocoreHTTPSession

**High Severity**
This change is affecting your customers *without a deployment or amplify push*. Real production customers using your stack are experiencing total failures to write to ES, with no deployment to root cause. For applications that use Amplify ES Search as a core functionality, this is the equivalent of no new records being written to their primary query layer. 

### ⚠️Please treat this as a high severity issue. This is not a drill. ⚠️

### PR DESCRIPTION
**Pull request by nikhname**
Using a map to determine the correct arn layer from the region of the user

fix #2386

*Issue #, if available:*
#2386

*Description of changes:*
Add a layer that contains the previous version of the SDK to the lambda resource based on the region of the user

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/graphql-elasticsearch-transformer/src/resources.ts [hunk 1]
```diff
@@ -11,6 +11,14 @@ import {
 } from 'graphql-mapping-template'
 import { toUpper, plurality, graphqlName, ResourceConstants, ModelResourceIDs } from 'graphql-transformer-common'
 
+interface Mappings {
```
Comment (SwaySway) [inline packages/graphql-elasticsearch-transformer/src/resources.ts]: nit: the mapping interface in here and in transformer context might want to be the same in terms of naming convention though I think it's only best defined in the transformer context

Comment (nikhname) [reply packages/graphql-elasticsearch-transformer/src/resources.ts]: Made this change, interface is now MappingParameters and is imported from transformer context
