### PR TITLE
fix: #2360 - meta json was written as object

### LINKED ISSUE #2360: amplify config gets corrupt, cant run any cli commands
$ amplify add codegen --apiId myapiId       
✔ Getting API details
✖ Getting API details
Unexpected token o in JSON at position 1
$ amplify status

Current Environment: myenv

Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at readJsonFile (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/read-json-file.js:11:17)
    at /home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:279:35
    at step (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:33:23)
    at Object.next (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:14:53)
    at /home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:4:12)
    at getResourceStatus (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:273:12)
    at AmplifyToolkit.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/resource-status.js:320:42)

Since then all amplify commands show the same error.
Before running codegen, I have auth configured and was able to push/status all fine. 

I am running this in a cloud9 environment and so reset the whole env and tried again, same issue. clearly, one of the required files have been corrupt.

my backend-config.json file looks like this-
$ cat backend-config.json 
{
    "auth": {
        "myauthname": {
            "service": "Cognito",
            "providerPlugin": "awscloudformation",
            "dependsOn": []
        }
    }
}
any other file I could check?
How do I reinstate my amplify env without losing what is already configured and how do I move forward?

### PR DESCRIPTION
**Pull request by attilah**
*Issue #, if available:*

Fixes #2360 

*Description of changes:*

meta.json was writing out the JS object instead of the JSON version of the object upon codegen add api operation.

This happened because context.filesystem.write is different with the new plugin system.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by attilah** [comment]
Closing in favor of an incoming PR for context write fix.

File: packages/amplify-codegen/src/utils/updateAmplifyMeta.js [hunk 1]
```diff
@@ -30,15 +30,15 @@ module.exports = async (context, apiDetails) => {
 
 
   const amplifyMetaFilePath = context.amplify.pathManager.getAmplifyMetaFilePath();
-  fs.write(amplifyMetaFilePath, amplifyMeta);
+  fs.write(amplifyMetaFilePath, JSON.stringify(amplifyMeta, null, 2));
```
Comment (UnleashedMind) [inline packages/amplify-codegen/src/utils/updateAmplifyMeta.js]: JSON.stringify() space set to 2 can cause the content hard to read on some editors, the CLI has it as 4 in almost all places.
