### PR TITLE
fix(amplify-category-api): surface override build errors for REST APIs

### LINKED ISSUE #9695: errors not surfaced on failed REST API override builds
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.15

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a	

### Amplify Categories

api

### Amplify Commands

override

### Describe the bug

When some error is present in the REST API's `overrides.ts` file, errors are not surfaced to terminal when building:

```ts
import { AmplifyApiRestResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper'

export function override(resources: AmplifyApiRestResourceStackTemplate) {
  console.log('hello', world)
}
```

It is important to note this does not occur for Auth overrides, where we will receive an error when attempting to build if a similar error is present:

```
🛑 Build error : Packaging overrides failed with the error:
```

### Expected behavior

Errors are printed to the terminal

### Reproduction steps

1. create a new project with `amplify init -y`
2. add a REST API with a sample route, `amplify add api`
3. override the REST API resource with `amplify override api`
4. add an error to the overrides file
5. attempt to build with `amplify build`
6. observe no indication of successful/failed build

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jhockett**
#### Description of changes
- Fixes REST API `overrides.ts` build errors were mistakenly hidden and swallowed.
- Convert use of `.catch` to `try/catch`

#### Issue #, if available
Fixes #9695

#### Description of how you validated changes
Observed expected failure when building invalid TS

```ts
export function override(resources: AmplifyApiRestResourceStackTemplate) {
  console.log('hello', world);
}
```

```bash
➜  api-override-example ad build
🛑 Failed to override api9f20b637 due to: Error: Packaging overrides failed with the error:
Command failed with exit code 2: /Users/johocke/test/api-override-example/amplify/backend/node_modules/.bin/tsc --project /Users/johocke/test/api-override-example/amplify/backend/api/api9f20b637/build/tsconfig.resource.json
../override.ts(22,24): error TS2304: Cannot find name 'world'..
```

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts [hunk 1]
```diff
@@ -186,23 +186,26 @@ export class ApigwStackTransform {
...
     if (isBuild) {
-      const { override } = await import(overrideJSFilePath).catch(error => {
+      let override;
+      try {
+        ({ override } = await import(overrideJSFilePath));
+      } catch {
         formatter.list(['No override file found', `To override ${this.resourceName} run "amplify override api"`]);
-        return undefined;
-      });
+        override = undefined;
```
Comment (sachscode) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:198]: is this required ?  , can we initialize override to undefined on line 193 ( if this is added for warnings ).

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts [hunk 2]
```diff
@@ -186,23 +186,26 @@ export class ApigwStackTransform {
...
-      return false;
-    });
+    const isBuild = await buildOverrideDir(backendDir, overrideFilePath);
 
     // skip if packageManager or override.ts not found
     if (isBuild) {
-      const { override } = await import(overrideJSFilePath).catch(error => {
+      let override;
+      try {
+        ({ override } = await import(overrideJSFilePath));
```
Comment (sundersc) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:195]: nit: does this statement require outer brackets ()?

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts [hunk 3]
```diff
@@ -186,23 +186,26 @@ export class ApigwStackTransform {
...
       if (override && typeof override === 'function') {
-        const overrideCode: string = await fs.readFile(overrideJSFilePath, 'utf-8').catch(() => {
-          formatter.list(['No override File Found', `To override ${this.resourceName} run amplify override auth`]);
-          return '';
-        });
+        let overrideCode: string;
+        try {
+          overrideCode = await fs.readFile(overrideJSFilePath, 'utf-8');
+        } catch (error) {
+          formatter.list(['No override file found', `To override ${this.resourceName} run amplify override auth`]);
```
Comment (sachscode) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:206]: The return value of the formatter is not used looks like. Does this function print to the screen ?

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts [hunk 4]
```diff
@@ -186,23 +186,26 @@ export class ApigwStackTransform {
...
+    const isBuild = await buildOverrideDir(backendDir, overrideFilePath);
 
     // skip if packageManager or override.ts not found
     if (isBuild) {
-      const { override } = await import(overrideJSFilePath).catch(error => {
+      let override;
+      try {
+        ({ override } = await import(overrideJSFilePath));
+      } catch {
         formatter.list(['No override file found', `To override ${this.resourceName} run "amplify override api"`]);
```
Comment (sachscode) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:197]: shouldn't the value of the formatter be printed to the screen or returned from this function ?

Comment (sachscode) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:197]: Should we use printer here ?

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts (hunk 2 above)
Comment (jhockett) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:195]: Parenthesis are required when assignment is separate from declaration: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts (hunk 3 above)
Comment (sachscode) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:206]: Since both these messages are same, can we move it to a function ?

**Review by sachscode — COMMENTED** [review]
Some comments

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts (hunk 4 above)
Comment (sachscode) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:197]: Looks like formatter actually prints to the screen. please disregard this comment

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts (hunk 3 above)
Comment (sachscode) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:206]: formatter seems to print to the screen. please disregard this comment

**Review by sachscode — APPROVED** [review]
LGTM

**Review by sundersc — APPROVED** [review]
LGTM.

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts (hunk 1 above)
Comment (jhockett) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:198]: This was added to keep the logic consistent with the previous `.catch` usage and ensures that the next `if` condition will fail.
