### PR TITLE
fix(gen2-migration): various fixes

### LINKED ISSUE #14730: (gen2-migration) `generate` command doesn't handle auth `aliasAttributes`
### How did you install the Amplify CLI?

Local

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

Local

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

For example, in `cli-inputs.json`:

```json
    "aliasAttributes": [
      "email",
      "preferred_username"
    ],
```

Is ignored during code generation.

### Expected behavior

We should generate an escape hatch:

```console
cfnUserPool.aliasAttributes = ['email', 'preferred_username'];
```

### Reproduction steps

See above

### Project Identifier

_No response_

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Should be handled here:

https://github.com/aws-amplify/amplify-cli/blob/c48d87884fd3bc35b6817f6fef16727bcf081ac0/packages/amplify-cli/src/commands/gen2-migration/generate/amplify/auth/auth.renderer.ts#L424

### Before submitting, please confirm:

- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] I have removed any sensitive information from my code snippets and submission.

### PR DESCRIPTION
**Pull request by iliapolo**
#### Description of changes

Fixes four `gen2-migration generate` issues reported against the migration tooling:

### `aliasAttributes` ignored during codegen. (#14730) 

`deriveUserPoolOverrides` now reads `AliasAttributes` from the Cognito `DescribeUserPool` response and emits `cfnUserPool.aliasAttributes = [...]` as an escape hatch in `backend.ts`. The Cognito mock also returns `aliasAttributes` from `cli-inputs.json` so snapshot tests exercise the new path.

### Buildspec only matched `amplifyPush --simple` (#14724) 

The `GEN1_COMMAND` regex now uses `amplifyPush\b.*` so any variant (`--force`, `--simple --yes`, etc.) is replaced with the Gen2 pipeline-deploy commands. A `\b` word boundary prevents false matches on unrelated strings like `amplifyPushSomething`.

### `npm install` fails on older apps (#14721) 

Removed `DependenciesInstaller` and the operation that deleted `package-lock.json` / `node_modules` before running `npm install` twice. The generate step now logs a message instructing the user to run `npm install` themselves, avoiding brittle auto-install on apps with legacy dependency trees.

### Missing `cli-inputs.json` crashes with an opaque error (#14726) 

Added `Gen1App.ensureCliInputs()` which throws a `MigrationError` with a resolution pointing to the Gen1 CLI migration guide. Each category assessor calls it at the start of `record()`, so old-CLI apps are caught during assessment. The auth-cognito assessor skips the check for imported resources (they don't have `cli-inputs.json`).

Tested by:

1. Install amplify v6
2. Configure an app with auth and storage
3. Observe `cli-inputs.json` is missing (it used to be `parameters.json`)
4. Update to amplify v14
5. Follow migration guide
6. Observed `parameters.json` converted to `cli-inputs.json` 

#### Issue #, if available

Closes #14730, #14724, #14721, #14726

#### Description of how you validated changes

- All 423 existing gen2-migration tests pass (55 suites, 67 snapshots).
- New unit tests for each fix:
  - `auth.renderer.test.ts`: 6 tests for `deriveUserPoolOverrides` (aliasAttributes present/absent/empty, usernameAttributes, password policy).
  - `auth.generator.test.ts`: integration snapshot test verifying `backend.ts` output includes the `aliasAttributes` override.
  - `amplify.yml.generator.test.ts`: 5 tests covering `--simple`, `--force`, arbitrary flags, word boundary, and default backend-only spec.
  - `gen1-app.test.ts`: test for `ensureCliInputs` throwing `MigrationError` with resolution.
  - All assessor test mocks updated with `ensureCliInputs`.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are changed or added
- [x] Relevant documentation is changed or added (and PR referenced)
- [x] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [x] Pull request labels are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/commands/gen2-migration/generate.ts [hunk 1]
```diff
@@ -183,35 +181,23 @@ export class AmplifyMigrationGenerateStep extends AmplifyMigrationStep {
...
-
-        if (await fileOrDirectoryExists(nodeModulesPath)) {
-          this.logger.info('Deleting node_modules');
-          await fs.rm(nodeModulesPath, { recursive: true });
-        }
-
-        this.logger.info('Installing dependencies');
-        await DependenciesInstaller.install();
+        this.logger.info(
+          'Run "npm install" to install the new Gen2 dependencies. ' +
```
Comment (dgandhi62) [inline packages/amplify-cli/src/commands/gen2-migration/generate.ts:190]: We should also add a comment in the migration guide

File: packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts [hunk 2]
```diff
@@ -123,13 +123,15 @@ export class CognitoIdentityProviderMock {
         }
 
         const usernameAttributes: string[] = authCliInputs.cognitoConfig.usernameAttributes ?? [];
+        const aliasAttributes: string[] = authCliInputs.cognitoConfig.aliasAttributes ?? [];
```
Comment (dgandhi62) [inline packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts:126]: Is it expected for inputs for `generate` to be under the `__tests` folder?

**Review by dgandhi62 — COMMENTED** [review]
Clarifying Questions

File: packages/amplify-cli/src/commands/gen2-migration/generate.ts (hunk 1 above)
Comment (iliapolo) [reply packages/amplify-cli/src/commands/gen2-migration/generate.ts:190]: Yeah we'll add that later.

File: packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts (hunk 2 above)
Comment (iliapolo) [reply packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts:126]: What do you mean? this is grabbing it from the `cli-inputs.json` in our snapshot directory.

Comment (dgandhi62) [reply packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts:126]: Ah! Do we already have access to AliasAttributes on our existing object in `generate`? 

I didn't see logic added for fetching it specifically in `generate` but I saw it in `__tests` so I got a bit confused

Comment (iliapolo) [reply packages/amplify-cli/src/__tests__/commands/gen2-migration/_framework/clients/cognito-identity-provider.ts:126]: Yeah the `AliasAttributes` are already available in the user pool we response. This PR just adds this:

https://github.com/aws-amplify/amplify-cli/blob/f8a08f65a10ed55e10fb6a7a4f700d00555e89c3/packages/amplify-cli/src/commands/gen2-migration/generate/amplify/auth/auth.renderer.ts#L438-L440

The mock in the snapshot tests gets it from `cli-inputs.json`, though it probably should take it from the template...but oh well. our apss don't even configure this property anyway.

**Review by dgandhi62 — APPROVED** [review]
