### PR TITLE
fix(amplify-category-custom): validate that the project has been initialized

### LINKED ISSUE #8920: `add custom` does not fail on uninitialized projects
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

7.x

### What operating system are you using?

macos

### Amplify Categories

Not applicable

### Amplify Commands

add

### Describe the bug

In an empty folder `amplify add custom` does not fail early.

image

### Expected behavior

fail with project the error before asking any prompts.

### Reproduction steps

1. mkdir foo
2. cd foo
3. amplify add custom

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SebasRod23**
#### Description of changes

Get meta file to validate that the project has been initialized before running the command

#### Issue #, if available

Closes #8920 

#### Description of how you validated changes

It uses the `pathManager` to validate that the meta file exist, if it doesn't then the it will throw a `NotInitializedError` before trying to run the command. This applies for every command in the `custom` category.
#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-custom/src/index.ts [hunk 1]
```diff
@@ -18,6 +18,8 @@ export async function executeAmplifyCommand(context: $TSContext) {
 
   const commandModule = await import(commandPath);
 
+  pathManager.getAmplifyMetaFilePath();
```
Comment (jhockett) [inline packages/amplify-category-custom/src/index.ts:21]: This should work, but it's confusing to rely on the error throwing side effect of `pathManager.getAmplifyMetaFilePath();` when we don't need the meta file path.

A better solution would be to add a stateManager method like `isProjectInitialized()` and call that here. That will make it easier to provide a useful error message, instead of throwing an error.

**Review by jhockett — CHANGES_REQUESTED** [review]
Hi @SebasRod23, thanks for the contribution! I left a comment about reworking the solution to be more maintainable. Let me know if you are able to implement the changes or if you have any questions.

File: packages/amplify-category-custom/src/index.ts (hunk 1 above)
Comment (SebasRod23) [reply packages/amplify-category-custom/src/index.ts:21]: Thank you for the feedback. I just have some questions: should I still call `pathManager.getAmplifyMetaFilePath()` in the `isProjectInitialized()` to validate that the project is initialized or is there a better way to do the validation? and, should the new method throw an error or just the error message?

Comment (jhockett) [reply packages/amplify-category-custom/src/index.ts:21]: On second thought, I think we can just use an existing stateManager method and leave a comment. I think implementing `isProjectInitialized()` robustly is out of scope for this issue.

```ts
// Check if project has been initialized
if (!stateManager.metaFileExists()) {
  printer.error('Could not find the amplfiy-meta.json file. Make sure your project is initialized in the cloud.');
}
```

**Review by jhockett — APPROVED** [review]

**Review by ammarkarachi — APPROVED** [review]
