### PR TITLE
fix(amplify-codegen): make codegen multienv aware

### LINKED ISSUE #1243: Is the codegen command multi-env aware?
** Which Category is your question related to? **
codegen

** What AWS Services are you utilizing? **
amplify cli, appsync, amplify codegen

** Provide additional details e.g. code snippets **
Is the codegen command multi-env aware? .graphqlconfig.yml does not change when I change envs.

### PR DESCRIPTION
**Pull request by yuth**
Amplify codegen relied graphql config file to figure out the AppSync API ID to download the
introspection schema. With the introduction of multienv, the API ID changes based on the current
environment. Updated codegen to use the API ID from amplify meta to make codegen multienv aware

fix #1243

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-codegen/src/commands/add.js [hunk 1]
```diff
@@ -80,13 +80,11 @@ async function add(context, apiId = null) {
     excludes: answer.excludePattern,
     schema,
     amplifyExtension: {
-      graphQLApiId: apiDetails.id,
       codeGenTarget: answer.target || '',
       generatedFileName: answer.generatedFileName || '',
       docsFilePath: answer.docsFilePath,
       region,
     },
-    endpoint: apiDetails.endpoint,
```
Comment (kaustavghosh06) [inline packages/amplify-codegen/src/commands/add.js]: Did you use the endpoint anywhere in the statement or doc generation? or was it just the appID?

Comment (yuth) [reply packages/amplify-codegen/src/commands/add.js]: We don't use it anywhere. Even with the endpoint present user will have to do some custom headers to support the Auth for AppSync.
