### PR TITLE
fix: #9363 - additional checks in case of previously failed add auth

### LINKED ISSUE #9363: amplify add auth breaks entire project
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

17.2.0

### Amplify CLI Version

7.6.4

### What operating system are you using?

macOS 10.15.7

### Amplify Categories

auth

### Amplify Commands

add

### Describe the bug

After running `amplify add auth` and following all steps of manual configuration (see complete log below) now all the project is broken. Every time I run an Amplify command I get the following error: `Name: TypeError : Message: Cannot read properties of undefined (reading 'serviceType')`

### Expected behavior

Auth category to be correctly added without breaking anything.

### Reproduction steps

See logs below.

### GraphQL schema(s)

N/A

### Log output

<details>

```
# Put your logs below this line
esmbp1015:codistica-website ernestostifano$ amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or
 other content, Analytics, and more)
 Provide a friendly name for your resource that will be used to label this category in the project: CodisticaWebsiteAuth
 Enter a name for your identity pool. CodisticaWebsiteIdentityPool
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes
 Do you want to enable 3rd party authentication providers in your identity pool? No
 Provide a name for your user pool: CodisticaWebsiteUserPool
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email
 Do you want to add User Pool Groups? Yes
? Provide a name for your user pool group: admins
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: customers
? Do you want to add another User Pool Group No
✔ Sort the user pool groups in order of preference · admins, customers
 Do you want to add an admin queries API? Yes
? Do you want to restrict access to the admin queries API to a specific Group Yes
? Select the group to restrict access with: admins
 Multifactor authentication (MFA) user login options: OPTIONAL (Individual users can use MFA)
 For user login, select the MFA types: Time-Based One-Time Password (TOTP)
 Specify an SMS authentication message: Your authentication code is {####}
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Specify an email verification subject: Your verification code
 Specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? Yes
 Enter the minimum password length for this User Pool: 8
 Select the password character requirements for your userpool: Requires Lowercase, Requires Uppercase, Requires Numbers, Requires Symbols
 Warning: you will not be able to edit these selections. 
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? Email Verification Link with Redirect, Add User to Group
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No
2021-12-21T12:42:16.049Z - error: uncaughtException: Cannot read properties of undefined (reading 'push') date=Tue Dec 21 2021 13:42:16 GMT+0100 (Central European Standard Time), pid=9538, uid=501, gid=20, cwd=/Users/ernestostifano/repositories/codistica-website, execPath=/usr/local/Cellar/node/17.2.0/bin/node, version=v17.2.0, argv=[/usr/local/Cellar/node/17.2.0/bin/node, /usr/local/bin/amplify, add, auth], rss=597618688, heapTotal=533700608, heapUsed=494870648, external=3239868, arrayBuffers=1300582, loadavg=[1.3837890625, 1.638671875, 1.560546875], uptime=14176, trace=[column=38, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts, function=AmplifyAuthCognitoStack.generateCognitoStackResources, line=382, method=generateCognitoStackResources, native=false, column=27, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, function=AmplifyAuthTransform.generateStackResources, line=95, method=generateStackResources, native=false, column=16, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts, function=AmplifyAuthTransform.transform, line=69, method=transform, native=false, column=10, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-stack-template.ts, function=generateAuthStackTemplate, line=6, method=null, native=false, column=7, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts, function=null, line=68, method=null, native=false, column=3, file=/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js, function=Object.executeAmplifyCommand, line=421, method=executeAmplifyCommand, native=false, column=3, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts, function=executePluginModuleCommand, line=204, method=null, native=false, column=5, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts, function=executeCommand, line=30, method=null, native=false, column=5, file=/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts, function=Object.run, line=205, method=run, native=false], stack=[TypeError: Cannot read properties of undefined (reading 'push'),     at AmplifyAuthCognitoStack.generateCognitoStackResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts:382:38),     at AmplifyAuthTransform.generateStackResources (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts:95:27),     at AmplifyAuthTransform.transform (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts:69:16),     at generateAuthStackTemplate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-stack-template.ts:6:10),     at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/provider-utils/awscloudformation/handlers/resource-handlers.ts:68:7,     at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:3),     at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3),     at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5),     at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)]
esmbp1015:codistica-website ernestostifano$ amplify add auth
Auth has already been added to this project. To update run amplify update auth.
esmbp1015:codistica-website ernestostifano$ amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Cannot read properties of undefined (reading 'serviceType')
TypeError: Cannot read properties of undefined (reading 'serviceType')
    at getResourcesToBeCreated (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:220:65)
    at AmplifyToolkit.getResourceStatus [as _getResourceStatus] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/resource-status-data.ts:117:35)
    at getAuthResourceName (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/utils/getAuthResourceName.ts:4:50)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/commands/auth/update.ts:58:49)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/amplify-category-auth/src/index.js:421:23)
    at /usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:222:45
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
esmbp1015:codistica-website ernestostifano$ amplify status
Name: TypeError : Message: Cannot read properties of undefined (reading 'serviceType')
esmbp1015:codistica-website ernestostifano$ 


```

</details>

### Additional information

This was the first category to be added, so project was "fresh", only CI/CD hosting was present and correctly working.

### PR DESCRIPTION
**Pull request by attilah**
#### Description of changes

#9214 is a duplicate of #9363, this PR fix the 2nd part of #9363 which helps with already corrupted project files, where User Pool Groups are already present in meta file, but Cognito addition failed.

#### Issue #, if available

Fixes #9363 

#### Checklist

- [X] PR description included
- [X] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts [hunk 1]
```diff
@@ -217,8 +217,9 @@ export function getResourcesToBeCreated(amplifyMeta, currentAmplifyMeta, categor
           (!amplifyMeta[dependsOnCategory][dependsOnResourcename]?.lastPushTimeStamp ||
             !currentAmplifyMeta[dependsOnCategory] ||
             !currentAmplifyMeta[dependsOnCategory][dependsOnResourcename]) &&
-          amplifyMeta[dependsOnCategory][dependsOnResourcename].serviceType !== 'imported' &&
-          !resources.includes(amplifyMeta[dependsOnCategory][dependsOnResourcename])
+          amplifyMeta[dependsOnCategory][dependsOnResourcename]?.serviceType !== 'imported' &&
+          !resources.includes(amplifyMeta[dependsOnCategory][dependsOnResourcename]) &&
+          amplifyMeta[dependsOnCategory][dependsOnResourcename]
```
Comment (cjihrig) [inline packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts:222]: Can you move this up two lines (so that it's before the `serviceType` check). That way, the logic should short circuit a little faster.

**Review by cjihrig — APPROVED** [review]

File: packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts (hunk 1 above)
Comment (yuth) [inline packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts:222]:
```suggestion
          amplifyMeta[dependsOnCategory][dependsOnResourcename] && 
          amplifyMeta[dependsOnCategory][dependsOnResourcename]?.serviceType !== 'imported' &&
          !resources.includes(amplifyMeta[dependsOnCategory][dependsOnResourcename])
```

Comment (attilah) [reply packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts]: Yathi also moved around these, took those changes.
