### PR TITLE
fix(cli): fixed projName and envName

### LINKED ISSUE #5399: Added tags via tags.json to an existing amplify project are inverting their default values
**Describe the bug**
Added tags via tags.json to an existing amplify project are inverting their default values

**Amplify CLI Version**
4.29.1

**To Reproduce**
Add tags as describe here [tags](https://docs.amplify.aws/cli/usage/tags)
Run amplify push. The value of **{project-env}** is switching by the value of **{project-name}**.

tags.json:
```
[
  {
    "Key": "user:Stack",
    "Value": "{project-env}"
  },
  {
    "Key": "user:Application",
    "Value": "{project-name}"
  }
]
```
Using the following project values:
**_project-env value: heroes
project-name value: aws-amplify-ninja_**

It results with the following tags:

**_user:Stack -> aws-amplify-ninja
user:Application -> heroes_**

**Expected behavior**
Assign the respect values for **{project-env}** and **{project-name}**
tags.json
```
[
  {
    "Key": "user:Stack",
    "Value": "{project-env}"
  },
  {
    "Key": "user:Application",
    "Value": "{project-name}"
  }
]
```

Resulting in the following tags:

**_user:Stack -> heroes
user:Application -> aws-amplify-ninja_**

**Screenshots**
amplify-issue-inverting-values-for-tags

**Desktop (please complete the following information):**
 - OS: Mac/Ubuntu
 - Node Version. 10.20.1

**Additional context**

**_Thanks in advance 
paco :rocket:_**

### PR DESCRIPTION
**Pull request by ammarkarachi**
fixes #5399

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by attilah — CHANGES_REQUESTED** [review]
Could you add some e2e tests that verifies the deployed tags to make sure it is working correctly niw?

File: packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export function getTags() {
   const projectDetails = getProjectDetails();
   const { projectName } = projectDetails.projectConfig;
   const { envName } = projectDetails.localEnvInfo;
-  return HydrateTags(stateManager.getProjectTags(), projectName, envName);
+  return HydrateTags(stateManager.getProjectTags(), envName, projectName);
```
Comment (yuth) [inline packages/amplify-cli/src/extensions/amplify-helpers/get-tags.ts:7]:
```suggestion
  return HydrateTags(stateManager.getProjectTags(), { envName, projectName });
```

**Review by nikhname — APPROVED** [review]

**Review by attilah — APPROVED** [review]

**Review by yuth — APPROVED** [review]
