### PR TITLE
fix(amplify-category-notifications): remove env name

### LINKED ISSUE #1372: backend-config.json has env specific stack name for notifications
**Describe the bug**
Notifications section of backend-config.json is being named with env instead of this dynamically happening during deploy.

Eg:

Checkout dev:
```
    "notifications": {
        "amplifyreactappdemoudAOX-dev": {
            "service": "Pinpoint",
            "channels": []
        }
    }
```

Checkout test:
```
    "notifications": {
        "amplifyreactappdemobrrHH-test": {
            "service": "Pinpoint",
            "channels": []
        }
    }
```
It's also changing some random string there too.  The rest of the file doesn't change when switching between environments.  This obviously is an issue given this file is managed under source control and shouldn't change just because we switch between environments.

### PR DESCRIPTION
**Pull request by UnleashedMind**
remove env name from the resource name in the notification category
in both the amplify-meta.json file and the backend-config.json file

projects configured by the previous versions will be automatically handled without customers' efforts. 

fix #1372

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-notifications/index.js [hunk 1]
```diff
@@ -25,7 +21,6 @@ module.exports = {
   console,
   deletePinpointAppForEnv,
   initEnv,
-  initEnvPush,
```
Comment (kaustavghosh06) [inline packages/amplify-category-notifications/index.js]: Why is this removed? I beleive this would break a few things including migration?

Comment (UnleashedMind) [reply packages/amplify-category-notifications/index.js]: that was an unneeded leftover from last year, we were talking about possibly separating initEnv locally and then push, but that's not the workflow we used.
