### PR TITLE
fix: opensearch instance type check during push

### LINKED ISSUE #10362: Upgrading to v2, getting "Your instance type for OpenSearch is t2.small.elasticsearch, you may experience..." even though it is set to medium
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.2

### Amplify CLI Version

8.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

I am upgrading from v1 to v2, and in my `team-provider-info.json`, I already had medium instances, but updated to use OpenSearchInstanceType:
```
{
  "prod": {
    "categories": {
      "api": {
        "my-api": {
          "OpenSearchInstanceType": "t2.medium.elasticsearch"
        }
      }
    }
  }
}
```

I have all my environments using t2.medium, but I am getting the warning during the `amplify push` step that it is being set to t2.small.elasticsearch). This was not an issue on v1.

### Expected behavior

Do not show warning and correctly set t2.medium.elasticsearch

### Reproduction steps

Cannot really describe given I have a large v1 api. But I have followed migration steps defined [here](https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate)

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AaronZyLee**
#### Description of changes

Use `OpenSearchInstanceType` for transformer v2 pre push check. `ElasticSearchInstanceType` will be checked afterwards when OS is not found
#### Issue #, if available
fix #10362 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-provider-awscloudformation/src/graphql-transformer/api-utils.ts [hunk 1]
```diff
@@ -8,13 +8,13 @@ export async function searchablePushChecks(context, map, apiName): Promise<void>
     if (searchableModelTypes.length) {
       const currEnv = context.amplify.getEnvInfo().envName;
       const teamProviderInfo = stateManager.getTeamProviderInfo();
+      const version = await getTransformerVersion(context);
       const instanceType = _.get(
         teamProviderInfo,
-        [currEnv, 'categories', 'api', apiName, ResourceConstants.PARAMETERS.ElasticsearchInstanceType],
+        [currEnv, 'categories', 'api', apiName, version === 2 ? ResourceConstants.PARAMETERS.OpenSearchInstanceType : ResourceConstants.PARAMETERS.ElasticsearchInstanceType],
```
Comment (alharris-at) [inline packages/amplify-provider-awscloudformation/src/graphql-transformer/api-utils.ts:14]: Is it possible to model this as a fallthrough condition instead?

```ts
const getInstanceType(instanceTypeParam: string): string? => _.get(teamProviderInfo, [currEnv, 'categories', 'api', apiName, instanceTypeParam]);
const instanceType =
    getInstanceType(ResourceConstants.PARAMETERS.OpenSearchInstanceType) ??
    getInstanceType(ResourceConstants.PARAMETERS.ElasticsearchInstanceType) ??
    't2.small.elasticsearch';
```

I'd like to avoid explicitly checking for transformer version as much as possible.

**Review by sundersc — APPROVED** [review]
LGTM.
