### PR TITLE
fix: do not delete if generated filename is empty

### LINKED ISSUE #4519: 'amplify delete' deletes all my project, including source files
**Describe the bug**
When typing `amplify delete`, the CLI not only deletes my amplify configuration, but it cleans up the entire project, deleting all my source files as well.

**Amplify CLI Version**
amplify --version
4.21.2

**To Reproduce**
Follow the steps described in the Amplify iOS workshop 

1. Download a Sample Project : https://amplify-ios-workshop-new.go-aws.com/20_getting_started/20_bootstrapping_the_app.html

2. Configure Amplify Tools : https://amplify-ios-workshop-new.go-aws.com/20_getting_started/30_configuring_amplify.html

3. in the project directory, type `amplify delete`

**Expected behavior**
`amplify delete` should delete the amplify configuration and backend infrastructure but should not delete my project source files !

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.5
 - Node Version. You can use `node -v` to check the node version on your system
 node --version
v14.4.0

**Additional context**
```bash
➜  Landmarks amplify delete
? Are you sure you want to continue? This CANNOT be undone. (This would delete all the environments of the project from the cloud and wipe out all the local fil
es created by Amplify CLI) Yes
⠋ Deleting resources from the cloud. This may take a few minutes...
Deleting env:amplify
✔ Project deleted in the cloud
ENOTEMPTY: directory not empty, rmdir '/Users/stormacq/Downloads/amplify-ios-workshop/Complete/Landmarks'
Error: ENOTEMPTY: directory not empty, rmdir '/Users/stormacq/Downloads/amplify-ios-workshop/Complete/Landmarks'
    at Object.rmdirSync (fs.js:865:3)
    at rmkidsSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:308:25)
    at rmdirSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at Object.rimrafSync (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:39:10
    at Array.forEach (<anonymous>)
    at Object.deleteAmplifyConfig [as deleteConfig] (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:32:27)
    at AmplifyToolkit.deleteProject [as _deleteProject] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/delete-project.js:36:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➜  Landmarks ls -al
total 16
drwxr-xr-x@ 3 stormacq  1896053708    96 Jun 10 16:53 .
drwxr-xr-x  8 stormacq  1896053708   256 Jun 10 16:35 ..
-rw-r--r--@ 1 stormacq  1896053708  6148 Jun 10 16:53 .DS_Store
```

### PR DESCRIPTION
**Pull request by nikhname**
*Issue #, if available:*
fix #4519
*Description of changes:*
Prevent root files being deleted when generatedfilename is empty

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-frontend-ios/lib/frontend-config-creator.js [hunk 1]
```diff
@@ -35,8 +35,9 @@ function deleteAmplifyConfig(context) {
         const file = path.join(srcDirPath, docsFilePath, `${filename}.${FILE_EXTENSION_MAP[codeGenTarget]}`);
         if (fs.existsSync(file)) fs.removeSync(file);
       });
-
-      fs.removeSync(path.join(srcDirPath, generatedFileName));
+      if (generatedFileName !== '') {
```
Comment (ammarkarachi) [inline packages/amplify-frontend-ios/lib/frontend-config-creator.js]: It's still not a good idea to check for empty string

Comment (ammarkarachi) [reply packages/amplify-frontend-ios/lib/frontend-config-creator.js]: Can you check if it's a directory or make it sure it's a file?

Comment (nikhname) [reply packages/amplify-frontend-ios/lib/frontend-config-creator.js]: Checking if empty string is the only way, because the generatedfilename by itself is **not** a path

Comment (nikhname) [reply packages/amplify-frontend-ios/lib/frontend-config-creator.js]: It is not bad practice to make a check for empty string

**Comment by yuth** [comment]
Could we get some unit/e2e tests around this?

**Comment by nikhname** [comment]
Functionality for removing the generated file path does not seem to exist in the other frontend plugins

**Comment by ammarkarachi** [comment]
@yuth I am merging this I will create another PR for the tests
