### PR TITLE
fix(amplify-category-api): Fix #2498

### LINKED ISSUE #2498: Amplify api add-graphql-datasource fails when Query Editor secret is available
**Describe the bug**
After selecting database the command fails with `No RDS access credentials found in the AWS Secret Manager.`, however there are available generated secret by Query Editor as well as another custom secret.

**To Reproduce**
1. Setup RDS with Aurora MySQL 5.6 Compatible (Serverless)
2. Login via query editor, create DB and tables
3. Try to add datasource

**Expected behavior**
Datasource is successfully added

**Possible reason**
If there is generated secret, this condition succeeds and `selectedSecretArn`.
https://github.com/aws-amplify/amplify-cli/blob/8b225c1f9f16fed303adaaa91831bac7752d579d/packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js#L131-L133
This causes this condition to be rendered as `false` and trigger exit in else statement
https://github.com/aws-amplify/amplify-cli/blob/8b225c1f9f16fed303adaaa91831bac7752d579d/packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js#L139-L146

**Possible solution**
Change last if to 
```js
if (!selectedSecretArn) {
  if (secrets.size > 0) {
  // Kick off questions flow
    const selectedSecretName
       = await promptWalkthroughQuestion(inputs, 2, Array.from(secrets.keys()));
      selectedSecretArn = secrets.get(selectedSecretName);
  } else {
    context.print.error('No RDS access credentials found in the AWS Secrect Manager.');
    process.exit(0);      
  }
}
```
**Additional context**
- Windows 10 Pro
- amplify-cli v3.11.0

### PR DESCRIPTION
**Pull request by TrueLecter**
Fixes 'No RDS access credentials found in the AWS Secret Manager' when Query Editor secret is found

*Issue:* #2498

*Description of changes:* Adds nested `if` to fix exit logic if generated secret was found.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js [hunk 1]
```diff
@@ -136,13 +136,15 @@ async function getSecretStoreArn(context, inputs, clusterResourceId, AWS) {
...
-    // Kick off questions flow
-    const selectedSecretName = await promptWalkthroughQuestion(inputs, 2, Array.from(secrets.keys()));
-    selectedSecretArn = secrets.get(selectedSecretName);
-  } else {
-    context.print.error('No RDS access credentials found in the AWS Secrect Manager.');
-    process.exit(0);
+  if (!selectedSecretArn) {
+    if (secrets.size > 0) {
+      // Kick off questions flow
+      const selectedSecretName = await promptWalkthroughQuestion(inputs, 2, Array.from(secrets.keys()));
```
Comment (nikhname) [inline packages/amplify-category-api/provider-utils/awscloudformation/service-walkthroughs/appSync-rds-walkthrough.js]: Just a small nit, this line exceeds our maximum line length of 100 characters - could you move some of it to the next line? Thanks!
