### PR TITLE
fix(amplify-util-mock): fixes #3319 java version check

### LINKED ISSUE #3319: amplify mock api throws dynamodb emulator error for amplify version 4.13.1
**Describe the bug**
Failed to start API Mock endpoint Error: max retries hit for starting dynamodb emulator

**Amplify CLI Version**
$ amplify --version
4.13.1

**To Reproduce**
I had amplify mock api command working perfectly fine. I just upgrade the amplify-cli package using the command -- $ npm install -g @aws-amplify/cli

The package upgraded properly to 4:13.1 and then the amplify mock would not start with the above error

**Desktop (please complete the following information):**
I am using Cloud9 Amazon Linux

$ node -v
v10.16.2

**Additional context**

I think I was on 4.12 before the upgrade

**Expected behavior**
The local DynamoDB should run and it should create the local tables. Please note that I did not change anything in the schema that could have caused this issue. 

Also when I press ctrl-c to exit the process, I keep getting the following error that does not go away.
^C(node:3863) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stop' of undefined
    at APITest.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:74:41)
    at Generator.next (<anonymous>)
    at /home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:4:12)
    at APITest.stop (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:58:16)
    at APITest.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:31:32)
    at Generator.next (<anonymous>)
    at /home/ec2-user/.nvm/versions/node/v10.16.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/lib/api/api.js:8:71
    at new Promise (<anonymous>)
(node:3863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### PR DESCRIPTION
**Pull request by akshbhu**
*Issue #3319 

*Description of changes:

* java version check while starting local dynaodb

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yuth** [comment]
# [Codecov](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=h1) Report
> Merging [#3511](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=desc) into [master](https://codecov.io/gh/aws-amplify/amplify-cli/commit/9aae9a6681c5ff744d908b5292a5b00faa14de4d&el=desc) will **increase** coverage by `0.55%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #3511      +/-   ##
==========================================
+ Coverage   58.67%   59.22%   +0.55%     
==========================================
  Files         286      283       -3     
  Lines       13370    13245     -125     
  Branches     2672     2662      -10     
==========================================
  Hits         7845     7845              
+ Misses       5100     4977     -123     
+ Partials      425      423       -2     
```


| [Impacted Files](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...l-mock/src/CFNParser/resource-processors/lambda.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL0NGTlBhcnNlci9yZXNvdXJjZS1wcm9jZXNzb3JzL2xhbWJkYS50cw==) | | |
| [packages/amplify-util-mock/src/index.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL2luZGV4LnRz) | | |
| [...plify-util-mock/src/\_\_e2e\_\_/utils/cognito-utils.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL19fZTJlX18vdXRpbHMvY29nbml0by11dGlscy50cw==) | | |
| [...amplify-util-mock/src/utils/mock-data-directory.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL3V0aWxzL21vY2stZGF0YS1kaXJlY3RvcnkudHM=) | | |
| [...es/amplify-util-mock/src/api/resolver-overrides.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL2FwaS9yZXNvbHZlci1vdmVycmlkZXMudHM=) | | |
| [packages/amplify-util-mock/src/api/index.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL2FwaS9pbmRleC50cw==) | | |
| [...ages/amplify-util-mock/src/amplify-plugin-index.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL2FtcGxpZnktcGx1Z2luLWluZGV4LnRz) | | |
| [packages/amplify-util-mock/src/utils/ddb-utils.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL3V0aWxzL2RkYi11dGlscy50cw==) | `0.00% <0.00%> (ø)` | |
| [...plify-util-mock/src/api/run-graphql-transformer.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL2FwaS9ydW4tZ3JhcGhxbC10cmFuc2Zvcm1lci50cw==) | `0.00% <0.00%> (ø)` | |
| [packages/amplify-util-mock/src/storage/storage.ts](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree#diff-cGFja2FnZXMvYW1wbGlmeS11dGlsLW1vY2svc3JjL3N0b3JhZ2Uvc3RvcmFnZS50cw==) | `0.00% <0.00%> (ø)` | |
| ... and [2 more](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=footer). Last update [9aae9a6...8af4796](https://codecov.io/gh/aws-amplify/amplify-cli/pull/3511?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

File: packages/amplify-util-mock/src/api/api.ts [hunk 1]
```diff
@@ -78,6 +83,21 @@ export class APITest {
     this.resolverOverrideManager.stop();
   }
 
+  async checkJavaversion() {
+    var javaSpawn = spawnSync('java', ['-version'], {
```
Comment (nikhname) [inline packages/amplify-util-mock/src/api/api.ts]: Can you make sure spawning 'java' on windows does not throw an error

Comment (akshbhu) [reply packages/amplify-util-mock/src/api/api.ts]: yes , I tested it, it works
