### PR TITLE
fix: revert running amplify version on install

### LINKED ISSUE #10528: CLI 8.4.0 amplify upgrade:  Command failed with exit code 1: C:\Users\erstraub\.amplify\bin\amplify.exe --version
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

amplify upgrade

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

8.3.1

### What operating system are you using?

Windows 10, also confirmed on  11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

Not applicable

### Amplify Commands

update

### Describe the bug

Was on amplify 8.3.1 and upgraded to 8.4.0 with `amplify upgrade`

The command reported the error but Amplify 8.4.0 was installed and working. 
 
image

### Expected behavior

Amplify upgrade should complete w/o any warnings or errors.

### Reproduction steps

use amplify to upgrade:   `amplify upgrade`  or `amplify --upgrade`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sachscode**
Reverted code to check version on installation to resolve #10528 
#### Description of changes
Removed code and test to run amplify --version on the installed binary immediately. 

#### Issue #, if available
#10528 

#### Description of how you validated changes
yarn test upgrade.pkg

#### Checklist

- [*] PR description included
- [*] `yarn test` passes
- [*] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/commands/upgrade.ts [hunk 1]
```diff
@@ -78,17 +78,6 @@ const upgradeCli = async (print, version: string) : Promise<void> => {
   await downloadPromise;
   await fs.move(extractedPath, binPath, { overwrite: true });
   await fs.chmod(binPath, '700');
-  // Load the new version of amplify-cli into memory to optimize subsequent runs and check if it runs without error.
-  const spinner:ora.Ora = ora('Validating downloaded Amplify CLI....');
```
Comment (jhockett) [inline packages/amplify-cli/src/commands/upgrade.ts:82]: If this is the only usage of ora, let's remove the import too

**Review by jhockett — APPROVED** [review]

File: packages/amplify-cli/src/commands/upgrade.ts (hunk 1 above)
Comment (sachscode) [reply packages/amplify-cli/src/commands/upgrade.ts:82]: Great catch,  removed ora and execa

**Review by ammarkarachi — APPROVED** [review]
