### PR TITLE
fix: nexpect pathname parsing (#7324)

### LINKED ISSUE #7324: Pathname parsing bug in Nexpect library
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.1

### Amplify CLI Version

4.50.2

### What operating system are you using?

Ubuntu 20.04 LTS

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

This bug was discovered while working on #7098

Some points to be considered:
- Amplify installation directory lies in **`/DOCUMENTS/SSD/MLH Fellowship/AWS Amplify/aws-amplify`** (note the spaces in the pathname)
- The issue exists in the core Nexpect library

How the bug was discovered:

1. While verbose logging during running E2E tests in the `amplify-e2e-tests` package, the following error was occurring in the system:
image

2. On close inspection of the verbose logs provided, the following console log was found:
image

3. Heading over to the reports generated by `jest-html-reporters` and `asciinema-recorder` packages, the following terminal session recording was found:
image

As per the screenshots above, it is clearly noticed that there is a pathname parsing bug in the `nexpect` library that does not parse pathnames with spaces properly, and it trims the pathname from the first space it finds in the pathname. That is how the pathname transforms to **`DOCUMENTS/SSD/MLH`**, which causes the test runner to not find the executable binary.

### Expected behavior

There should be support for spaces in the pathname while calling the test runner, else it might cause issues in any user's system who has stored the repository in a folder whose pathname may have spaces in between.

### Reproduction steps

1. Shift the amplify repository to a folder containing spaces in its pathname.
For example: **`/home/$USER/AWS Amplify/aws-amplify`**
2. Try to execute the E2E tests inside the `amplify-e2e-tests` package (in this case, the env was being tested), optionally enabling the verbose logging like:
**`env VERBOSE_LOGGING_DO_NOT_USE_OR_YOU_WILL_BE_FIRED=true yarn e2e env.test.ts`**
3. The above errors will be reproduced.

### GraphQL schema(s)

_No response_

### Log output

_No response_

### Additional information

On closer inspection, the following lines [**(596-598)**](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-core/src/utils/nexpect.ts#L595-L597) in `nexpect.ts` is causing the error:

image

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
#### Description of changes

This PR fixes the nexpect pathname parsing bug, where nexpect trims pathnames with spaces in it.

#### Issue #, if available

Fixes #7324 

#### Description of how you validated changes
The environment tests located in `amplify-e2e-tests` is passing.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-e2e-core/src/utils/nexpect.ts [hunk 1]
```diff
@@ -592,9 +593,9 @@ export function nspawn(command: string | string[], params: string[] = [], option
     params = command;
     command = params.shift();
   } else if (typeof command === 'string') {
-    command = command.split(' ');
-    params = params || command.slice(1);
-    command = command[0];
+    const parsedPath = parse(command);
+    command = join(parsedPath.dir, parsedPath.base.split(' ')[0]);
+    params = params || parsedPath.base.split(' ').splice(1);
```
Comment (cjihrig) [inline packages/amplify-e2e-core/src/utils/nexpect.ts:598]: You could alternatively use `slice()` instead of `splice()` here.

File: packages/amplify-e2e-core/src/utils/nexpect.ts [hunk 2]
```diff
@@ -592,9 +593,9 @@ export function nspawn(command: string | string[], params: string[] = [], option
     params = command;
     command = params.shift();
   } else if (typeof command === 'string') {
-    command = command.split(' ');
-    params = params || command.slice(1);
-    command = command[0];
+    const parsedPath = parse(command);
+    command = join(parsedPath.dir, parsedPath.base.split(' ')[0]);
```
Comment (cjihrig) [inline packages/amplify-e2e-core/src/utils/nexpect.ts:597]: Can you put `parsedPath.base.split(' ')` in a variable.

**Review by cjihrig — APPROVED** [review]
From some quick testing, the updated path parsing logic here seems to work. LGTM.

**Review by cjihrig — APPROVED** [review]
