### PR TITLE
fix(graphql-relational-schema-transformer): fix #3025 rds resolver correctly handles no data in response

### LINKED ISSUE #3025: Autogenerated response template crashes when using Aurora
**Describe the bug**
Hello,

I am using Aurora Serverless as a data source.
When amplify generates code for the response templates, there are basically 2 types, one for elements, and the other one for collections:
`$utils.toJson($utils.rds.toJsonObject($ctx.result)[0][0])`
and
`$utils.toJson($utils.rds.toJsonObject($ctx.result)[0])`

The problem I have is that, when I use a query that returns one elements, instead of a collection, like for example getPost/getComment/getUser or similar, if the element that I am requesting is not in the data base (or the id I am passing is wrong), then I receive this error:
message": "Error invoking method 'get(java.lang.Integer)' in java.util.ArrayList at velocity[line 4, column 54]"

I guess the reason is because there is no data structure at [0][0].
So, should I modify my template doing something like?:

```
#if ($context.source.WHATEVER == 0) 
   #return([])
#end
$utils.toJson($utils.rds.toJsonObject($ctx.result)[0][0])
```

What do you think about this? Thanks.

**Amplify CLI Version**
4.2.0

**To Reproduce**
Use Amazon Serverless as a data source for AppSync. Generate code using "amplify api" and "amplify api add-graphql-datasource" 

**Expected behavior**
I should receive no element, not sure as an error or as an empty element. But not that strange error message about javascript.

**Desktop (please complete the following information):**
 - OS: Catalina. 10.15.1 (19B88)
 - Node Version. v13.2.0

**Additional context**
Can you explain to me how I should solve this problem manually (while you fix the code generation)?

EDIT: I guess the same would happen with collections when the collection is empty. I didn't try that tough.

EDIT2: Here more info about how to solve it: https://adrianhall.github.io/cloud/2019/01/03/early-return-from-graphql-resolvers/

### PR DESCRIPTION
**Pull request by edwardfoyle**
Correctly handle cases where the specified query to Aurora does not match any stored entities.

*Issue #, if available:*
#3025

*Description of changes:*
Before, if no data matched the query to Aurora, this would result in a cryptic VTL error. Now the behavior is:
On a get request return null
On a delete request return null
On an update request throw a helpful error

This matches the behavior of a dynamodb datasource.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/graphql-mapping-template/src/ast.ts [hunk 1]
```diff
@@ -360,6 +380,10 @@ export function block(name: string, exprs: Expression[]): CompoundExpressionNode
   return compoundExpression([comment(`[Start] ${name}`), ...exprs, comment(`[End] ${name}`)]);
 }
 
+export function methodCall(methodName: ReferenceNode, ...params: Expression[]): CompoundExpressionNode {
+  return compoundExpression([methodName, parens(compoundExpression(params, ', '))], '', !RECURSE_INDENT);
```
Comment (SwaySway) [inline packages/graphql-mapping-template/src/ast.ts]: `!RECURSE_INDENT` might not be needed here as a default argument is already specified on the compoundExpression itself.

File: packages/graphql-mapping-template/src/ast.ts [hunk 2]
```diff
@@ -388,4 +412,11 @@ export type Expression =
...
   | ToJsonNode
   | NotNode
-  | NewLineNode;
+  | NewLineNode
+  | ReturnNode;
+
+/**
+ * Can be used as a parameter to iff() and others to more clearly specify "inline" parameter
+ */
+export const INLINE = true;
```
Comment (SwaySway) [inline packages/graphql-mapping-template/src/ast.ts]: nit: I don't think these are necessary since there are default arguments are used in the functions that use `INLINE` and `RECURSE_INDENT`

File: packages/graphql-mapping-template/src/ast.ts (hunk 1 above)
Comment (edwardfoyle) [reply packages/graphql-mapping-template/src/ast.ts]: The default is true though (for backwards compatibility with the old behavior when that was not a parameter) and here it needs to be false
