### PR TITLE
fix(amplify-provider-awscloudformation): reverse asc events

### LINKED ISSUE #6578: Cloudformation messages are printed in the wrong order
**Describe the bug**

The CLI polls CF for status messages and getting it in chunks. Then we are printing it to the screen as we have received it, but it is in the wrong order, the latest entry is on the top:

image

**Amplify CLI Version**
4.41.2

**To Reproduce**
Push any project, observe the timestamps of the printed messages

**Expected behavior**
Print messages in correct order

### PR DESCRIPTION
**Pull request by watilde**
Fixes #6578

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js [hunk 1]
```diff
@@ -454,7 +454,15 @@ function formatOutputs(outputs) {
 }
 
 function showEvents(events) {
-  events = events.sort((a, b) => new Date(a.Timestamp) > new Date(b.Timestamp));
+  events = events.sort((a, b) => {
```
Comment (attilah) [inline packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:457]: I would not use sort based on timestamp because CFN already sorts the events for us, we just get it in reverse order, and if we get two events with the same timestamp we can hit an issue that we'll still print it in wrong order. Please update to just reverse the entries and it will be ok

**Review by attilah — DISMISSED** [review]
Thanks for the contribution, I added a comment on the implementation, please update it and the it is good to be merged.

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js (hunk 1 above)
Comment (watilde) [reply packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js]: Thank you for your review! That is good to know. As that sounds to require domain knowledge, I left that as a comment in the implementation.

**Review by edwardfoyle — APPROVED** [review]
