### PR TITLE
fix(cli): fixes issues for missing build or start command

### LINKED ISSUE #3728: `amplify publish` does not correctly exit if the build fails
### **Describe the bug**
When running `amplify publish`, any failures during the build do not correctly exit, therefore subsequent commands are run when they shouldn't.

### **Amplify CLI Version**
4.16.1

### **To Reproduce**
1. Initialize an app with CRA and amplify.
```bash
npx create-react-app some-app-name
cd some-app-name
amplify init
amplify hosting add
```
2. Break the React build, e.g. import something that doesn't exist.
```javascript
// App.js
import BreakTheBuild from './DoesNotExist'
```
3. Run the following command, and notice how the `echo` command runs even though the `amplify publish` command fails.
```bash
amplify publish -y && echo FINISH
```
4. Run the following command, and notice how the `echo` command does not run after `yarn build` fails.
```bash
yarn build && echo FINISH
``` 

### **Expected behavior**
When the build fails during the `amplify publish` command, it should correctly exit so no further commands are run.

### **Desktop:**
 - OS: Mac
 - Node Version. v10.14.1

### LINKED ISSUE #3806: The argument 'file' cannot be empty. Received ''
**Describe the bug**
I'm not exactly sure, it just started happening recently. I'm not sure what the cause is. It started with an existing project and has since plagued me. I'm not sure if it is related to the auth module, the hosting module, or something else. This time I didn't use API, so it isn't that. 

**To Reproduce**
I'm sure some of the options are important so I've included a log. To star with before running amplify init I ran expo init and choose "tabs". After that I ran amplify init

The exact console log is below. I was trying to add auth.

**Expected behavior**
Previously I was given the ability to log in using HOC's. Currently I can't get amplify to work for me. I've used a similar process before, bu it isn't working now and I'm not sure what is different.

**Screenshots**
Instead of a screenshot, here is a log of my amplify init:
```
 tom  ~  Sync  test  amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project test
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react-native
? Source Directory Path:  /
? Distribution Directory Path: /
? Build Command:  
? Start Command: expo start --web
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
Adding backend environment dev to AWS Amplify Console app: d2ini5tciv80bv
⠦ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket        AWS::S3::Bucket            Sun Mar 29 2020 17:15:07 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UnauthRole              AWS::IAM::Role             Sun Mar 29 2020 17:15:07 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                AWS::IAM::Role             Sun Mar 29 2020 17:15:07 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket        AWS::S3::Bucket            Sun Mar 29 2020 17:15:06 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UnauthRole              AWS::IAM::Role             Sun Mar 29 2020 17:15:06 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS AuthRole                AWS::IAM::Role             Sun Mar 29 2020 17:15:06 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS amplify-test-dev-171459 AWS::CloudFormation::Stack Sun Mar 29 2020 17:15:02 GMT-0400 (Eastern Daylight Time) User Initiated             
⠸ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Sun Mar 29 2020 17:15:19 GMT-0400 (Eastern Daylight Time) 
CREATE_COMPLETE AuthRole   AWS::IAM::Role Sun Mar 29 2020 17:15:19 GMT-0400 (Eastern Daylight Time) 
⠧ Initializing project in the cloud...

CREATE_COMPLETE amplify-test-dev-171459 AWS::CloudFormation::Stack Sun Mar 29 2020 17:15:30 GMT-0400 (Eastern Daylight Time) 
CREATE_COMPLETE DeploymentBucket        AWS::S3::Bucket            Sun Mar 29 2020 17:15:28 GMT-0400 (Eastern Daylight Time) 
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
“amplify console” to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything

 tom  ~  Sync  test  amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Email and Phone Number
 Do you want to configure advanced settings? No, I am done.
 What domain name prefix you want us to create for you? test6277f392-6277f392
 Enter your redirect signin URI: http://localhost:3000/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:3000/
? Do you want to add another redirect signout URI No
 Select the social providers you want to configure for your user pool: 
Successfully added resource test6277f392 locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

 tom  ~  Sync  test  amplify publish

Please add hosting to your project before publishing your project
Command: amplify hosting add

 tom  ~  Sync  test  amplify hosting add
? Select the plugin module to execute Hosting with Amplify Console (Managed hosting with custom domains, Continuous deployment)
? Choose a type Manual deployment

You can now publish your app using the following command:

Command: amplify publish
 tom  ~  Sync  test  amplify publish
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Auth     | test6277f392   | Create    | awscloudformation |
| Hosting  | amplifyhosting | Create    | awscloudformation |
? Are you sure you want to continue? Yes
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS authtest6277f392               AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:50 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS hostingamplifyhosting          AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS authtest6277f392               AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS hostingamplifyhosting          AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time)                            
UPDATE_IN_PROGRESS amplify-test-dev-171459        AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:44 GMT-0400 (Eastern Daylight Time) User Initiated             
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-test-dev-171459-authtest6277f392-1UMJQS9ADOGU0 AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:50 GMT-0400 (Eastern Daylight Time) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-test-dev-171459-hostingamplifyhosting-1SH2WYO0SKHTV AWS::CloudFormation::Stack Sun Mar 29 2020 17:21:49 GMT-0400 (Eastern Daylight Time) User Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS AmplifyBranch AWS::Amplify::Branch Sun Mar 29 2020 17:21:53 GMT-0400 (Eastern Daylight Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Sun Mar 29 2020 17:21:57 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS SNSRole AWS::IAM::Role Sun Mar 29 2020 17:21:56 GMT-0400 (Eastern Daylight Time)                            
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UpdateRolesWithIDPFunctionRole AWS::IAM::Role Sun Mar 29 2020 17:22:03 GMT-0400 (Eastern Daylight Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    AmplifyBranch AWS::Amplify::Branch Sun Mar 29 2020 17:22:05 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS AmplifyBranch AWS::Amplify::Branch Sun Mar 29 2020 17:22:05 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE amplify-test-dev-171459-hostingamplifyhosting-1SH2WYO0SKHTV AWS::CloudFormation::Stack Sun Mar 29 2020 17:22:07 GMT-0400 (Eastern Daylight Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE SNSRole AWS::IAM::Role Sun Mar 29 2020 17:22:11 GMT-0400 (Eastern Daylight Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE hostingamplifyhosting AWS::CloudFormation::Stack Sun Mar 29 2020 17:22:11 GMT-0400 (Eastern Daylight Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Sun Mar 29 2020 17:22:14 GMT-0400 (Eastern Daylight Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:20 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    UserPool          AWS::Cognito::UserPool       Sun Mar 29 2020 17:22:17 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPool          AWS::Cognito::UserPool       Sun Mar 29 2020 17:22:17 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClient AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:20 GMT-0400 (Eastern Daylight Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolClient    AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:22 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    UserPoolClientWeb AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:22 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClient    AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:22 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientWeb AWS::Cognito::UserPoolClient Sun Mar 29 2020 17:22:22 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Sun Mar 29 2020 17:22:26 GMT-0400 (Eastern Daylight Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Sun Mar 29 2020 17:22:26 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UserPoolClientRole AWS::IAM::Role Sun Mar 29 2020 17:22:39 GMT-0400 (Eastern Daylight Time) 
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    HostedUICustomResource          AWS::Lambda::Function Sun Mar 29 2020 17:22:45 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    HostedUIProvidersCustomResource AWS::Lambda::Function Sun Mar 29 2020 17:22:44 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    UserPoolClientLambda            AWS::Lambda::Function Sun Mar 29 2020 17:22:44 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS HostedUICustomResource          AWS::Lambda::Function Sun Mar 29 2020 17:22:44 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResource AWS::Lambda::Function Sun Mar 29 2020 17:22:44 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResource          AWS::Lambda::Function Sun Mar 29 2020 17:22:44 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClientLambda            AWS::Lambda::Function Sun Mar 29 2020 17:22:43 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResource AWS::Lambda::Function Sun Mar 29 2020 17:22:43 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClientLambda            AWS::Lambda::Function Sun Mar 29 2020 17:22:43 GMT-0400 (Eastern Daylight Time)                            
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sun Mar 29 2020 17:22:50 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResourcePolicy          AWS::IAM::Policy Sun Mar 29 2020 17:22:49 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UserPoolClientLambdaPolicy            AWS::IAM::Policy Sun Mar 29 2020 17:22:49 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sun Mar 29 2020 17:22:49 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS HostedUICustomResourcePolicy          AWS::IAM::Policy Sun Mar 29 2020 17:22:48 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClientLambdaPolicy            AWS::IAM::Policy Sun Mar 29 2020 17:22:48 GMT-0400 (Eastern Daylight Time)                            
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE UserPoolClientLambdaPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:01 GMT-0400 (Eastern Daylight Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientLogPolicy               AWS::IAM::Policy Sun Mar 29 2020 17:23:05 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResourceLogPolicy       AWS::IAM::Policy Sun Mar 29 2020 17:23:05 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClientLogPolicy               AWS::IAM::Policy Sun Mar 29 2020 17:23:04 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:02 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    HostedUICustomResourcePolicy          AWS::IAM::Policy Sun Mar 29 2020 17:23:01 GMT-0400 (Eastern Daylight Time)                            
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:05 GMT-0400 (Eastern Daylight Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:06 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResourceLogPolicy          AWS::IAM::Policy Sun Mar 29 2020 17:23:06 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:19 GMT-0400 (Eastern Daylight Time) 
CREATE_COMPLETE HostedUICustomResourceLogPolicy          AWS::IAM::Policy Sun Mar 29 2020 17:23:18 GMT-0400 (Eastern Daylight Time) 
CREATE_COMPLETE UserPoolClientLogPolicy                  AWS::IAM::Policy Sun Mar 29 2020 17:23:17 GMT-0400 (Eastern Daylight Time) 
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UserPoolClientInputs Custom::LambdaCallout Sun Mar 29 2020 17:23:21 GMT-0400 (Eastern Daylight Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UserPoolClientInputs                  Custom::LambdaCallout Sun Mar 29 2020 17:23:25 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UserPoolClientInputs                  Custom::LambdaCallout Sun Mar 29 2020 17:23:24 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResourceInputs          Custom::LambdaCallout Sun Mar 29 2020 17:23:22 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs Custom::LambdaCallout Sun Mar 29 2020 17:23:22 GMT-0400 (Eastern Daylight Time)                            
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResource                   AWS::Lambda::Function      Sun Mar 29 2020 17:23:30 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS IdentityPool                          AWS::Cognito::IdentityPool Sun Mar 29 2020 17:23:30 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_COMPLETE    HostedUICustomResourceInputs          Custom::LambdaCallout      Sun Mar 29 2020 17:23:28 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS IdentityPool                          AWS::Cognito::IdentityPool Sun Mar 29 2020 17:23:28 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS HostedUICustomResourceInputs          Custom::LambdaCallout      Sun Mar 29 2020 17:23:28 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_COMPLETE    HostedUIProvidersCustomResourceInputs Custom::LambdaCallout      Sun Mar 29 2020 17:23:26 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs Custom::LambdaCallout      Sun Mar 29 2020 17:23:26 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    IdentityPool        AWS::Cognito::IdentityPool Sun Mar 29 2020 17:23:31 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS OAuthCustomResource AWS::Lambda::Function      Sun Mar 29 2020 17:23:30 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourcePolicy AWS::IAM::Policy                         Sun Mar 29 2020 17:23:35 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS OAuthCustomResourcePolicy AWS::IAM::Policy                         Sun Mar 29 2020 17:23:34 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS IdentityPoolRoleMap       AWS::Cognito::IdentityPoolRoleAttachment Sun Mar 29 2020 17:23:34 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    OAuthCustomResource       AWS::Lambda::Function                    Sun Mar 29 2020 17:23:31 GMT-0400 (Eastern Daylight Time)                            
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    IdentityPoolRoleMap AWS::Cognito::IdentityPoolRoleAttachment Sun Mar 29 2020 17:23:36 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS IdentityPoolRoleMap AWS::Cognito::IdentityPoolRoleAttachment Sun Mar 29 2020 17:23:36 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:50 GMT-0400 (Eastern Daylight Time) 
CREATE_COMPLETE    OAuthCustomResourcePolicy    AWS::IAM::Policy Sun Mar 29 2020 17:23:47 GMT-0400 (Eastern Daylight Time) 
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:23:52 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE OAuthCustomResourceLogPolicy AWS::IAM::Policy Sun Mar 29 2020 17:24:04 GMT-0400 (Eastern Daylight Time) 
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceInputs Custom::LambdaCallout Sun Mar 29 2020 17:24:07 GMT-0400 (Eastern Daylight Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    amplify-test-dev-171459-authtest6277f392-1UMJQS9ADOGU0 AWS::CloudFormation::Stack Sun Mar 29 2020 17:24:14 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    OAuthCustomResourceInputs                              Custom::LambdaCallout      Sun Mar 29 2020 17:24:11 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS OAuthCustomResourceInputs                              Custom::LambdaCallout      Sun Mar 29 2020 17:24:11 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE authtest6277f392 AWS::CloudFormation::Stack Sun Mar 29 2020 17:24:29 GMT-0400 (Eastern Daylight Time) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Sun Mar 29 2020 17:24:34 GMT-0400 (Eastern Daylight Time)                            
CREATE_COMPLETE    UpdateRolesWithIDPFunction        AWS::Lambda::Function Sun Mar 29 2020 17:24:32 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UpdateRolesWithIDPFunction        AWS::Lambda::Function Sun Mar 29 2020 17:24:31 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
CREATE_IN_PROGRESS UpdateRolesWithIDPFunction        AWS::Lambda::Function Sun Mar 29 2020 17:24:31 GMT-0400 (Eastern Daylight Time)                            
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Sun Mar 29 2020 17:24:38 GMT-0400 (Eastern Daylight Time)                            
CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Sun Mar 29 2020 17:24:38 GMT-0400 (Eastern Daylight Time) Resource creation Initiated
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-test-dev-171459 AWS::CloudFormation::Stack Sun Mar 29 2020 17:24:40 GMT-0400 (Eastern Daylight Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE amplify-test-dev-171459 AWS::CloudFormation::Stack Sun Mar 29 2020 17:24:41 GMT-0400 (Eastern Daylight Time) 
✔ All resources are updated in the cloud

Hosted UI Endpoint: https://test6277f392-6277f392-dev.auth.us-east-1.amazoncognito.com/
Test Your Hosted UI Endpoint: https://test6277f392-6277f392-dev.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=4bmv04ron1gl6fpla2hsmk5ti1&redirect_uri=http://localhost:3000/


Publish started for amplifyhosting
The argument 'file' cannot be empty. Received ''
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at normalizeSpawnArguments (child_process.js:409:11)
    at spawn (child_process.js:542:16)
    at /home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/utils/build-utils.js:36:23
    at new Promise (<anonymous>)
    at Object.run (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/utils/build-utils.js:32:10)
    at buildArtifacts (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/manual/publish.js:49:17)
    at Object.publish (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/manual/publish.js:24:13)
    at Object.publish (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/manual/index.js:12:19)
    at Object.publish (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/hosting/index.js:45:23)
    at Object.publish (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-console-hosting/index.js:37:19)
    at Object.run (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/publisher.js:36:31)
    at Object.publish (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:37:20)
    at Object.run (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/src/commands/publish.js:42:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.executeAmplifyCommand (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:101:3)
    at executePluginModuleCommand (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:158:7)
    at Object.executeCommand (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:24:5)
    at Object.run (/home/tom/.npm-global/lib/node_modules/@aws-amplify/cli/src/index.ts:45:5)
 tom  ~  Sync  test  
```

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
    Memory: 4.84 GB / 15.53 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
  npmPackages:
    @babel/core: ~7.6.0 => 7.6.4 
    @react-native-community/netinfo: 4.7.0 => 4.7.0 
    @types/react: ~16.9.0 => 16.9.26 
    @types/react-native: ~0.60.23 => 0.60.31 
    aws-amplify: ^2.2.1 => 2.2.7 
    aws-amplify-react: ^3.1.2 => 3.1.8 
    aws-amplify-react-native: ^2.2.3 => 2.3.3 
    babel-preset-expo: ~8.0.0 => 8.0.0 
    expo: ~36.0.0 => 36.0.2 
    jest-expo: ~36.0.0 => 36.0.1 
    jetifier: ~1.6.4 => 1.6.5 
    react: ~16.9.0 => 16.9.0 
    react-dom: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
    react-native-gesture-handler: ~1.5.0 => 1.5.6 
    react-native-reanimated: ~1.4.0 => 1.4.0 
    react-native-screens: ~2.0.0-alpha.12 => 2.0.1 
    react-native-unimodules: ~0.7.0 => 0.7.0 
    react-native-web: ~0.11.7 => 0.11.7 
    react-router-dom: ^5.1.2 => 5.1.2 
    react-router-native: ^5.1.2 => 5.1.2 
    typescript: ~3.6.3 => 3.6.5 
  npmGlobalPackages:
    @aws-amplify/cli: 4.17.2
    expo-cli: 3.16.1
    yarn: 1.22.4
```

</details>


**Sample code**
I used expo init with tabs to simplify the process and ensure it was reproducible and not something code related.

### PR DESCRIPTION
**Pull request by UnleashedMind**
fix #3728, fix #3806

*Issue #, if available:*

*Description of changes:*
fixes issues for missing build or start command or when the commands exit with none zero code

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/index.ts [hunk 1]
```diff
@@ -55,12 +54,12 @@ export async function run(): Promise<number> {
     if (e.stack) {
       print.info(e.stack);
     }
-    return 1;
+    process.exit(1);
```
Comment (attilah) [inline packages/amplify-cli/src/index.ts:57]: Can't we bubble up return code and handle process exit at the top level? is this the best solution?

Comment (UnleashedMind) [reply packages/amplify-cli/src/index.ts:71]: This is actually the top most level, the amplify in the bin directly calls this run method.
