### PR TITLE
fix(graphql): avoid duplicate function when overriding resolvers

### LINKED ISSUE #9650: overrid an auto generated pipeline resolver create another function
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
I overriden an auto generated pipline resolver (just the res.vtl file) using this gide https://docs.amplify.aws/cli/graphql/custom-business-logic/#override-amplify-generated-resolvers  it overrid it just fine, but  it also created another function with the same res.vtl and $util.toJson({}) for the req.vtl

**Amplify CLI Version** 
7.6.13
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

### PR DESCRIPTION
**Pull request by sundersc**
#### Description of changes

Avoid creating a duplicate function when overriding a generated resolver.

#### Issue #, if available

Fixes #9650 

#### Description of how you validated changes
- E2E test
- Manual test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts [hunk 1]
```diff
@@ -162,14 +162,59 @@ export class TransformerResolver implements TransformerResolverProvider {
       slotEntry = [];
     }
 
-    slotEntry.push({
-      requestMappingTemplate,
-      responseMappingTemplate,
-      dataSource,
-    });
+    if (!this.updateSlotIfExists(slotName, requestMappingTemplate, responseMappingTemplate)) {
+      slotEntry.push({
```
Comment (alharris-at) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:166]: I think we can improve the understandability of this snippet here. Having `updateSlotIfExists` return control flow signals seems like one of those things we'll confuse or mix up later on. I'd prefer if we either 1) treat this method as an upsert taking the 4 params we're using in both places, or 2) have control flow helper that determines if slotExists, then a separate push/update flow that follows.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts [hunk 2]
```diff
@@ -162,14 +162,59 @@ export class TransformerResolver implements TransformerResolverProvider {
...
+    }
     this.slotMap.set(slotName, slotEntry);
   };
 
+  updateSlotIfExists = (
+    slotName: string,
+    requestMappingTemplate?: MappingTemplateProvider,
+    responseMappingTemplate?: MappingTemplateProvider,
+  ): boolean => {
+    const slotEntires = this.slotMap.get(slotName)!;
```
Comment (alharris-at) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:180]: typo on Entires

Comment (alharris-at) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:180]: You also don't need the bang here, since we're null checking down below, right?

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts [hunk 3]
```diff
@@ -162,14 +162,59 @@ export class TransformerResolver implements TransformerResolverProvider {
...
+    let slotIndex = 1;
+
+    if (!slotEntires) {
+      return false;
+    }
+
+    for (const slotItem of slotEntires) {
```
Comment (alharris-at) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:187]: Rather than needing a mutable `slotIndex` can we just call `slotEntries.forEach((slotEntry, slotIndex) => { /** your logic below **/ };`

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts [hunk 4]
```diff
@@ -162,14 +162,59 @@ export class TransformerResolver implements TransformerResolverProvider {
...
+      const [slotItemRequestMappingTemplate, slotItemResponseMappingTemplate] = [
+        (slotItem.requestMappingTemplate as any)?.name ?? '',
```
Comment (alharris-at) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:189]: Is there a specific type we can use here instead of `any`?

File: packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap [hunk 5]
```diff
@@ -3531,139 +3531,6 @@ $util.toJson({})
 #set( $filterArgsMap = {} )
 ## [End] Set map initialization for @key **
 ## [Start] Set query expression for @key **
-$util.qr($QueryMap.put('status+createdAt' , 'ByStatus'))
```
Comment (alharris-at) [inline packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap:3534]: I'm not really able to tell from this test on it's own, but to clarify, what's being kept here is the customer overridden logic only, not the one we'd write?

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts [hunk 6]
```diff
@@ -162,14 +162,59 @@ export class TransformerResolver implements TransformerResolverProvider {
...
+        .map(name => name.replace('{slotName}', slotName).replace('{slotIndex}', slotIndex));
+
+      // If both request and response mapping templates are inline, return false
+      if (slotItemRequestMappingTemplate === '' && slotItemResponseMappingTemplate === '') {
+        return false;
+      }
+
+      // If name matches, then it is an overridden resolver
+      if (
+        slotItemRequestMappingTemplate === ((requestMappingTemplate as any)?.name ?? '')
```
Comment (lazpavel) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:201]: nit: can you use $TSAny if there isn't a better alternative?

**Review by lazpavel — APPROVED** [review]
LGTM

File: packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap (hunk 5 above)
Comment (sundersc) [reply packages/amplify-graphql-index-transformer/src/__tests__/__snapshots__/amplify-graphql-index-transformer.test.ts.snap:3534]: That's right. The customer overridden logic will replace the one we create.

File: packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts [hunk 7]
```diff
@@ -47,6 +47,30 @@ describe('user created resolvers', () => {
...
+      await generateModels(projectDir);
+      await amplifyPushUpdate(projectDir);
+
+      const todoJsonPath = join(projectDir, 'amplify', 'backend', 'api', apiName, 'build', 'stacks', 'Todo.json');
+      const todoJson = JSON.parse(fs.readFileSync(todoJsonPath).toString());
+
+      expect(fs.readFileSync(generatedResolverPath).toString()).toEqual(slot);
+      expect(todoJson.Resources.GetTodoResolver.Properties.PipelineConfig.Functions).toHaveLength(3);
+      // The function count should be 3 even after overriding the auth resolver
+      expect(todoJson.Resources.ListTodoResolver.Properties.PipelineConfig.Functions).toHaveLength(3);
```
Comment (phani-srikar) [inline packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts:72]: If it's not too much additional work, can we add a check that the contents of the custom resolver slot are preserved and not overwritten? Thanks

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 6 above)
Comment (phani-srikar) [inline packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts:201]: In the case the user only wants to override the request mapping template but not the response VTL, will this logic work?

**Review by phani-srikar — APPROVED** [review]

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 1 above)
Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: Good catch. Refactored into 3 different functions - findSlot, updateSlot and slotExists.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 2 above)
Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: Updated.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 3 above)
Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: This block requires early termination if match is found. The only way to early exit foreach is using exception, that would look ugly. I have also considered the usage of every() and some(), however `for .. of ...` seems to be the best fit here. I'm open to suggestions if there is a better way.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 4 above)
Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: Unfortunately no. We could alter the class structure we have for storing templates but that would be outside the scope of the change intended here and requires quite a bit of refactoring.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 6 above)
Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: $TSAny is defined on `amplify-cli-core`. Currently, amplify-graphql-transformer-core doesn't have a dependency on `amplify-cli-core`. We can consider adding something similar to $TSAny type within data package once we split the repository.

Comment (sundersc) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: Yes. For example, if response VTL is not overridden, `(responseMappingTemplate as any)?.name` would be `undefined`. In that case, the slot's response VTL is preserved.

```js
slot.responseMappingTemplate = (responseMappingTemplate as any)?.name
        ? responseMappingTemplate
        : slot.responseMappingTemplate;
```

File: packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts (hunk 7 above)
Comment (sundersc) [reply packages/amplify-e2e-tests/src/__tests__/resolvers.test.ts:74]: Updated the e2e test to check the overridden resolver folder and make sure that the file exists and the contents match the custom resolver content.

File: packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts (hunk 3 above)
Comment (alharris-at) [reply packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts]: Ahh, I see. I'm fine w/ this as-is in that case.

**Review by alharris-at — COMMENTED** [review]
Generally LGTM - one n.p. on the `slotExists` method.

**Review by alharris-at — APPROVED** [review]
