### PR TITLE
fix(amplify-category-api): remove stack trace from printout for api

### LINKED ISSUE #9825: Auth with User Pools missing gives stack trace
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

_No response_

### If applicable, what version of Node.js are you using?

_No response_

### Amplify CLI Version

7.6.21

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

Running `gql-compile` on a project without a User Pool gives a full stack trace when it should actually either error gracefully or prompt customers to move into the `add auth` flow. Example:

```bash
clitestproj $amplify-dev api gql-compile

⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules

🛑 @auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.
InvalidDirectiveError: @auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.
    at validateRuleAuthStrategy (/Downloads/amplify-cli/packages/amplify-graphql-auth-transformer/src/utils/validations.ts:77:11)

```

### Expected behavior

Better error message or moving into the `add auth` flow to guide customers.

### Reproduction steps

`init` a project then `add api` flow as normal without adding auth.

### GraphQL schema(s)

<details>

```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
}


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marcvberg**
We're barfing stack traces for many error conditions in the API category with an explicit print,
this is removing that

fix #9825

#### Description of changes
Removes an explicit printout of the stack trace in the API category. An error was showing up in GQL transform in `push` and `gql-compile`, but push is just printing the error without the trace because it has separate logic. This brings the two into alignment

#### Issue #, if available
#9825 

#### Description of how you validated changes
Triggered the error and saw it without stack trace on `gql-compile`

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/src/index.ts [hunk 1]
```diff
@@ -224,9 +224,6 @@ export async function executeAmplifyCommand(context: $TSContext) {
   } catch (error) {
     if (error) {
       printer.error(error.message || error);
-      if (error.stack) {
-        printer.info(error.stack);
```
Comment (jhockett) [inline packages/amplify-category-api/src/index.ts:228]: might be helpful to change this to `printer.debug(error.stack);`

Then we can see the stack traces when `--debug` is passed, but they're be hidden by default

Comment (marcvberg) [reply packages/amplify-category-api/src/index.ts:228]: Fixed

**Review by jhockett — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]
