### PR TITLE
fix: global notification configuration is replaced with private/protected/public

### LINKED ISSUE #9089: amplify headless storage is created with prefixes
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac

### Amplify Categories

storage

### Amplify Commands

add

### Describe the bug

I'm creating storage in amplify headless mode: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-headless-interface/src/interface/storage/add.ts

And storage is created successfull with existing Trigger (tsTrigger) but its have prefixes public/eu-central-1, private, protected on every ObjectCreated or ObjectRemoved event

signal-2021-11-25-125838_001

And as the result trigger event is never fired on Add/Remove files to S3 storage.

### Expected behavior

If I manually remove all 6 triggers and add 2 on ObjectCreated and ObjectRemoved without prefixes it's work as expected.
But how can I skip preffix in amplify storage add headless mode?

### Reproduction steps

`jq -c . < tsHeadlessStorage.addstorage.json | amplify add storage --headless`

content of the `tsHeadlessStorage.addstorage.json`
```
{
  "version": 1,
  "serviceConfiguration": {
    "serviceName": "S3",
    "permissions": {
      "auth": ["CREATE_AND_UPDATE","READ","DELETE"]
    },
    "bucketName": "tsbucket",
    "lambdaTrigger": {
      "mode": "existing",
      "name": "tsTrigger"
    }
  }
}
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sachscode**
#### Description of changes
Problem:
The legacy behavior for S3 Notification triggers was to have a globally configured lambda trigger. However this precludes any new triggers being added to the S3 bucket for any subfolders (prefix clash - https://aws.amazon.com/premiumsupport/knowledge-center/lambda-s3-event-configuration-error/ ) . Hence applications like Predictions (for IdentitySearch) had to 'remove' the global NotificationTrigger from S3 bucket and replace with a per-folder (public, private, protected folder) triggers.
To fix this problem ( of default configuration resulting in overlapping trigger prefixes ) , a code change was made to not include global triggers for S3 buckets. This resulted in legacy apps losing global triggers as the bug #9089 states.

Fix:
Only create per-folder triggers if predictions is enabled, else retain global S3 triggers.

#### Issue #, if available
#9089 , #9128

#### Description of how you validated changes
1. (manual) Add S3 bucket , add Trigger, Deploy to Cloud - validate 2- roles created. Validate uploading file results in Lambda trigger.
2. (manual) Add Predictions with identity flow , Deploy to Cloud - validate 6 - roles created + 2 for rekognitionLambda. Validate both StorageTrigger and RekognitionLambda are triggered when data is uploaded in respective folders.
3. (manual) Headless- Add S3 bucket with triggers , validate roles and repeat test 1 and 2.
4. (manual) Add S3 trigger => test= > Remove S3 trigger => test => Update S3 trigger with existing function => test
E2E & Unit-test Storage
E2E test Predictions
#### Checklist

- [*] PR description included
- [*] `yarn test` passes
- [*] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [*] Relevant documentation is changed or added (and PR referenced)
- [*] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts [hunk 1]
```diff
@@ -288,14 +288,16 @@ export class S3InputState {
...
       for (const triggerParams of this._inputPayload.additionalTriggerFunctions) {
-        for (const configuredTriggerPrefix of triggerParams.triggerPrefix) {
-          if (
-            this.checkPrefixExists(triggerPrefixList, configuredTriggerPrefix.prefix) &&
-            triggerParams.triggerFunction !== triggerFunctionName
-          ) {
-            throw new Error(
-              `Error installing additional Lambda Trigger : trigger ${triggerParams.triggerFunction} already configured on prefix ${triggerParams.triggerPrefix}`,
-            );
+        if (triggerParams.triggerPrefix) {
```
Comment (akshbhu) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/service-walkthroughs/s3-user-input-state.ts:291]: will this also work for empty ```triggerParams.triggerPrefix``` 
or
```suggestion
        if (_.isEmpty(triggerParams.triggerPrefix)) {
```

**Review by akshbhu — APPROVED** [review]
Can we also add an e2e for this usecase or  an asana task to track the e2e task to stop future regression?

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts [hunk 2]
```diff
@@ -333,7 +334,7 @@ export class AmplifyS3ResourceStackTransform {
   }
 
   //Helper: Save DependsOn entries to amplify-meta
-  _saveDependsOnToBackendConfig() {
+  _saveDependsOnToBackendConfig( ) {
```
Comment (attilah) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts:337]: this could be simplified: 

```
const dependsOn = [...s3DependsOnResources || []];
```

and then just 1 call to `updateamplifyMetaAfterResourceUpdate`

**Review by attilah — COMMENTED** [review]
Added a simplification
