### PR TITLE
fix: checkout into existing env with new LL

### LINKED ISSUE #7640: when checkout env: ERROR: No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v14.15.4

### Amplify CLI Version

5.1.0

### What operating system are you using?

Mac

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I have created a new lambda layer on SVIL env and pushed it correctly.

When I try to checkout on TEST with: 
`$amplify env checkout test`

I get the following error:

```
No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json
Error: No CloudFormation template found at /Users/xxxx/xxxxxx/amplify/#current-cloud-backend/function/newfunctionslayer/newfunctionslayer-awscloudformation-template.json
    at Object.readCFNTemplate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/cfnUtilities.ts:9:11)
    at Object.updateConfigOnEnvInit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/index.ts:408:57)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:131:28
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Expected behavior

`amplify env checkout test`
then 
`Initialized your environment successfully.`

### Reproduction steps

```
1) amplify env checkout svil
2) create a new lambda layer
3) amplify push --yes
4)  amplify env checkout test
   ---> ERROR
```

### PR DESCRIPTION
**Pull request by jhockett**
#### Description of changes

Handle non-existing CFN template in `#current-cloud-backend` when running `amplify env checkout` with a LL present that is not in the target environment.

#### Issue #, if available

Fixes #7640

#### Description of how you validated changes
Manual testing, local e2e test passes, yarn test passes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts [hunk 1]
```diff
@@ -405,8 +405,15 @@ export async function updateConfigOnEnvInit(context: $TSContext, resourceName: s
       }
 
       const currentCfnTemplatePath = pathManager.getCurrentCfnTemplatePath(projectPath, categoryName, resourceName);
-      const { cfnTemplate: currentCfnTemplate } = await readCFNTemplate(currentCfnTemplatePath);
-      await writeCFNTemplate(currentCfnTemplate, pathManager.getResourceCfnTemplatePath(projectPath, categoryName, resourceName));
+      try {
+        const { cfnTemplate: currentCfnTemplate } = await readCFNTemplate(currentCfnTemplatePath);
+        await writeCFNTemplate(currentCfnTemplate, pathManager.getResourceCfnTemplatePath(projectPath, categoryName, resourceName));
+      } catch (e) {
+        if (e.message === `No CloudFormation template found at ${currentCfnTemplatePath}`) {
```
Comment (edwardfoyle) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/index.ts:412]: might be better to update `readCFNTemplate` to accept a `throwIfNotExist` option rather than catch and parse the error here. This implementation tightly couples the error message to business logic (ie updating the error message would cause the bug to resurface)

File: packages/amplify-cli-core/src/cfnUtilities.ts [hunk 2]
```diff
@@ -1,12 +1,26 @@
...
 import * as path from 'path';
+import { JSONUtilities } from './jsonUtilities';
+
+export async function readCFNTemplate(filePath: string): Promise<{ templateFormat: CFNTemplateFormat; cfnTemplate: Template }>;
+export async function readCFNTemplate(
+  filePath: string,
+  options: { throwIfNotExist: boolean },
+): Promise<{ templateFormat: CFNTemplateFormat; cfnTemplate: Template } | undefined>;
+
+export async function readCFNTemplate(filePath: string, options: { throwIfNotExist: boolean } = { throwIfNotExist: true }) {
```
Comment (edwardfoyle) [inline packages/amplify-cli-core/src/cfnUtilities.ts:13]: A pattern I like to follow for the options with defaults is:
```suggestion
const defaultReadCFNTemplateOptions = {
  throwIfNotExists: true
}

export async function readCFNTemplate(filePath: string, options: Partial<typeof defaultReadCFNTemplateOptions> = defaultReadCFNTemplateOptions) {
options = {...defaultReadCFNTemplateOptions, ...options};
```

Alternatively, if this is going to be the only option that could potentially make the function return undefined, maybe it would be better to simply define another function:
```
export async function readCFNTemplateSafe(filePath: string): Promise<{ templateFormat: CFNTemplateFormat; cfnTemplate: Template } | undefined>
```

I'll leave it up to you
```

File: packages/amplify-cli-core/src/cfnUtilities.ts [hunk 3]
```diff
@@ -1,12 +1,26 @@
...
+    if (options.throwIfNotExist === false) {
+      return undefined;
+    }
+    throw new Error(errorMessage);
+  }
 
-export async function readCFNTemplate(filePath: string): Promise<{ templateFormat: CFNTemplateFormat; cfnTemplate: Template }> {
-  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile) {
-    throw new Error(`No CloudFormation template found at ${filePath}`);
+  if (!fs.statSync(filePath).isFile) {
```
Comment (edwardfoyle) [inline packages/amplify-cli-core/src/cfnUtilities.ts:22]: if the `throwIfNotExist` flag is set, I think undefined should be returned in this case as well

**Review by attilah — APPROVED** [review]
