### PR TITLE
fix: #5662 - python fallback from python3

### LINKED ISSUE #5662: Can't create a lambda function with python runtime
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Trying to `amplify function add` a lambda with a python run time, and the moment I select the option for python, the following error is thrown:

```console
Error executing python3
You must have python >= 3.8 installed and available on your PATH as "python3". It can be installed from https://www.python.org/downloads
```
I've installed python 3.9 on the Windows 10 system and have updated the PATH to include both `...\Python39` and ...\Python39\Scripts`

The Python installer creates a `python.exe` executable, not `python3.exe`.

I'm using PowerShell, not WSL.

Entering `python3` on the PowerShell does start python correctly.

I've tried making a copy of `python.exe` and naming it `python3.exe`, but to no avail.

I've also tried to create some aliases, like the below, but none seem to help Amplify find python:
```console
Set-Alias python3.exe "D:\Users\Kim\AppData\Local\Programs\Python\Python39\python3.exe"
Set-Alias python3 "D:\Users\Kim\AppData\Local\Programs\Python\Python39\python3.exe"
```
I'm feeling like I'm doing something dumb here, but I don't know what.

**Amplify CLI Version**
4.30.0

**To Reproduce**
1.  run `amplify function add`
2.  select python as the runtime

**Expected behavior**
Should create a python function

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: v12.18.3

**Additional context**
Sorry if this is not a bug, and just me being stupid, but any input that sets me straight would be appreciated.

### PR DESCRIPTION
**Pull request by attilah**
*Issue #, if available:*

#5662 

*Description of changes:*

Fixes #5662 by adding a fallback support for 'python' as binary beside 'python3' which has a higher precedence. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts [hunk 1]
```diff
@@ -43,3 +50,18 @@ export async function execAsStringPromise(command: string, opts?: ExecOptions):
     throw new Error(`Recieved error [${err}] running command [${command}]`);
   }
 }
+
+export const getPythonBinaryName = (): string | undefined => {
+  const executables = ['python3', 'python'];
+  let executablePath: string | null;
+
+  for (let i = 0; i < executables.length; i++) {
```
Comment (edwardfoyle) [inline packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts:58]: nit:
```suggestion
  for (const executable of executables) {
```

File: packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts [hunk 2]
```diff
@@ -43,3 +50,18 @@ export async function execAsStringPromise(command: string, opts?: ExecOptions):
...
+    executablePath = which.sync(executables[i], {
+      nothrow: true,
+    });
+
+    if (executablePath !== null) {
```
Comment (edwardfoyle) [inline packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts:63]: should this also check for undefined?

**Review by edwardfoyle — APPROVED** [review]
couple comments, but looks good

File: packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts (hunk 2 above)
Comment (attilah) [reply packages/amplify-python-function-runtime-provider/src/util/pyUtils.ts:63]: return value is: `string | null`
