### PR TITLE
fix: prevent naming conflicts with new env names

### LINKED ISSUE #3854: InvalidParameterException: Domain cannot contain reserved word: cognito
We were testing some changes related to `cognito` and created a new amplify environment called `newcognito`. 

Upon pushing changes related to auth and facebook federation, we noticed that pushes started failing. I had to dig through the CloudWatch logs to figure it out and noticed this error there:

```
2020-04-03T06:43:17.294Z	aecce830-794e-472e-8ad6-5b52de0ce89d	INFO	{ InvalidParameterException: Domain cannot contain reserved word: cognito
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Domain cannot contain reserved word: cognito',
  code: 'InvalidParameterException',
  time: 2020-04-03T06:43:17.254Z,
  requestId: '6f63c763-ef54-47fb-a527-540f861c2d60',
  statusCode: 400,
  retryable: false,
  retryDelay: 23.270292044054486 }
```

I realize this is a very niche problem but perhaps environment creation could check for reserved words and fail earlier.

### PR DESCRIPTION
**Pull request by jhockett**
Fix for #3854. Also simplifies validation logic and adjusts wording of input validation errors.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.js [hunk 1]
```diff
@@ -95,20 +95,15 @@ async function getEnvName(context) {
...
+    return /^[a-z]{2,10}$/.test(inputEnvName);
   };
 
   if (context.exeInfo.inputParams.amplify && context.exeInfo.inputParams.amplify.envName) {
     if (isEnvNameValid(context.exeInfo.inputParams.amplify.envName)) {
       ({ envName } = context.exeInfo.inputParams.amplify);
       return envName;
     }
-    context.print.error('Environment name should be between 2 and 10 characters (only lowercase alphabets).');
+    context.print.error('Environment name must be between 2 and 10 characters, and lowercase only.');
```
Comment (yuth) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.js:106]: This could be moved a const as the same message is used in both places

Comment (jhockett) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.js]: Fixed
