### PR TITLE
fix(graphql-dynamodb-transformer): always output datasource name

### LINKED ISSUE #982: amplify push fails after removing a model from schema.graphql
**Describe the bug**
Can not remove a model from **schema.graphql** after it was pushed/deployed.

**To Reproduce**
1. Initial **schema.graphql**
    ```
    type User @model {
      id: ID!
      invitations: [Invitation] @connection(name: "UserInvitations")
      last_name: String
      first_name: String
    }

    type Invitation @model {
      id: ID!
      date: String
      sentTo: User @connection(name: "UserInvitations")
      state: String
    }
    ```
2. `amplify push`
3. Update **schema.graphql** and remove *Invitation*
    ```
    type User @model {
      id: ID!
      last_name: String
      first_name: String
    }
    ```
4. `amplify push`
5. Update failed with the following error
    ```
    Embedded stack [ARN of User stack] was not successfully updated. Currently in 
    UPDATE_ROLLBACK_IN_PROGRESS with reason: Export ******************:GetAtt:UserDataSource:Name 
    cannot be deleted as it is in use by [NAME of ConnectionStack stack]
    ```

**Expected behavior**
Be able to remove models from **schema.graphql** and push/publish the changes.

**Additional context**
Tested using the AWS Amplify Console deploy and amplify-cli locally, version 1.1.6.

### LINKED ISSUE #1030: changed @connection directives make `amplify push` unusable
**Describe the bug**
It seems like the `@connection` directives are broken in some fundamental way with respect to `amplify push`.

**To Reproduce**
1. Create a GraphQL api
2. Use some `@connection` directives
3. After a couple pushes involving deleting a directive, and maybe adding it back under a different field or name, `amplify push` will stop working with the `Resource is not in the state stackUpdateComplete` error. 

**Stack Trace**
I can post a stack trace the next time this happens.

**Expected behavior**
When I use Amplify, I have this constant fear that my app will fall into this `push` state where it's completely unrecoverable. **What I expect/would be nice is some way to back out, or rollback, to a point where everything works again.** This has happened now a couple times now and the only way forward, which it now looks like I will have to do yet again, is to nuke the entire API and start over.

### LINKED ISSUE #1141: Update_Rollback_in_Progress.
When trying to update my graphql api using amplify api gql-compile then amplify api push, I get the following error.

```
UPDATE_ROLLBACK_IN_PROGRESS fastlab-20190205133112-apifastlab-VK067GYQ2VUA-Staff-1UQYWAKLJOA5Y AWS::CloudFormation::Stack Wed Mar 27 2019 11:10:42 GMT+1100 (Australian Eastern Daylight Time) Export 4ljyxgicineojb54vspqofs4yu:GetAtt:StaffDataSource:Name cannot be deleted as it is in use by fastlab-20190205133112-apifastlab-VK067GYQ2VUA-ConnectionStack-1D3DCV81JC706
⠹ Updating resources in the cloud. This may take a few minutes...
```

After this point, everything else rolls back, and the push fails.

I'm trying amplify init to see if that gets everything back to normal, as suggested in #2881 but it's not looking promising. Happens to me regularly, and my only solution is to api delete api create.

### PR DESCRIPTION
**Pull request by kstro21**
fix #982 
fix #1030 
fix #1141 

*Description of changes:*
By **always** exporting the **DataSource** name output, it prevents `amplify push` to fails if a **@connection** directive or a model with a **@connection** is removed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by c0dingarchit3ct** [comment]
Hi Guys, I am also blocked on this, anyway we can help move this forward?

**Comment by c0dingarchit3ct** [comment]
I am facing the same problem as well hoping we can get it fixed soon

**Comment by kstro21** [comment]
I've run some test and these changes don't affect projects that were migrated from a previous version of the CLI like what happens with #1047. I.E. if a stack mapping override was given for a DynamoDB table that causes the output to remain in the root stack.

File: packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts [hunk 1]
```diff
@@ -137,9 +138,13 @@ export class DynamoDBModelTransformer extends Transformer {
             this.resources.makeIAMRole(typeName)
         )
         ctx.setResource(
-            ModelResourceIDs.ModelTableDataSourceID(typeName),
+            dataSourceRoleLogicalID,
```
Comment (mikeparisstuff) [inline packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts]: Wouldn't you need to add this to the stack mapping?

Comment (kstro21) [reply packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts]: https://github.com/aws-amplify/amplify-cli/blob/9ffb02bfa36ec4efbb01d6f093c6e9e811827eb8/packages/graphql-dynamodb-transformer/src/DynamoDBModelTransformer.ts#L102
Already exists a stack mapping that covers this case.

**Comment by mikeparisstuff** [comment]
@kstro21 Can you please rebase this and push again to resolve conflicts with your other PR that was just merged?

**Comment by kstro21** [comment]
@mikeparisstuff the conflicts are now resolved. This is ready for another review, please, let me know if I need to do anything else. I'm also waiting for this to be merged.

**Comment by bokuweb** [comment]
I am facing the same problem. I'm also waiting for this to be merged.

**Comment by ajhool** [comment]
My API is currently in a state of conflict, will release 1.6.10 fix existing conflicts like mine, or will it only prevent future conflicts? If the latter, how can existing conflicts be resolved?

**Comment by kstro21** [comment]
Hey, @ajhool, that depends on what issues are you facing right now. Can you describe it?

**Comment by ajhool** [comment]
I had a working graphql API but made a few substantial changes to it and attempted to push via `amplify push api`. The schema passed but the update failed. 

Types of schema changes:

Changed the name of one of the fields that had a connection
```
    oldSchemaPostName: @Post @connection(name: "PostComments")
    ...
   newSchemaPostName: @Post @connection(name: "PostComments")
```

Removed auth from one of the models and added some new fields
```
type OriginalSchemaItem @model
  @versioned
  @auth(rules: [
    { allow: groups, groups: ["Admin"] },
    { allow: groups, groups: ["Public"], operations: [ read ] },
  ])
  ... many fields
...

type UpdatedSchemaItem @model
  @versioned
  {
    someNewField: String
    ... many fields
```

There was a lot of log output but the errors were:

```
    ⠋ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
ResourceNotReady: Resource is not in the state stackUpdateComplete
    at constructor.setError (/Users/aidan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
    at Request.CHECK_ACCEPTORS (/Users/aidan/.config/yarn/global/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
```

```
UPDATE_FAILED               myapi                AWS::CloudFormation::Stack Mon May 20 2019 23:19:44 GMT-0400 (Eastern Daylight Time) Embedded stack arn:aws:cloudformation:us-east-1:redacted:stack/redacted was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [SomeModel]. The following resource(s) failed to update: [TransferRating, Transfer, UserCredit, TransfersTracker, LineItem]. 
```

**Comment by ajhool** [comment]
I have reverted my graphql schema back to the way that it *had* been when it was working... and I am seeing the same error when trying to push.

**Comment by kstro21** [comment]
@ajhool you will need to go to AWS CloudFormation and take a look to the stacks events to see what exactly is going on. What you provided is too broad.

Also, you probably hit the `No resolver found` after removing the **@searchable/@connection** directive from a model. I've seen it reported in other issues, but I think it is more a bug in the CloudFormation service that not restore the resolver in the update rollback process.

If that is the case, you will need to create the **resolvers** manually using the AppSync Console, until then, you won't be able to update your stack.

**Comment by ajhool** [comment]
From CF

(Filter is the name of the model)
```
Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [UpdateFilterResolver, GetFilterResolver, CreateFilterResolver, ListFilterResolver, DeleteFilterResolver].
```

So I need to create those 5 resolvers manually and then Amplify will be able to overwrite them when I try to push again? Or I am now stuck in a state that I'll never be able to escape?

**Comment by kstro21** [comment]
Create them manually, CF will be able to overwrite them when you `amplify push/publish`

**Comment by ajhool** [comment]
So, I'm currently developing the schema in a "dev" amplify env. My end goal is to move it to a "production" amplify env branch. If I try to push this dev code (eg. with different connections in the schema), is that going to bring production down while:

a. the initial push fails and rolls back
b. I manually add the resolvers in
c. The second push succeeds

**Comment by kstro21** [comment]
If you try to update your "production" env using the current version of @aws-amplify/cli and your current code that have changes in the use of the **@connection** directive, yes, you might end up breaking your env.

Or, you can wait until this fix is released in version 1.6.10

**Comment by ajhool** [comment]
I was under the impression that this 1.6.10 fix would not resolve my existing issue?

**Comment by kstro21** [comment]
1.6.10 won't fix the missing **resolvers** if you have any.  It prevents `amplify push/publish` to fails if a **@connection** directive or a model with a **@connection** is removed.

**Comment by ajhool** [comment]
Got it, thanks.

**Comment by ajhool** [comment]
For anybody finding this issue in the future...

1. Go to AppSync console
2. Select your Amplify environment's AppSync schema
3. In the Resolvers pane, in the input that says "Filter types...", type "query"
4. The query results should show a few items that are missing resolvers. Most resolvers will have a DataSource, but some of the items will have "Add Resolver". For me, where my model was called "Filter", the items were: `listFilters`, `getFilter`.
5. For each of those items, I clicked "Add Resolver" -> Chose the relevant data source (in my case, it was "FilterTable" -> Add Resolver.
6. I then repeated step 4-5, but instead of "query" I typed in "mutation" and updated `updateFilter`, `createFilter`, and `deleteFilter`

I believe that this resolved that specific issue, although a separate unrelated issue did arise.
