### PR TITLE
fix: console override build issue

### LINKED ISSUE #9067: Override configuration for Storage/S3 not working on Amplify Console CI/CD builds
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.13.0

### Amplify CLI Version

7.5.1

### What operating system are you using?

AWS Builds

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

I have an override.ts file for storage on my Amplify. Using my local computer, with `amplify push`, it is updated to cloud without any problem.

But for AWS Amplify builds (it is using `amplifyPush --simple`), when machine automatically create the build, all included on override.ts is reverted to base status. I need to make `amplify push` from my local computer to apply again the overrides. It is working but when someone upload to git and then AWS Amplify generate the build, agian is reverted.

### Expected behavior

When building bakend on AWS with `amplifyPush --simple` command, take care of override.ts modifications

### Reproduction steps

1. Create override storage
2. Add some CDK changes
3. Apply it from local computer (ok)
4. Upload something to git and then AWS Amplify starts building
5. When building backed, all on override.ts is reverted to base and that build is not considering override.ts configurations

### GraphQL schema(s)

_No response_

### Log output

_No response_

### Additional information

applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush --simple

### PR DESCRIPTION
**Pull request by akshbhu**
#### Description of changes
- copy package.json  to current cloud backend
- changes appoverrides() fn to throw error when build is failed
- generates package.json in pull if not present

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts [hunk 1]
```diff
@@ -50,16 +52,19 @@ export async function buildOverrideDir(cwd: string, destDirPath: string): Promis
 
     // making sure build folder exists for resource
     fs.ensureDirSync(tsConfigDir);
+    // add overrde.ts and tsconfig<project> to build folder of the resource / rootstack
+    const tsConfigDestFilePath = path.join(tsConfigDir, 'tsconfig.resource.json');
+    const tsConfigFileName = path.join(__dirname, '..', '..', 'resources', 'overrides-resource', 'tsconfig.resource.json');
+    fs.writeFileSync(tsConfigDestFilePath, fs.readFileSync(tsConfigFileName));
```
Comment (jhockett) [inline packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts:58]:
```suggestion
    const tsConfigFilePath = path.join(__dirname, '..', '..', 'resources', 'overrides-resource', 'tsconfig.resource.json');
    fs.writeFileSync(tsConfigDestFilePath, fs.readFileSync(tsConfigFilePath));
```

**Review by jhockett — APPROVED** [review]

**Review by jhockett — APPROVED** [review]

File: packages/amplify-category-api/src/index.ts [hunk 2]
```diff
@@ -308,12 +308,6 @@ export async function transformCategoryStack(context: $TSContext, resource: $TSO
     }
   } else if (resource.service === AmplifySupportedService.APIGW) {
     if (canResourceBeTransformed(resource.resourceName)) {
-      const backendDir = pathManager.getBackendDirPath();
-      const overrideDir = pathManager.getResourceDirectoryPath(undefined, AmplifyCategories.API, resource.resourceName);
-      await buildOverrideDir(backendDir, overrideDir).catch(error => {
```
Comment (kaustavghosh06) [inline packages/amplify-category-api/src/index.ts:313]: Why remove this?

File: packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts [hunk 3]
```diff
@@ -168,8 +168,8 @@ export class AmplifyS3ResourceStackTransform {
     const overrideJSFilePath = path.resolve(path.join(resourceDirPath, 'build', 'override.js'));
 
     const isBuild = await buildOverrideDir(backendDir, resourceDirPath).catch(error => {
-      printer.debug(`Skipping build as ${error.message}`);
-      return false;
+      printer.error(`Skipping build due to ${error.message}`);
```
Comment (kaustavghosh06) [inline packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts:171]: Should it be skipping build - or "Build error".

File: packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts [hunk 4]
```diff
@@ -50,6 +50,10 @@ function moveBackendResourcesToCurrentCloudBackend(resources: $TSObject[]) {
   const amplifyCloudMetaFilePath = pathManager.getCurrentAmplifyMetaFilePath();
   const backendConfigFilePath = pathManager.getBackendConfigFilePath();
   const backendConfigCloudFilePath = pathManager.getCurrentBackendConfigFilePath();
+  const overridePackageJsonBackendFilePath = path.join(pathManager.getBackendDirPath(), 'package.json');
+  const overrideTsConfigJsonBackendFilePath = path.join(pathManager.getBackendDirPath(), 'tsconfig.json');
+  const overridePackageJsonCurrentCloudBackendFilePath = path.join(pathManager.getCurrentCloudBackendDirPath(), 'package.json');
```
Comment (kaustavghosh06) [inline packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts:55]: Do we need tsconfig.json copying anymore?

File: packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts [hunk 5]
```diff
@@ -50,16 +60,19 @@ export async function buildOverrideDir(cwd: string, destDirPath: string): Promis
 
     // making sure build folder exists for resource
     fs.ensureDirSync(tsConfigDir);
+    // add overrde.ts and tsconfig<project> to build folder of the resource / rootstack
+    const tsConfigDestFilePath = path.join(tsConfigDir, 'tsconfig.resource.json');
+    const tsConfigFilePath = path.join(__dirname, '..', '..', 'resources', 'overrides-resource', 'tsconfig.resource.json');
```
Comment (kaustavghosh06) [inline packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts:65]: tsConfigSampleFilePath?

File: packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts [hunk 6]
```diff
@@ -90,7 +103,7 @@ export const generateAmplifyOverrideProjectBuildFiles = (backendDir: string, src
   }
```
Comment (kaustavghosh06) [inline packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts:103]: Can we remove addition of tsconfig at the prooject level?

File: packages/amplify-category-api/src/index.ts (hunk 2 above)
Comment (akshbhu) [reply packages/amplify-category-api/src/index.ts:313]: we are doing buildOverride inside transform , same as other categories except for graphql

File: packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts (hunk 4 above)
Comment (akshbhu) [reply packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts:55]: I dont think we nneed to copy it as per our usecase now , but we can keep it handy to copy over tsconfig values from user to tsconfig-resource, when doing buildOverrideDir

File: packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts (hunk 6 above)
Comment (akshbhu) [reply packages/amplify-cli-core/src/overrides-manager/override-skeleton-generator.ts:103]: Do you mean to remove tsConfig from everwhere ?

**Review by kaustavghosh06 — APPROVED** [review]
