### PR TITLE
fix(amplify-cli): remove redundant prompt #6535

### LINKED ISSUE #6535: "amplify env add" asks "Do you want to use an existing environment?"
When I enter `amplify env add` or `amplify env add <env name>` it first asks "Do you want to use an existing environment?" If I say yes, and select an environment, it will just use that environment and not create a new environment. I personally believe this is counter-intuitive. It should immediately just ask you for the name of the new environment. If I wanted to use an existing environment, I would run `amplify env checkout`.

Also, if you provide an environment name to `amplify env add` (e.g. `amplify env add stg`) it should be able to immediately add that environment and skip the environment name prompt.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Simply create an Amplify project and enter `amplify env add` to add a new environment.

**Expected behavior**
It asks "Enter a name for the environment" and rest of the steps proceeds as expected for adding new environment. (selecting AWS profile, etc.)

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version: v12.18.4

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
#### Description of changes

Improves the `amplify env add` workflow.
Changes made:

1. Skip the `Do you want to use an existing environment?` question when `amplify env add` is executed.

Screenshot from 2021-04-15 12-45-59

2. On passing environment name in `amplify env add <envName>`, the new environment is directly added.

Screenshot from 2021-04-15 12-47-02

#### Issue #, if available

Fixes #6535 

#### Description of how you validated changes
`yarn test`

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts [hunk 1]
```diff
@@ -297,3 +299,29 @@ function getDefaultEditor() {
...
+/**
+ *Checks if `amplify env add` has been executed, and extract environment name if exists
+ * @param {$TSContext} context The Amplify context object
+ * @returns `{exec: boolean, envName?: string | null}`
+ *
+ * `exec` denotes if `amplify env add` has been executed
+ *
+ * `envName` extracts environment name if provided
+ */
+function addNewEnv(context): { exec: boolean; envName?: string | null } {
```
Comment (cjihrig) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:312]: Can you please give this a different name. It currently seems like this function would add a new environment.

Comment (cjihrig) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:312]: It seems like this function can just return a boolean (the value of `exec`), and the caller can use `context.parameters.first` to check for the environment name.

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts [hunk 2]
```diff
@@ -242,7 +242,7 @@ async function getEnvName(context) {
   } else {
     const allEnvs = context.amplify.getAllEnvs();
 
-    if (allEnvs.length > 0) {
+    if (allEnvs.length > 0 && addNewEnv(context).exec === false) {
```
Comment (cjihrig) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:245]: Instead of calling `addNewEnv()` repeatedly, please store the result in a variable.

**Comment by ammarkarachi** [comment]
@cjihrig

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts [hunk 3]
```diff
@@ -297,3 +300,16 @@ function getDefaultEditor() {
 
   return localEnvInfo.defaultEditor;
 }
+
+/**
+ *Checks if `amplify env add` has been executed
```
Comment (cjihrig) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:305]:
```suggestion
 * Checks if `amplify env add` has been executed
```

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts [hunk 4]
```diff
@@ -297,3 +300,16 @@ function getDefaultEditor() {
...
+ * @param {$TSContext} context The Amplify context object
+ * @returns `boolean`
+ */
+function checkEnvAddExec(context): boolean {
+  if (context.parameters.command === 'env' && context.parameters.array[0] === 'add') {
+    return true;
+  } else {
+    return false;
+  }
```
Comment (cjihrig) [inline packages/amplify-cli/src/init-steps/s0-analyzeProject.ts:314]:
```suggestion
  return context.parameters.command === 'env' && context.parameters.array[0] === 'add'
```

**Review by edwardfoyle — CHANGES_REQUESTED** [review]
The E2E test flows here (and maybe some other places too) need to be updated with this change
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-tests/src/environment/env.ts

**Comment by gitaalekhyapaul** [comment]
> The E2E test flows here (and maybe some other places too) need to be updated with this change
> https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-e2e-tests/src/environment/env.ts

@edwardfoyle I have been trying to execute the `env.test.ts`, but the test is failing with the following error code: `1`. As per the code, it is not a timeout error, since the timeout error code is `EXIT_CODE_TIMEOUT = 2` and not even any generic error since the error code for generic error is `EXIT_CODE_GENERIC_ERROR = 3`. I am not sure how to resolve this.

Is there any specific situations where the child procccess will return `1`?

Screenshot from 2021-05-11 13-36-50

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts (hunk 4 above)
Comment (gitaalekhyapaul) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.ts]: Resolved!

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts (hunk 3 above)
Comment (gitaalekhyapaul) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.ts]: Resolved!

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts (hunk 2 above)
Comment (gitaalekhyapaul) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.ts]: Resolved!

File: packages/amplify-cli/src/init-steps/s0-analyzeProject.ts (hunk 1 above)
Comment (gitaalekhyapaul) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.ts]: Resolved!

Comment (gitaalekhyapaul) [reply packages/amplify-cli/src/init-steps/s0-analyzeProject.ts]: Resolved!

**Review by edwardfoyle — APPROVED** [review]
