### PR TITLE
fix(graphql-model-transformer): use modelobject key for mutation resolver creation

### LINKED ISSUE #7414: Custom Key Fails to Adhere to Unique Constraints
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.97 GB / 15.62 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @fortawesome/fontawesome-svg-core: ^1.2.35 => 1.2.35
    @fortawesome/free-regular-svg-icons: ^5.15.3 => 5.15.3
    @fortawesome/free-solid-svg-icons: ^5.15.3 => 5.15.3
    @fortawesome/vue-fontawesome: ^3.0.0-3 => 3.0.0-3
    @types/uuid: ^8.3.0 => 8.3.0
    @types/validator: ^13.1.3 => 13.1.3
    @typescript-eslint/eslint-plugin: ^4.18.0 => 4.22.1
    @typescript-eslint/parser: ^4.18.0 => 4.22.1
    @vee-validate/rules: ^4.1.20 => 4.1.20
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.13
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13
    @vue/cli-service: ~4.5.0 => 4.5.13
    @vue/compiler-sfc: ^3.0.0 => 3.0.11
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    animate.css: ^4.1.1 => 4.1.1
    aws-amplify: ^3.4.0 => 3.4.0
    axios: ^0.21.1 => 0.21.1
    blob-util: ^2.0.2 => 2.0.2
    core-js: ^3.6.5 => 3.12.1 (2.6.12)
    dayjs: ^1.10.4 => 1.10.4
    direct-vuex: ^0.12.1 => 0.12.1
    eslint: ^6.7.2 => 6.8.0
    eslint-plugin-import: ^2.20.2 => 2.22.1
    eslint-plugin-node: ^11.1.0 => 11.1.0
    eslint-plugin-promise: ^4.2.1 => 4.3.1
    eslint-plugin-standard: ^4.0.0 => 4.1.0
    eslint-plugin-vue: ^7.0.0 => 7.9.0
    memo-parser:  0.2.1
    node-sass: ^4.12.0 => 4.14.1
    register-service-worker: ^1.7.1 => 1.7.2
    sass-loader: ^8.0.2 => 8.0.2
    svg-path-bounds: ^1.0.2 => 1.0.2
    typescript: ~4.1.5 => 4.1.5
    uuid: ^3.4.0 => 3.4.0 (3.3.2)
    validator: ^13.6.0 => 13.6.0
    vue: ^3.0.0 => 3.0.11
    vue-awesome-example:  2.0.0
    vue-router: ^4.0.0-0 => 4.0.6
    vue3-mq: ^2.3.1 => 2.3.1
    vuex: ^4.0.0-0 => 4.0.0
    vuex-persistedstate: * => 4.0.0-beta.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.2
    @ionic/cli: 6.14.1
    @vue/cli-init: 4.5.13
    @vue/cli: 4.5.13
    coffeescript: 2.5.1
    cordova: 10.0.0
    dotenv-cli: 4.0.0
    eslint: 7.26.0
    eslit: 6.0.0
    exp: 57.2.1
    expo-cli: 4.4.7
    graphql-schema-utilities: 1.1.3
    gulp: 4.0.2
    ionic: 5.4.16
    live-server: 1.2.1
    mocha: 8.4.0
    node-gyp: 8.0.0
    node-ts: 5.1.1
    npm: 7.12.0
    production: 0.0.2
    react-native-cli: 2.0.1
    serverless-create-global-dynamodb-table: 3.1.1
    serverless-dynamodb-autoscaling: 0.6.2
    serverless: 2.43.0
    to-ico-cli: 1.0.0
    ts-node: 9.1.1
    typescript: 4.2.3
    vue-next: 0.0.1
    webpack-cli: 4.7.0
    webpack: 5.36.2
    windows-build-tools: 5.2.2
    wscat: 4.0.1
```

</details>

### Describe the bug

I defined a model like this.
```
type XXX
  @model
  @auth(
    rules:[
      { allow: owner, operations: [create, update, delete] }
    ]
  )
{
  id: ID!
  owner: String
}
```
It works fine. At first Owner A create a record on a XXX table. If owner B create a record with same id, it cause error 400.

But, I defined a model with custom primary key, it doesn't work.
```
type XXX
  @model
  @auth(
    rules:[
      { allow: owner, operations: [create, update, delete] }
    ]
  )
  @key(fields: ["customId"])
{
  customId: ID!
  owner: String
}
```

Even though owner B create a record with same customId created by ownerA, it will be no error. In addition, after create operation by owner B, owner value is still owner A, but _version changed to 2. 

### Expected behavior

Even if model have a custom primary keys, It should be prevented creating a record with same id created by other owner.

### Reproduction steps

1. define some model with custom primary key
2. create a record by owner A on the model.
3. create record with same id created by owner A. It will be OK result.

### PR DESCRIPTION
**Pull request by SwaySway**
#### Description of changes

- create update and delete resolvers should check for model object key
- update unit tests to the new resolver change
- update mock and e2e packages to test change

#### Issue #, if available

- fix #7414 

#### Description of how you validated changes

- ran unit, mock, and e2e tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/graphql-dynamodb-transformer/src/resources.ts [hunk 1]
```diff
@@ -864,4 +797,44 @@ export class ResourceFactory {
...
     });
   }
+
+  /**
+   * Adds the default Condition Expression uses ModelObjectkey if @key is used
+   * @returns
+   */
+
+  private addDefaultConditionExpression = (operation: string): Expression => {
+    let attributeCheck = operation === 'create' ? 'attribute_not_exists' : 'attribute_exists';
```
Comment (edwardfoyle) [inline packages/graphql-dynamodb-transformer/src/resources.ts:807]: nit
```suggestion
    const attributeCheck = operation === 'create' ? 'attribute_not_exists' : 'attribute_exists';
```

File: packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts [hunk 2]
```diff
@@ -381,14 +381,31 @@ test('Test create/update mutation validation with three part secondary key.', as
...
 
 test('Test Customer Create with list member and secondary key', async () => {
-  const createCustomer1 = await createCustomer('customer1@email.com', ['thing1', 'thing2'], 'customerusr1');
+  await createCustomer('customer1@email.com', ['thing1', 'thing2'], 'customerusr1');
   const getCustomer1 = await getCustomer('customer1@email.com');
   expect(getCustomer1.data.getCustomer.addresslist).toEqual(['thing1', 'thing2']);
-  // const items = await onCreateCustomer
+});
+
+test('Test can overwrite customer record with custom primary key', async () => {
```
Comment (edwardfoyle) [inline packages/graphql-transformers-e2e-tests/src/__tests__/KeyTransformer.e2e.test.ts:389]:
```suggestion
test('Test cannot overwrite customer record with custom primary key', async () => {
```

File: packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts [hunk 3]
```diff
@@ -351,14 +351,25 @@ test('Test update mutation validation with three part secondary key.', async ()
...
 
 test('Test Customer Create with list member and secondary key', async () => {
-  const createCustomer1 = await createCustomer('customer1@email.com', ['thing1', 'thing2'], 'customerusr1');
+  await createCustomer('customer1@email.com', ['thing1', 'thing2'], 'customerusr1');
   const getCustomer1 = await getCustomer('customer1@email.com');
   expect(getCustomer1.data.getCustomer.addresslist).toEqual(['thing1', 'thing2']);
-  // const items = await onCreateCustomer
+});
+
+test('Test can overwrite customer record with custom primary key', async () => {
```
Comment (edwardfoyle) [inline packages/amplify-util-mock/src/__e2e__/key-transformer.e2e.test.ts:359]:
```suggestion
test('Test cannot overwrite customer record with custom primary key', async () => {
```

**Review by edwardfoyle — APPROVED** [review]
