### PR TITLE
fix: enable only-userpool flow without idp and addition of groups without roles tied to idp

### LINKED ISSUE #2096: UPDATE_FAILED UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout 'IdentityPoolId' not found in stack
**Describe the bug**
I am using 

**amplify --version**
**1.12.0**

At any create or update on any configuration, which is not the default configuration, the amplify update fail with:

UPDATE_FAILED               UpdateRolesWithIDPFunctionOutputs      Custom::LambdaCallout      Tue Aug 20 2019 17:40:30 GMT+0200 (GMT+02:00) Output 'IdentityPoolId' not found in stack '...'

or 

CREATE_FAILED               UpdateRolesWithIDPFunctionOutputs      Custom::LambdaCallout      Tue Aug 20 2019 16:33:25 GMT+0200 (GMT+02:00) Output 'IdentityPoolId' not found in stack '...'

Although I chose

? Do you want to configure Lambda Triggers for Cognito? **No**

This behavior appears after update of amplify cli on version 1.12.0 comping from 1.11.0

**To Reproduce**
1. Go to console in project directory
2. amplify init
3. amplify add auth
`
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up & Sign-In only (Best used with a cloud API only)
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 1
 Do you want to specify the user attributes this app can read and write? Yes
 Specify read attributes: (Press <space> to select, <a> to toggle all, <i> to invert selection)Address, Birthdate, Email, Family Name, Middle Name, Gender, Locale, Given Name, Name, Nickname, Phone Number, Preferred Username, Picture, Prof
ile, Updated At, Website, Zone Info, Email Verified?, Phone Number Verified?
 Specify write attributes: (Press <space> to select, <a> to toggle all, <i> to invert selection)Address, Birthdate, Family Name, Middle Name, Gender, Locale, Given Name, Name, Nickname, Phone Number, Preferred Username, Picture, Profile, U
pdated At, Website, Zone Info
 Do you want to enable any of the following capabilities? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to use an OAuth flow? Yes
 What domain name prefix you want us to create for you? ********
 Which redirect signin URIs do you want to edit? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to add redirect signin URIs? Yes
 Enter your new redirect signin URI: http://localhost:5000/
? Do you want to add another redirect signin URI No
 Which redirect signout URIs do you want to edit? (Press <space> to select, <a> to toggle all, <i> to invert selection)
 Do you want to add redirect signout URIs? No
 Select the OAuth flows enabled for this project. Authorization code grant
 Select the OAuth scopes enabled for this project. (Press <space> to select, <a> to toggle all, <i> to invert selection)Phone, Email, OpenID, Profile, aws.cognito.signin.user.admin
 Select the identity providers you want to configure for your user pool: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito (Press <space> to select, <a> to toggle all, <i> to invert selection)
Successfully updated resource gbe01reactclient locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
`
4. amplify push
5. Cloudformation script fail with:
CREATE_FAILED               UpdateRolesWithIDPFunctionOutputs      Custom::LambdaCallout      Tue Aug 20 2019 16:33:25 GMT+0200 (GMT+02:00) Output 'IdentityPoolId' not found in stack 'arn:aws:cloudformation:eu-central-1:****'

Cloudformation template rollback is executed afterwards.

Interesting is, if I just use defaults and publish, everything works fine. If I start to add my callback URL's or the read/write attributes I always fail in this step.

This behavior appears after update of amplify cli on version 1.12.0 comping from 1.11.0

**Expected behavior**
Create/update succeed with

√ All resources are updated in the cloud

**Desktop (please complete the following information):**
 - OS: Win10 (although the error happens at AWS CloudFormation)

### PR DESCRIPTION
**Pull request by kaustavghosh06**
*Issue #, if available:*
fix #2096 

*Description of changes:*

1) Fixing addition of onlyuserpool
2) Provide ability to add user-pool groups without identity pools and without need of IAM role when only cognito user pools are enabled

E2E tests included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-auth/commands/auth/update.js [hunk 1]
```diff
@@ -70,6 +71,30 @@ module.exports = {
         }
         amplify.updateamplifyMetaAfterResourceUpdate(category, resourceName, 'customAuth', customAuthConfigured);
 
+        // Update Identity Pool dependency attributes on userpool groups
+        const allResources = context.amplify.getProjectMeta();
+        if(allResources.auth && allResources.auth.userPoolGroups) {
+          let attributes;
```
Comment (attilah) [inline packages/amplify-category-auth/commands/auth/update.js]: Perhaps it would be more optimal to see what is different in behavior:

```
const attributes = ['UserPoolId', 'AppClientIDWeb', 'AppClientID'];
 
if(authParameters.identityPoolName) {
    attributes.push ('IdentityPoolId');
}
```

File: packages/amplify-category-auth/index.js [hunk 2]
```diff
@@ -120,28 +120,55 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
   };
 
   try {
-    authProps = removeDeprecatedProps(authProps);
+    authProps = await removeDeprecatedProps(authProps);
     await copyCfnTemplate(context, category, authProps, cfnFilename);
-    saveResourceParameters(context, provider, category, authProps.resourceName, authProps, ENV_SPECIFIC_PARAMS);
+    await saveResourceParameters(context, provider, category, authProps.resourceName, authProps, ENV_SPECIFIC_PARAMS);
+    const resourceDirPath = path.join(amplify.pathManager.getBackendDirPath(), '/auth/', authProps.resourceName, 'parameters.json');
```
Comment (attilah) [inline packages/amplify-category-auth/index.js]: Remove the slashes around `auth` as we're in a `path.join` and could break on Windows.

File: packages/amplify-category-auth/index.js [hunk 3]
```diff
@@ -120,28 +120,55 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
...
       if (authParameters.dependsOn) {
         options.dependsOn = authParameters.dependsOn;
       }
       await amplify.updateamplifyMetaAfterResourceAdd(category, authProps.resourceName, options);
     }
+
+    // Update Identity Pool dependency attributes on userpool groups
+    const allResources = context.amplify.getProjectMeta();
+    if(allResources.auth && allResources.auth.userPoolGroups) {
+      let attributes;
```
Comment (attilah) [inline packages/amplify-category-auth/index.js]: Same as above, can't we share this logic as well and just have it once in the codebase?

File: packages/amplify-e2e-tests/src/categories/auth.ts [hunk 4]
```diff
@@ -404,6 +404,185 @@ export function addAuthWithDefaultSocial(cwd: string, settings: any) {
...
+      .send('\r')
+      .wait('Do you want to configure Lambda Triggers for Cognito')
+      .send('y')
+      .send('\r')
+      .wait('Which triggers do you want to enable for Cognito')
+      .send('a')
+      .send(' ')
+      .send('\r')
+      .wait('What functionality do you want to use for Create Auth Challenge')
+      .send('jjj')
```
Comment (yuth) [inline packages/amplify-e2e-tests/src/categories/auth.ts]: We have constants for these now. Please use them

File: packages/amplify-e2e-tests/src/categories/auth.ts [hunk 5]
```diff
@@ -404,6 +404,185 @@ export function addAuthWithDefaultSocial(cwd: string, settings: any) {
...
+      .send('\r')
+      .wait('Select the social providers you want to configure for your user pool')
+      .send('a')
+      .send('\r')
+      .wait('Enter your Facebook App ID for your OAuth flow')
+      .send('fbOAUTHid')
+      .send('\r')
+      .wait('Enter your Facebook App Secret for your OAuth flow')
+      .send('fbOAUTHsecret')
+      .send('\r')
```
Comment (yuth) [inline packages/amplify-e2e-tests/src/categories/auth.ts]: we have an `sendCarriageReturn` function. Lets use that

File: packages/amplify-category-auth/commands/auth/update.js (hunk 1 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/commands/auth/update.js]: Done. I chose the previous style for better readability, but I guess your suggestion is more maintainable.

File: packages/amplify-category-auth/index.js (hunk 2 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/index.js]: Done. This was a copy-paste issue. Changed it in all other places as well - with this reference.

File: packages/amplify-category-auth/index.js (hunk 3 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/index.js]: Yeah, as I was diving through the code there's a refactor which I'm planning to basically consolidate the enable/update/externalAuth functions since it has a bunch of repeated code. It'll be a part of another PR.

File: packages/amplify-e2e-tests/src/categories/auth.ts (hunk 5 above)
Comment (kaustavghosh06) [reply packages/amplify-e2e-tests/src/categories/auth.ts]: Yup. Done - wasn't aware of the constants.

File: packages/amplify-e2e-tests/src/categories/auth.ts (hunk 4 above)
Comment (kaustavghosh06) [reply packages/amplify-e2e-tests/src/categories/auth.ts]: Done!

File: packages/amplify-category-auth/index.js [hunk 6]
```diff
@@ -120,28 +120,49 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
...
+    }
+
     const action = authExists ? 'updated' : 'added';
     context.print.success(`Successfully ${action} auth resource locally.`);
 
     return requirements.resourceName;
   } catch (e) {
-    return new Error('Error updating Cognito resource');
+    throw new Error('Error updating Cognito resource');
+    context.print.error(e.stack);
```
Comment (yuth) [inline packages/amplify-category-auth/index.js]: Code after throw never gets executed

File: packages/amplify-category-auth/index.js [hunk 7]
```diff
@@ -120,28 +120,49 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
...
+      }
+      const userPoolGroupDependsOn = [
+        {
+          category: 'auth',
+          resourceName: authProps.resourceName,
+          attributes,
+        },
+      ];
+
+      amplify.updateamplifyMetaAfterResourceUpdate('auth', 'userPoolGroups', 'dependsOn', userPoolGroupDependsOn);
```
Comment (yuth) [inline packages/amplify-category-auth/index.js]: This code almost identical to that of what we have in https://github.com/aws-amplify/amplify-cli/blob/144d69785a8ff8a2a83fefe47b6f195861f51245/packages/amplify-category-auth/commands/auth/update.js#L74-L91. Can we just move it to a method instead of having repeated code

File: packages/amplify-category-auth/index.js [hunk 8]
```diff
@@ -120,28 +120,49 @@ async function externalAuthEnable(context, externalCategory, resourceName, requi
...
       if (authParameters.dependsOn) {
         options.dependsOn = authParameters.dependsOn;
       }
       await amplify.updateamplifyMetaAfterResourceAdd(category, authProps.resourceName, options);
     }
+
+    // Update Identity Pool dependency attributes on userpool groups
+    const allResources = context.amplify.getProjectMeta();
+    if (allResources.auth && allResources.auth.userPoolGroups) {
+      let attributesm = ['UserPoolId', 'AppClientIDWeb', 'AppClientID'];
```
Comment (yuth) [inline packages/amplify-category-auth/index.js]: `attributesm` -> `attributes`

File: packages/amplify-category-auth/index.js (hunk 6 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/index.js]: Will remove this error printing - was using it for debugging

File: packages/amplify-category-auth/index.js (hunk 7 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/index.js]: Same comment on above:
attilah 6 days ago Member
Same as above, can't we share this logic as well and just have it once in the codebase?

 @kaustavghosh06
kaustavghosh06 4 days ago Author Member
Yeah, as I was diving through the code there's a refactor which I'm planning to basically consolidate the enable/update/externalAuth functions since it has a bunch of repeated code. It'll be a part of another PR.

File: packages/amplify-category-auth/index.js (hunk 8 above)
Comment (kaustavghosh06) [reply packages/amplify-category-auth/index.js]: Changing it

File: packages/amplify-category-auth/index.js (hunk 7 above)
Comment (yuth) [reply packages/amplify-category-auth/index.js]: Dont you think it would easier to move it a separate function now as the duplicate code is introduced now. We could always do refactoring, but moving it out now would make one less thing to worry about. I will leave it up to you to decide how you want to handle this
