### PR TITLE
fix: multi-env container hosting (#7009)

### LINKED ISSUE #7009: Multi Env with Amplify Containers
### Before opening, please confirm:

I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

15.0.1

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

hosting

### Amplify Commands

env, publish

### Describe the bug

I would like to use the container based deployment feature of Amplify with multiple environments (so I can hopefully use it on a CI/CD pipeline like the console). When I deploy my production environment it works but then when I switch to staging and run `amplify publish`, I get a `CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists` even when I manually edit the `container-template.json` and `backend-config.json` file to move from the `www` to the `staging`

### Expected behavior

I expect that I should be able to create multiple environments and deploy them independently using Amplify.

### Reproduction steps

1. Deploy environment using this guide: https://dev.to/dabit3/serverless-containers-with-next-js-aws-fargate-and-aws-amplify-17fe
2. `amplify env add staging`
3. `amplify add hosting`
4. Provide my domain: `staging.mydomain.com`
5. Get an error `ElasticContainer is present in amplify-meta.json` 
6. Decide to change the `container-template.json` and `backend-config.json` files manually from www to staging.
7. Run `amplify publish` 
8. It eventually fails with the error above.

### GraphQL schema(s)

_No response_

### Log output

<details>

```
# Put your logs below this line

2021-04-01T15:57:21.972Z|info : amplify help core  
2021-04-01T15:57:32.645Z|info : amplify env core  
2021-04-01T15:57:49.705Z|info : amplify help core staging 
2021-04-01T15:58:04.758Z|info : amplify env core add staging 
2021-04-01T15:59:00.602Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T15:59:00.604Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T15:59:00.604Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T15:59:00.611Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T15:59:00.611Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T15:59:00.612Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T15:59:00.623Z|info : amplify-provider-awscloudformation.amplify-service-permission-check.checkAmplifyServiceIAMPermission.amplifyClient.listApps([])
2021-04-01T15:59:00.872Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.listApps([{"maxResults":25}])
2021-04-01T15:59:01.083Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]nz5t3i","environmentName":"[***]ing"}])
2021-04-01T15:59:01.229Z|error : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]nz5t3i","environmentName":"[***]ing"}])
NotFoundException: BackendEnvironment staging does not exist.
2021-04-01T15:59:01.230Z|info : amplify-provider-awscloudformation.amplify-service-manager.init.amplifyClient.getBackendEnvironment([{"appId":"[***]nz5t3i","environmentName":"[***]ing","stackName":"[***]ify-[***]ompare-[***]ing-[***]900","deploymentArtifacts":"amplify-project-staging-105900-deployment"}])
2021-04-01T15:59:01.363Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T15:59:01.364Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T15:59:01.364Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T16:00:02.459Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T16:00:02.460Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T16:00:02.460Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T16:00:02.471Z|info : amplify-provider-awscloudformation.attach-backend.storeCurrentCloudBackend.s3.uploadFile([{"Key":"[***]rent-[***]ud-[***]d.zip"}])
2021-04-01T16:00:02.475Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T16:00:02.748Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]ify-[***]json"}])
2021-04-01T16:00:02.749Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T16:00:02.937Z|info : amplify-provider-awscloudformation.attach-backend.uploadFile.s3.uploadFile([{"Key":"[***]end-[***].json"}])
2021-04-01T16:00:02.938Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]end-[***].json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T16:00:59.342Z|info : amplify add api  
2021-04-01T16:01:57.826Z|info : amplify configure core project 
2021-04-01T16:02:13.616Z|info : amplify add api  
2021-04-01T16:02:23.660Z|info : amplify add hosting  
2021-04-01T16:04:52.588Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T16:04:52.591Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T16:04:52.591Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T16:05:11.702Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T16:05:11.703Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T16:05:11.703Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:27:16.410Z|info : amplify publish core  
2021-04-01T19:27:27.742Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:27:27.744Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:27:27.745Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:27:27.756Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-04-01T19:27:27.758Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:27:27.969Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:27:27.969Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:27:27.970Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:27:27.977Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]ompare-[***]ing-[***]900"}])
2021-04-01T19:27:28.180Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:28:30.620Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:28:30.622Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:28:30.622Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:28:31.860Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]emplate.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:28:32.037Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]tom-[***]urce-[***]line-[***]r.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:28:32.298Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]eline-[***]ion-[***]spec-[***]ator-[***].zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:28:35.982Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:28:35.982Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:28:35.982Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:28:36.621Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]ing/[***]iner-[***]e.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:28:37.160Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:28:37.161Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:28:37.161Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:28:37.162Z|info : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
2021-04-01T19:28:37.166Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ted-[***]mation-[***].yml","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:37:16.155Z|error : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
ResourceNotReady: Resource is not in the state stackUpdateComplete
2021-04-01T19:38:06.391Z|info : amplify publish core  
2021-04-01T19:38:17.954Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:38:17.955Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:38:17.956Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:38:17.967Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-04-01T19:38:17.970Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:38:18.189Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:38:18.189Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:38:18.189Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:38:18.195Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]ompare-[***]ing-[***]900"}])
2021-04-01T19:38:18.402Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:39:14.737Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:39:14.738Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:39:14.738Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:39:16.009Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]emplate.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:39:16.190Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]tom-[***]urce-[***]line-[***]r.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:39:16.470Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]eline-[***]ion-[***]spec-[***]ator-[***].zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:39:20.134Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:39:20.135Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:39:20.135Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:39:20.679Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]ing/[***]iner-[***]e.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:39:21.292Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:39:21.293Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:39:21.293Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:39:21.294Z|info : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
2021-04-01T19:39:21.299Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ted-[***]mation-[***].yml","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:47:00.063Z|error : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
ResourceNotReady: Resource is not in the state stackUpdateComplete
2021-04-01T19:48:00.944Z|info : amplify publish core  
2021-04-01T19:48:10.837Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:48:10.838Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:48:10.838Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:48:10.848Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-04-01T19:48:10.850Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:11.084Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:48:11.085Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:48:11.085Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:48:11.090Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]ompare-[***]ing-[***]900"}])
2021-04-01T19:48:11.292Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:14.328Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:48:14.329Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:48:14.329Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:48:15.379Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]emplate.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:15.702Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]tom-[***]urce-[***]line-[***]r.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:15.969Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]eline-[***]ion-[***]spec-[***]ator-[***].zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:19.404Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:48:19.404Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:48:19.404Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:48:19.880Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]ing/[***]iner-[***]e.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:48:20.395Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:48:20.395Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:48:20.395Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:48:20.396Z|info : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
2021-04-01T19:48:20.400Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ted-[***]mation-[***].yml","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:55:59.283Z|error : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
ResourceNotReady: Resource is not in the state stackUpdateComplete
2021-04-01T19:56:07.825Z|info : amplify publish core  
2021-04-01T19:56:19.039Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:56:19.041Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:56:19.041Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:56:19.059Z|info : amplify-provider-awscloudformation.zip-util.downloadZip.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip"},null])
2021-04-01T19:56:19.063Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]rent-[***]ud-[***]d.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:19.555Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:56:19.555Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:56:19.555Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:56:19.563Z|info : amplify-provider-awscloudformation.initialize-env.run.cfn.updateamplifyMetaFileWithStackOutputs([{"StackName":"[***]ify-[***]ompare-[***]ing-[***]900"}])
2021-04-01T19:56:20.214Z|info : amplify-provider-awscloudformation.aws-s3.s3.getFile([{"Key":"[***]ify-[***]json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:29.043Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:56:29.043Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:56:29.043Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:56:30.355Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]emplate.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:30.543Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]tom-[***]urce-[***]line-[***]r.zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:30.756Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.upload([{"Key":"[***]eline-[***]ion-[***]spec-[***]ator-[***].zip","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:34.425Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:56:34.426Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:56:34.426Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:56:34.877Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ify-[***]fn-[***]ates/[***]ing/[***]iner-[***]e.json","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T19:56:35.498Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T19:56:35.499Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T19:56:35.499Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T19:56:35.500Z|info : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
2021-04-01T19:56:35.504Z|info : amplify-provider-awscloudformation.aws-s3.uploadFile.s3.putObject([{"Key":"[***]ted-[***]mation-[***].yml","Bucket":"[***]ify-[***]ompare-[***]ing-[***]900-[***]ment"}])
2021-04-01T20:04:45.300Z|error : amplify-provider-awscloudformation.push-resources.updateCloudFormationNestedStack(["/Users/user/dev/project/amplify/backend/awscloudformation","/Users/user/dev/project/amplify/backend/awscloudformation/nested-cloudformation-stack.yml"])
ResourceNotReady: Resource is not in the state stackUpdateComplete
2021-04-01T20:24:44.974Z|info : amplify version core  
2021-04-01T20:30:43.566Z|info : amplify add hosting  
2021-04-01T20:31:21.439Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T20:31:21.442Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T20:31:21.443Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
2021-04-01T20:31:31.163Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["default"])
2021-04-01T20:31:31.163Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"us-east-1"}])
2021-04-01T20:31:31.163Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["default"])
```

</details>

### PR DESCRIPTION
**Pull request by sundersc**
#### Description of changes
Bug fix for the Multi-Env container based hosting.
[Multi Env with Amplify Containers #7009](https://github.com/aws-amplify/amplify-cli/issues/7009)

#### Issue #, if available
closes #7009 

#### Description of how you validated changes
- Manual testing
- yarn test passed

#### Checklist
- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/initialize-env.ts [hunk 1]
```diff
@@ -112,3 +114,15 @@ function populateAmplifyMeta(projectPath: string, amplifyMeta: $TSMeta) {
...
+                                metaCategory: string, teamProviderCategory: string, serviceName: string) {
+  if (amplifyMeta[metaCategory] &&
+      amplifyMeta[metaCategory][serviceName] &&
+      teamProviderInfo[CATEGORIES] &&
+      teamProviderInfo[CATEGORIES][teamProviderCategory] &&
+      teamProviderInfo[CATEGORIES][teamProviderCategory][serviceName]) {
+    Object.assign(amplifyMeta[metaCategory][serviceName], teamProviderInfo[CATEGORIES][teamProviderCategory][serviceName]);
+    stateManager.setMeta(projectPath, amplifyMeta);
+  }
+}
```
Comment (jhockett) [inline packages/amplify-cli/src/initialize-env.ts:128]:
```suggestion
function populateCategoriesMeta(
  projectPath: string,
  amplifyMeta: $TSMeta,
  teamProviderInfo: $TSTeamProviderInfo,
  categoryName: string,
  serviceName: string,
) {

  if (
    amplifyMeta[categoryName]?.[serviceName] &&
    teamProviderInfo[CATEGORIES]?.[teamProviderCategory]?.[serviceName]
  ) {
    Object.assign(amplifyMeta[categoryName][serviceName], teamProviderInfo[CATEGORIES][categoryName][serviceName]);
    stateManager.setMeta(projectPath, amplifyMeta);
  }
} 

```

**Review by jhockett — COMMENTED** [review]
I don't see any semantic issues, but this solution deviates from what we discussed offline- generating a template to accept the parameterized values. The amplify-cli package should not contain category specific logic.

**Review by jhockett — DISMISSED** [review]
Solution LGTM! @sundersc let's add an e2e test that covers this to prevent any regressions

File: packages/amplify-e2e-core/src/categories/hosting.ts [hunk 2]
```diff
@@ -29,6 +29,46 @@ export function addDEVHosting(cwd: string): Promise<void> {
   });
 }
 
+export function enableContainerHosting(cwd: string): Promise<void> {
+  return new Promise((resolve, reject) => {
+    spawn(getCLIPath(), ['configure', 'project'], { cwd, stripColors: true })
+      .wait('Which setting do you want to configure?')
+      .send(KEY_DOWN_ARROW)
+      .send(KEY_DOWN_ARROW)
+      .sendCarriageReturn()
```
Comment (jhockett) [inline packages/amplify-e2e-core/src/categories/hosting.ts:38]:
```suggestion
      .wait('Which setting do you want to configure?')
      .sendKeyDown(2)
      .sendCarriageReturn()
```

File: packages/amplify-e2e-core/src/categories/hosting.ts [hunk 3]
```diff
@@ -29,6 +29,46 @@ export function addDEVHosting(cwd: string): Promise<void> {
...
+      });
+  });
+}
+
+export function addDevContainerHosting(cwd: string): Promise<void> {
+  return new Promise((resolve, reject) => {
+    spawn(getCLIPath(), ['add', 'hosting'], { cwd, stripColors: true })
+      .wait('Select the plugin module to execute')
+      .send(KEY_DOWN_ARROW)
+      .send(KEY_DOWN_ARROW)
```
Comment (jhockett) [inline packages/amplify-e2e-core/src/categories/hosting.ts:56]:
```suggestion
      .sendKeyDown(2)
```

File: packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
+import { createReactTestProject } from 'amplify-e2e-core';
+
+import { initJSProjectWithProfile, deleteProject } from 'amplify-e2e-core';
+import { enableContainerHosting, addDevContainerHosting, removeHosting } from 'amplify-e2e-core';
+import { deleteProjectDir, getBackendAmplifyMeta } from 'amplify-e2e-core';
```
Comment (jhockett) [inline packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts:5]: nit: please combine these imports. In VSCode, right-click the code => source action => organize imports

File: packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+import * as fs from 'fs-extra';
+import * as path from 'path';
+
+describe('amplify add hosting - container', () => {
+  let projRoot: string;
+
+  beforeAll(async () => {
+    projRoot = await createReactTestProject();
```
Comment (jhockett) [inline packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts:13]: why `createReactTestProject()` instead of `createNewProjectDir()`?

File: packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+    await removeHosting(projRoot);
+    await deleteProject(projRoot);
+    deleteProjectDir(projRoot);
+  });
+
+  it('add container hosting works', async () => {
+    expect(fs.existsSync(path.join(projRoot, 'amplify', 'backend', 'hosting', 'ElasticContainer'))).toBe(true);
+    const projectMeta = getBackendAmplifyMeta(projRoot);
+    expect(projectMeta.hosting).toBeDefined();
+    expect(projectMeta.hosting.ElasticContainer).toBeDefined();
```
Comment (jhockett) [inline packages/amplify-e2e-tests/src/__tests__/container-hosting.test.ts:29]: Is there anything else we can check to ensure things are working correctly?

**Review by jhockett — APPROVED** [review]
LGTM, thanks for adding the test

**Review by attilah — APPROVED** [review]
Added some comments about adding single select to the test method.
