### PR TITLE
fix(amplify-category-storage): pass context to DDB migration helper

### LINKED ISSUE #1384: Error Migrating
**Describe the bug**
After upgrading the cli to the most recent version, I ran `amplify` in my project root because I wanted to use amplify to set up multiple environments. It prompted me to migrate the project, and asking me to reconfirm. At this point the program says `There was an error migrating your project`, and dumps a whole lot of info, none of which makes sense.

The error occurs at migrate-project.js:93:47

### EDIT AFTER A DEEPER DIVER
Ok so I went through the error, and went to the location, and added a print statement.
That giant dump at the bottom of this is actually what's being passed into the migrate method -- it's `projectPath`, and when `path.join(projectPath, 'amplify', 'backend', category, resourceName)` it crashes since path.join expects [String] as an argument, and `projectPath` is an object.

Not sure how this error is coming up. Will update if I figure out how to fix.

**To Reproduce**
1. Start at root of pre-multienv project
2. run `amplify`

**Expected behavior**
Project is migrated, and can work with multienv.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.6

**Additional context**
The start of the error dump:

```
- Migrating your projectCould not run migration for storage: ServerlessProjects
× There was an error migrating your project.
migration operations are rolledback.
2019-05-03T01:24:06.864Z - error: uncaughtException: Path must be a string. Received Toolbox {
 . 
 . 
 . 
}
at assertPath (path.js:28:11),     
at Object.join (path.js:489:7),     
at migrate (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-storage\provider-utils\awscloudformation\service-walkthroughs\dynamoDb-walkthrough.js:394:32),     
at Object.migrateResource (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-storage\provider-utils\awscloudformation\index.js:44:10),     
at Object.keys.forEach (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-storage\index.js:30:61),
at Array.forEach (<anonymous>),     
at Object.keys.forEach (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-category-storage\index.js:26:42),     
at Array.forEach (<anonymous>),     
at migrate (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@awsamplify\cli\node_modules\amplify-category-storage\index.js:24:28),     
at Array.categoryMigrationTasks.push (C:\Users\ss108560\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\lib\migrate-project.js:93:47)
```

The error dump I've now realized is the context object being incorrectly passed in.
I've cleaned it up a bit. It was not this nice

### PR DESCRIPTION
**Pull request by simsinght**
The arity of migrate method on DDB and S3 were not the same and caused issues when migrating DynamoDB resources. This fixes the arity by passing context as the first argument of migrate method DynamoDB category

*Issue #, if available:*
fix #1384 

*Description of changes:*
See commit message above.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-storage/provider-utils/awscloudformation/index.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ function migrateResource(context, projectPath, service, resourceName) {
     return;
   }
 
-  return migrate(context, projectPath, resourceName);
+  return migrate(projectPath, resourceName);
```
Comment (yuth) [inline packages/amplify-category-storage/provider-utils/awscloudformation/index.js]: The `migrateResource` method is used for both `S3` and `DynamoDB`

https://github.com/aws-amplify/amplify-cli/blob/92895ca8bd9a37ca96b7aeb0ccfda8a379aa8e43/packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js#L290-L294


https://github.com/aws-amplify/amplify-cli/blob/92895ca8bd9a37ca96b7aeb0ccfda8a379aa8e43/packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/dynamoDb-walkthrough.js#L392-L394.

The right fix will be to add `context` to DDB service walkthrough.

Comment (simsinght) [reply packages/amplify-category-storage/provider-utils/awscloudformation/index.js]: ahh yeah I was wondering which was the right way to go about it. Will do so right away.
