### PR TITLE
fix: fix appsync permission assignment from functions

### LINKED ISSUE #4306: Grant lambdas access to other project resources for GraphQL API is either broken or very misleading
**Describe the bug**
The workflow you go through to "update permissions granted to the Lambda function to perform on other resources in your project" does not work - at least not in the way that this piece of documentation implies that it does: https://docs.amplify.aws/cli/function. If you don't choose the `create` operation, you won't actually be able to access an AppSync api from the lambda.

**Amplify CLI Version**
4.20.0

**To Reproduce**
image

Go through the `amplify update function` flow as shown in the above image, being sure to choose an operation other than `create` - `read` for example.

Also, follow all the other steps outlined in the amplify docs here: https://docs.amplify.aws/cli/function#signing-a-request-from-lambda - except instead of a create mutation, feel free to switch to one that is implied to be available based on the operation you chose (a list query for example).

Then, run the lambda and note that you get back an unauthorized error.

**Expected behavior**
Lambda's response contains response of the AppSync query.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. 13.14.0

**Additional context**
When going through the permission grant flow, the outcome is the generation of a CloudFormation template in the lambda's directory. This contains a subtree `AmplifyResourcesPolicy.Properties.PolicyDocument.Statement.Action`, and this is where the problem is. The actions granted by choosing the `read` in the permission grant flow are `appsync:Get*` and `appsync:List*`; `update` gets you `appsync:Update*` and `delete` gets you `appsync:Delete*`. `create` on the other hand gives you `appsync:Create*`, `appsync:StartSchemaCreation`, and critically `appsync:GraphQL`.

An examination of the available Actions under the AppSync category in the IAM Policy Simulator reveals the following: 

image

It looks like all the Create*, Get*, Update*, and Delete* Actions are meta-actions, which would allow your lambda to manipulate AppSync itself - not _use_ it.

I'm not sure if this is technically a bug, because you may well want a lambda to be able to perform meta-actions on your AppSync instance. But that's definitely not the use case advertised in the amplify docs on functions that I've linked twice in here. Those docs technically work because they recommend choosing the `create` option in the workflow, but the way the article is written, that looks like an arbitrary choice that shouldn't affect the outcome, and/or it is implied that because the author was using a mutation that did creation, _that's_ why `create` was chosen.

**Workaround**
Just choose the `create` option if you want a lambda to be able to access your AppSync API (and optionally go into the cloudformation template and delete the extraneous `Create*` and `StartSchemaCreation` Actions).

**Suggested Fix**
Update the CLI to include some more language about how the `create`, `read`, `update`, and `delete` choices relate to meta actions on the AppSync api itself; add a new category named `access` or `call GraphQL endpoint` or something; move the Action `appsync:GraphQL` from `create` to this new category; update the docs at https://docs.amplify.aws/cli/function

### PR DESCRIPTION
**Pull request by r0zar**
fix #4306

*Issue #, if available:*
4306

*Description of changes:*
The current implementation of appsync permissions is using an incorrect understanding of [IAM policies for AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/security.html). This PR updates the IAM Policy generation process for lambdas from `amplify function create/update` walkthroughs.

This PR is ready for merging. :rocket: 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jamesonwilliams** [comment]
PHAL @aws-amplify/amplify-cli (@kaustavghosh06 @renebrandel @UnleashedMind @yuth @attilah)

**Comment by renebrandel** [comment]
hi @r0zar ! I'll try to get the team to review it on Friday. Thanks for starting this!

**Comment by r0zar** [comment]
@renebrandel :wave:  Completed my final updates. This PR is ready for merging now AFAIK

**Comment by renebrandel** [comment]
@attilah will test this PR and see if we need to introduce a feature flag. At this point it looks good.

**Comment by attilah** [comment]
@r0zar Thanks for the PR, I went through it and I see the reason for the changes, but because of existing deployments we have to preserve the existing functionality so it needs to be put behind a feature flag that can be enabled by default for new projects and not for existing projects.

I have one concern about the generated IAM policy and that is that I can't see that the policy generation code includes the schema types. If I remember correctly you have to have access to the types as well, since if I have a policy for `UpdatePost` that does not implicitly grant me access to the `Post` type. This brings to the other thing I am missing is an E2E test which creates a function and an AppSync API and invokes a GraphQL operation.

Since this change has to go behind a feature flag we don't have to deal with the legacy permissions especially we don't have to map it.

If you need further help on the above suggested changes, ping me and I we can setup a meeting to get it through the finish line.

**Comment by r0zar** [comment]
Thanks for the review. 

Yeah let's find some time next week so I get aligned on this and put together a todo list.

**Comment by attilah** [comment]
@r0zar sounds good, please test out the `types/*` policy I miss before that if you can.

**Comment by attilah** [comment]
Synced up offline with @r0zar will add the E2E tests and the Feature flag to preserve the existing functionality and will update the PR.

**Comment by attilah** [comment]
@r0zar how you see your time working on this, do you have an ETA?

**Comment by r0zar** [comment]
I finally had some time open up this week and was going to make a start on it. Hopefully I can knock it out in a few sessions.

**Comment by attilah** [comment]
@r0zar let me know if I can be any help.

**Comment by r0zar** [comment]
Ran a rebase to keep my changes.

**Comment by r0zar** [comment]
Ok, fixed the terrible rebase. :sweat_smile:

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts [hunk 1]
```diff
@@ -9,9 +9,9 @@ export const layerParametersFileName = 'layer-parameters.json';
 export const parametersFileName = 'parameters.json';
 export const provider = 'awscloudformation';
 export const appsyncTableSuffix = '@model(appsync)';
-export const resourceAccessSetting = 'Resource access permissions';
-export const cronJobSetting = 'Scheduled recurring invocation';
-export const lambdaLayerSetting = 'Lambda layers configuration';
+export const resourceAccessSetting = '🔒 Resource access permissions';
+export const cronJobSetting = '⏰ Schedule recurring invocation';
+export const lambdaLayerSetting = '📦 Lambda layers configuration';
```
Comment (jhockett) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts:14]: Make sure associated Lambda e2e test helper functions are updated to wait on the updated text.

Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts:14]: Gotcha! thanks.

**Comment by r0zar** [comment]
:tada:

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts [hunk 2]
```diff
@@ -1,9 +1,9 @@
 import { constructCFModelTableNameComponent, constructCFModelTableArnComponent } from '../utils/cloudformationHelpers';
-import inquirer from 'inquirer';
+import inquirer, { CheckboxQuestion, DistinctChoice } from 'inquirer';
 import path from 'path';
 import * as TransformPackage from 'graphql-transformer-core';
-import _ from 'lodash';
-import { topLevelCommentPrefix, topLevelCommentSuffix, envVarPrintoutPrefix, CRUDOperation } from '../../../constants';
+import _, { get, capitalize, concat, isEmpty } from 'lodash';
```
Comment (attilah) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:5]: Please use `import _ from 'lodash';` and don't deconstruct its functions, it's more readable that way.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts [hunk 3]
```diff
@@ -60,7 +60,7 @@ export async function createWalkthrough(
   // list out the advanced settings before asking whether to configure them
   context.print.info('');
   context.print.success('Available advanced settings:');
-  advancedSettingsList.forEach(setting => context.print.info('- '.concat(setting)));
+  advancedSettingsList.forEach(setting => context.print.info(setting));
```
Comment (attilah) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts:63]: Why removed the '-' prefix? We rarely change prompts and DX without API reviews. Sync up on this with @renebrandel .

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts (hunk 1 above)
Comment (attilah) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/utils/constants.ts:14]: @renebrandel please ack the icon changes.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts [hunk 4]
```diff
@@ -1,5 +1,8 @@
+import { FeatureFlags } from 'amplify-cli-core';
 import _ from 'lodash';
 
+const featureFlagPR5342 = () => FeatureFlags.getBoolean('useAppSyncPermissionsInLambdaPolicies')
```
Comment (attilah) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts:4]: Just name it normally as a variable, no need for GH reference, also FeatureFlags has a <group>.<feature>, I'd suggest to use `appSync`.`generateGraphQLPermissionsForCRUD` since this feature flag is not for `graphqlTransformer`. We can debate the name but this is what it does IMHO, suggest something similar if you have a better in mind.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts [hunk 5]
```diff
@@ -8,6 +11,36 @@ export const fetchPermissionResourcesForCategory = (permissionMap, category: str
...
+export const fetchPermissionsForResourceInCategory = (
+  permissionMap: object = {},
+  category: string,
+  resourceName: string,
+  serviceType: string,
+) => {
+  const permissions = _.get(permissionMap, [category, resourceName], []);
+  // If AppSync and legacy CRUD permissions BUT they opted into the feature flag, update policy.
+  if (serviceType == 'AppSync' && hasCRUDPermissions(permissions) && featureFlagPR5342()) {
+    return updatePermissionsForBackwardsCompatibility(permissionMap, category, resourceName);
```
Comment (attilah) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts:23]: Why is the FF branch of the if doing anything that is backward compatible? It should not, right?

File: packages/amplify-cli-core/src/feature-flags/featureFlags.ts [hunk 6]
```diff
@@ -504,6 +504,12 @@ export class FeatureFlags {
         defaultValueForExistingProjects: false,
         defaultValueForNewProjects: false,
       },
+      {
+        name: 'useAppSyncPermissionsInLambdaPolicies',
```
Comment (attilah) [inline packages/amplify-cli-core/src/feature-flags/featureFlags.ts:508]: As suggested above it should go into a new `appSync` group.

**Review by attilah — CHANGES_REQUESTED** [review]
Added a few comments on the recent changes, but overall almost there!

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts (hunk 4 above)
Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts:4]: how do you feel about the category being `iamPolicies`? This distinction would be helpful to make clear it's related to how the policies are generated and managed.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts (hunk 3 above)
Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.ts:63]: The `-` served as the bullet-point in a pseudo unordered list. I replaced that with the icons in the PR. It results in a more visually comprehensible list of choices that can be understood better internationally.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts (hunk 5 above)
Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts:23]: I wrote it so that enabling a feature flag with incorrect permissions would autocorrect their policies. I now see that the way feature flags are being used in amplify is that by turning them on early, the user may deals with the consequences. I see this results in code with less 'artifacts' so I'll update to fit this design.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts (hunk 2 above)
Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:5]: :heavy_check_mark:

File: packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts (hunk 5 above)
Comment (r0zar) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/utils/permissionMapUtils.ts:23]: I moved the FF check to line 102 of `execPermissionsWalkthrough.ts`. Still exists as an artifact in the code, but there is no more autocorrecting of permissions. Is this the intention?

**Comment by r0zar** [comment]
I squashed and force pushed the commit with only the relevant changes to keep the scope a little tighter.

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts [hunk 7]
```diff
@@ -25,32 +26,31 @@ export const askExecRolePermissionsQuestions = async (
   category?: string,
```
Comment (r0zar) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:26]: This value seems to be coming in as undefined for most scenarios. Is it still used?

**Review by attilah — APPROVED** [review]
LGTM, thanks for hanging in there ;-)
