### PR TITLE
fix: split policies for both legacy and migrated REST APIs

### LINKED ISSUE #9225: amplify push fails after upgrading to cli 7.6.2
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.2

### What operating system are you using?

Windows

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

>amplify push
? Are you sure you want to continue? Yes
√ A migration is needed to support latest updates on api resources.
Recommended to try in a non-production environment first. Run "amplify env add" to create or clone an environment.
Learn more about this migration: https://docs.amplify.aws/cli/migration/override
Do you want to migrate api resource "resources"? (Y/n) · yes

× An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: Cannot read properties of undefined (reading 'forEach')

Before saying "yes" to the migration step, there were api-params.json and parameters.json files under the existing resources.
After running this command all the api-params.json and parameters.json files are deleted and the command itself fails with the above message.
It even deletes the cloud formation templates which were customized as per requirements.

After this I uninstalled amplify cli and installed version 6.4.0 and took a fresh git clone.
Everything worked fine with 6.4.0 version of amplify cli.
DeletedItems

### Expected behavior

Amplify push should create the resources in the cloud without any error.

### Reproduction steps

Create amplify project with amplify version < 7.
Add API to the project.
Customize the API's cloud formation template to add a custom authorizer or to covert it to a web socket API.
Run Amplify push. It runs successfully.
Upgrade amplify to the latest version.
Make any change in the API. For eg., change a description in the cloud formation template.
Again run Amplify Push.
It gives the error mentioned above.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jhockett**
#### Description of changes
Currently, the CLI will ensure all REST APIs have been migrated to ensure that the policy splitting is done correctly. This PR makes older APIs compatible with the policy splitting logic, and migration on push is no longer required. Override migration is only prompted for on `amplify update api` after this change.

#### Description of how you validated changes
Manually created api, `apigw-ext-migration.test.ts` and `yarn test` pass

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts [hunk 1]
```diff
@@ -200,7 +200,7 @@ export class ApigwStackTransform {
 
       if (override && typeof override === 'function') {
         const overrideCode: string = await fs.readFile(overrideJSFilePath, 'utf-8').catch(() => {
-          formatter.list(['No override File Found', `To override ${this.resourceName} run amplify override auth`]);
+          formatter.list(['No override file found', `To override ${this.resourceName} run amplify override auth`]);
```
Comment (akshbhu) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/apigw-stack-transform.ts:203]:
```suggestion
          formatter.list(['No override file found', `To override ${this.resourceName} run amplify override api`]);
```

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts [hunk 2]
```diff
@@ -34,7 +34,7 @@ type AmplifyCDKL1 = {
   addCfnCondition(props: cdk.CfnConditionProps, logicalId: string): void;
   addCfnMapping(props: cdk.CfnMappingProps, logicalId: string): void;
   addCfnOutput(props: cdk.CfnOutputProps, logicalId: string): void;
-  addCfnParameter(props: cdk.CfnParameterProps, logicalId: string): void;
+  addCfnParameter(props: cdk.CfnParameterProps, logicalId: string, value?: any): void;
```
Comment (akshbhu) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts:37]: I guess we can discuss on this to return the cdk obj also with these functions.
```
  addCfnResource(props: cdk.CfnResourceProps, logicalId: string): CfnResource;
```

File: packages/amplify-category-api/src/provider-utils/awscloudformation/convert-deprecated-apigw-paths.ts [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+        groups,
+      },
+      lambdaFunction: path.lambdaFunction,
+    };
+  });
+
+  return paths;
+}
+
+function _convertDeprecatedPermissionStringToCRUD(deprecatedPrivacy: string) {
```
Comment (akshbhu) [inline packages/amplify-category-api/src/provider-utils/awscloudformation/convert-deprecated-apigw-paths.ts:73]:
```suggestion
function _convertDeprecatedPermissionStringToCRUD(deprecatedPrivacy: string): CrudOperation[] {
```

**Review by akshbhu — COMMENTED** [review]
Changes looks good.  Can we also include unit tests around convertDeperecatedRestApiPaths.ts file to be safe?

Also is there a e2e test present for the oldRestApi to not migrate when upgrading amplify and doing amplify push

File: packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts (hunk 2 above)
Comment (jhockett) [reply packages/amplify-category-api/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts:37]: I'm open to expanding the API, but I think that's better for another PR. This change was just fixing a type that I forgot to update in a previous PR.

**Review by akshbhu — APPROVED** [review]
LGTM!!

**Review by johnpc — APPROVED** [review]
lgtm!
