### PR TITLE
fix(graphql-dynamodb-transformer): support model without id

### LINKED ISSUE #4502: amplify cli v4.21.1 introduces graphql mutation dynamo error
**Describe the bug**
`amplify push` with v4.21.1 results in an api stack that where sending `createThing` graphql mutations results in consistant failure with the following error:

```json
{
  "data": {
    "createFoo": null
  },
  "errors": [
    {
      "path": [
        "createFoo"
      ],
      "data": null,
      "errorType": "DynamoDB:AmazonDynamoDBException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "One or more parameter values were invalid: Type mismatch for key id expected: S actual: NULL (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: REDACTED)"
    }
  ]
}
```

The same action with v4.21.0 (and earlier) results in no error.

**Amplify CLI Version**
@aws-amplify/cli@4.21.1 (@aws-amplify/cli@4.21.0 is fine)

**To Reproduce**
`amplify push` and then send a `createFoo` mutation to the api.

Schema:

```graphql
type Foo
  @model
  @key(
    name: "byBar"
    fields: ["barID"]
    queryField: "fooByBar"
  ) {
  barID: ID!
  Bar: Bar! @connection(fields: ["barID"])
  something: [Something]
    @connection(keyName: "byBar", fields: ["barID"])
}
```

Autogenerated mutation that creates error when used:

```graphql

mutation CreateFoo(
  $input: CreateFooInput!
  $condition: ModelFooConditionInput
) {
  createFoo(input: $input, condition: $condition) {
    barID
    bar {
      (stuff)
    }
  }
}
```
With the input type being:

```graphql
input CreateFooInput {
  barID: ID!
}
```

**Expected behavior**
I expect the mutation to create a new Foo entry in dynamo and no error to be thrown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.16.2

### PR DESCRIPTION
**Pull request by yuth**
Updatd graphql-dynamodb-transformer to automatically add id to the model when
id is missing in the type. Id will not be added if `@key` directive changes
the primary index

fix #4502 
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/graphql-key-transformer/src/KeyTransformer.ts [hunk 1]
```diff
@@ -115,6 +115,10 @@ export class KeyTransformer extends Transformer {
   private updateSchema = (definition: ObjectTypeDefinitionNode, directive: DirectiveNode, ctx: TransformerContext) => {
     this.updateQueryFields(definition, directive, ctx);
     this.updateInputObjects(definition, directive, ctx);
+    const isPrimaryKey = this.isPrimaryKey(directive);
+    if (isPrimaryKey) {
+      this.removeAutocreatedPrimaryKey(definition, directive, ctx);
```
Comment (attilah) [inline packages/graphql-key-transformer/src/KeyTransformer.ts:120]: nit: AutoCreated

**Comment by yuth** [comment]
> A migration test which ensures that the GraphQL output of the same schema where `@key` transformer added the `id` field will produce the very same output from the new CLI with this change where this behavior is done with `@model` transformer.

I am not sure how we can do migration test for this. This changes the behavior of `@model` directive by adding `id` field and exposing that in the type if the `model`  does not change the `hashKey` with `@key` directive.

This used to work in CLI version 4.20.0 but stopped working in later versions. But prior to 4.20.0, the id was not exposed in the type and an model without the `id` field could not be used with `@connection`. This fixes that issue

File: packages/graphql-key-transformer/src/KeyTransformer.ts (hunk 1 above)
Comment (yuth) [reply packages/graphql-key-transformer/src/KeyTransformer.ts]: Fixed
