### PR TITLE
fix: isMockable() handles Lambda functions without dependsOn array

### LINKED ISSUE #4761: amplify mock function myPreSignup errors with: Cannot read property 'filter' of undefined
**Describe the bug**
When running ```amplify mock function myPreSignup``` on a fresh untouched PreSignup function I get the error:
```Cannot read property 'filter' of undefined```

I suspect this error came with the latest CLI version.

**Amplify CLI Version**
4.23.0

**To Reproduce**
Create an AUTH with PreSignup function then run:
```amplify mock function yourPreSignup```

**Expected behavior**
It should not result in error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version 10.17.0

### PR DESCRIPTION
**Pull request by jhockett**
*Issue #, if available:*
fixes  #4761

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-function/src/index.ts [hunk 1]
```diff
@@ -138,7 +138,7 @@ export async function getInvoker(context: any, params: InvokerParameters): Promi
 export function isMockable(context: any, resourceName: string): IsMockableResponse {
   const { service, dependsOn } = context.amplify.getProjectMeta()[category][resourceName];
   const hasLayer =
-    service === ServiceName.LambdaFunction && dependsOn.filter(dependency => dependency.category === 'function').length !== 0;
+    service === ServiceName.LambdaFunction && dependsOn && dependsOn.filter(dependency => dependency.category === 'function').length !== 0;
```
Comment (edwardfoyle) [inline packages/amplify-category-function/src/index.ts:141]: I don't think it should ever not be an array, but maybe also check Array.isArray(dependsOn)
