### PR TITLE
fix: aggreagate paginated results in cfn.listStackResources call

### LINKED ISSUE #9037: Storage outputs from cfn not getting generated
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.22.1

### Amplify CLI Version

7.4.5

### What operating system are you using?

Mac

### Amplify Categories

auth, storage

### Amplify Commands

push

### Describe the bug

Entire environment is broken after trying to upgrade to amplify v7.4.5.

Issue started with our cypress tests failing with our front-end getting an error on Storage.put indicating that the region is missing. This led me down to realized that the s3/storage information is not getting populated into the aws-exports.json file.

I then noticed on every push it is saying that our storage needs to be created (s3), even though it definitely exists.

I then went through the process of doing the overrides migration https://docs.amplify.aws/cli/migration/override/ in the attempt to fix this. I started with storage and did a push which then failed. I then tried doing Auth which resulted in more failures.

So now I have reverted everything and went back to version 6.4.0 which is working.

The following was the latest push failure which means that during your migration process, something is not referencing the new outputs/inputs from auth.

I replaced our resource name with XXXXXX for privacy purposes.
```
UPDATE_FAILED storageXXXXXX   AWS::CloudFormation::Stack Mon Nov 22 2021 15:13:04 GMT-0800 (Pacific Standard Time) Parameters: [authXXXXXXXXXXXXXUserPoolId, authuserPoolGroupsadminGroupRole] do not exist in the template
UPDATE_FAILED apiXXXXXX AWS::CloudFormation::Stack Mon Nov 22 2021 15:13:05 GMT-0800 (Pacific Standard Time) Resource update cancelled   
```

### Expected behavior

amplify push works and amplify-exports.json is generated correctly

### Reproduction steps

See above description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kaustavghosh06**
fixes #9037

Related - https://github.com/aws-amplify/amplify-cli/pull/9060

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js [hunk 1]
```diff
@@ -326,9 +326,24 @@ class CloudFormation {
     };
     const projectDetails = this.context.amplify.getProjectDetails();
     const { amplifyMeta } = projectDetails;
+
```
Comment (attilah) [inline packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:329]: use pagedAWSCall from https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/aws-utils/paged-call.ts

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js [hunk 2]
```diff
@@ -326,9 +326,24 @@ class CloudFormation {
...
+    let stackSummaries = [];
+
     logger('updateamplifyMetaFileWithStackOutputs.cfn.listStackResources', [cfnParentStackParams])();
-    const result = await this.cfn.listStackResources(cfnParentStackParams).promise();
-    const resources = result.StackResourceSummaries.filter(
+
+    do {
+      const listStackResourcesParams = {
+        StackName: parentStackName,
+        nextToken,
```
Comment (gakinson) [inline packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:338]: the param needs to be labeled as "NextToken" with a capital N

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js (hunk 1 above)
Comment (kaustavghosh06) [reply packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:329]: @attilah The pagedAWSCall uses "nextToken" as the param key whereas CFN expects it to be "NextToken" as @gakinson mentioned below, so might not be able to use the pagedAWSCall util function as is.

Comment (attilah) [reply packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:329]: @kaustavghosh06 getNextToken in that function is an accessor function for this reason, because it is varies across AWS APIs as they evolved. Like dynamodb is using something else as "NextToken", see usage here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/aws-utils/DynamoDBService.ts#L41

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js [hunk 3]
```diff
@@ -335,7 +335,7 @@ class CloudFormation {
     do {
       const listStackResourcesParams = {
         StackName: parentStackName,
-        nextToken,
+        NextToken: nextToken,
```
Comment (gakinson) [inline packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:338]: you are also going to want to double check that it supports undefined as a value in here for the call.

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js (hunk 1 above)
Comment (kaustavghosh06) [reply packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:330]: Got it. Made the change. Could you please review?

File: packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js (hunk 3 above)
Comment (kaustavghosh06) [reply packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js]: Yup, using an already existing util function that we have to do this which takes care of these checks.

**Review by attilah — APPROVED** [review]
Thx for the update, lgtm

**Comment by gakinson** [comment]
Hey, glad this has been merged in. Do you have an ETA on a new release?

**Comment by kaustavghosh06** [comment]
@gakinson We're working on a release for this right now but i've published an NPM tag for you to test out

**Comment by gakinson** [comment]
> @gakinson We're working on a release for this right now but I've published an NPM tag for you to test out - `npm install -g @aws-amplify/cli@pagefix` Could you please give that a shot?

EVerything generated correctly. meta file and aws-exports.json

**Comment by gakinson** [comment]
Hey, just checking in again on an ETA

**Comment by kaustavghosh06** [comment]
@gakinson We've started the release to the npm tag. You can monitor it out here - https://app.circleci.com/pipelines/github/aws-amplify/amplify-cli?branch=release should be ~ 15-30 mins.
