### PR TITLE
fix(amplify-util-mock): pass env vars to lambda when invoked with mock

### LINKED ISSUE #2453: amplify mock Error: Cannot find ref to userpoolId
I am trying to get "amplify mock" to work, but I'm getting 2 errors: 

> Failed to parse Lambda function cloudformation in
> amplify/backend/function/lambdaHandler/lambdaHandler-cloudformation-template.json
> 
> Error: Could not find ref for "mycustomname77b3f30UserPoolId"
> 
> Also in the lambda that was auto generated by "amplify add auth" "mycustomnamePostConfirmation"
> 
> mycustomnamePostConfirmation-cloudformation-template.json
> Error: Could not find ref for "GROUP"

There's a function in my project called "lambdaHandler"  (amplify add function)
API: yes 
Auth: yes (cognito)

Any ideas at all on what must be done here to get a local mock environment working?

### PR DESCRIPTION
**Pull request by yuth**
Updated the mock lambda invoker to pass the env vars related to resources suck as API Key and
GraphQL endpoint

fix #2453 and #2690

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-util-mock/src/utils/lambda/hydrate-env-vars.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+};
+export function hydrateAllEnvVars(
+  resources: Resources,
+  sourceEnvVars: Record<string, string>,
+  apiDetails?: ApiDetails,
+): Record<string, string> {
+  const outputMap: Record<string, object> = resources.reduce((acc: Record<string, object>, r) => {
+    const category = r.category;
+    const resourceName = r.resourceName.toLowerCase();
+    const outputs = Object.entries(r.output || {}).reduce((sum, [name, value]) => {
```
Comment (edwardfoyle) [inline packages/amplify-util-mock/src/utils/lambda/hydrate-env-vars.ts]: Nit: these nested reduce functions are a bit confusing to reason through. Maybe consider putting them into helper functions?
