### PR TITLE
fix: show friendly error message when pull fails with EPERM

### LINKED ISSUE #7448: Can't pull amplify app: operation not permitted, rename
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v13.14.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

Windows 7

### Amplify Categories

Not applicable

### Amplify Commands

pull

### Describe the bug

using `amplify pull --appId <id> --envName <name>` breaks with the following error:
`EPERM: operation not permitted, rename 'C:\Users\Ori\Documents\tawkit\backend\am
plify' -> 'C:\Users\Ori\Documents\tawkit\backend\amplify-backup'
Error: EPERM: operation not permitted, rename 'C:\Users\Ori\Documents\tawkit\bac
kend\amplify' -> 'C:\Users\Ori\Documents\tawkit\backend\amplify-backup'
    at Object.renameSync (fs.js:754:3)
    at rename (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_module
s\fs-extra\lib\move-sync\move-sync.js:31:8)
    at doRename (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\node_modu
les\fs-extra\lib\move-sync\move-sync.js:26:10)
    at Object.moveSync (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\no
de_modules\fs-extra\lib\move-sync\move-sync.js:17:10)
    at backupAmplifyFolder (C:\Program Files\nodejs\node_modules\@aws-amplify\cl
i\lib\attach-backend.js:107:12)
    at Object.attachBackend (C:\Program Files\nodejs\node_modules\@aws-amplify\c
li\lib\attach-backend.js:35:5)
    at Object.run (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\lib\com
mands\pull.js:64:32)
    at Object.executeAmplifyCommand (C:\Program Files\nodejs\node_modules\@aws-a
mplify\cli\lib\index.js:238:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async executePluginModuleCommand (C:\Program Files\nodejs\node_modules\@a
ws-amplify\cli\lib\execution-manager.js:164:5)
    at async Object.executeCommand (C:\Program Files\nodejs\node_modules\@aws-am
plify\cli\lib\execution-manager.js:35:9)
    at async Object.run (C:\Program Files\nodejs\node_modules\@aws-amplify\cli\l
ib\index.js:114:9)`

### Expected behavior

amplify pulls correctly.

### Reproduction steps

amplify pull -appId <id> -envName <name>

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

looks like this issue: https://github.com/aws-amplify/amplify-cli/issues/6138#issuecomment-742730830
but it's still repro-ing.

### PR DESCRIPTION
**Pull request by yuth**
fix #7448

#### Checklist

- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/attach-backend.ts [hunk 1]
```diff
@@ -104,8 +104,16 @@ function backupAmplifyFolder() {
...
       throw error;
     }
-
-    fs.moveSync(amplifyDirPath, backupAmplifyDirPath);
+    try {
+      fs.moveSync(amplifyDirPath, backupAmplifyDirPath);
+    } catch (e) {
+      if (e.code === 'EPERM') {
+        throw new Error(
+          'Could move attach the backend to the project. Ensure that there no applications locking the `amplify` folder and try again',
```
Comment (cjihrig) [inline packages/amplify-cli/src/attach-backend.ts:112]: It's not clear to me what "Could move attach" is intended to mean.

Comment (cjihrig) [inline packages/amplify-cli/src/attach-backend.ts:112]:
```suggestion
          'Could move attach the backend to the project. Ensure that there are no applications locking the `amplify` folder and try again',
```

File: packages/amplify-cli/src/attach-backend.ts [hunk 2]
```diff
@@ -104,8 +104,16 @@ function backupAmplifyFolder() {
...
       throw error;
     }
-
-    fs.moveSync(amplifyDirPath, backupAmplifyDirPath);
+    try {
+      fs.moveSync(amplifyDirPath, backupAmplifyDirPath);
+    } catch (e) {
+      if (e.code === 'EPERM') {
+        throw new Error(
+          'Could attach the backend to the project. Ensure that there are no applications locking the `amplify` folder and try again',
```
Comment (cjihrig) [inline packages/amplify-cli/src/attach-backend.ts:112]: Should this be "Could not attach..."?

**Review by cjihrig — APPROVED** [review]
