### PR TITLE
fix: support serve script

### LINKED ISSUE #5068: Command "amplify init --app <repo>" doesn't find "yarn start" for a Vue project as it should be "yarn serve"
**Describe the bug**
I was using `amplify init --app https://github.com/gsans/fullstack-serverless-amplify-ui-vue-solution` and saw this error.

```
$ amplify init --app https://github.com/gsans/fullstack-serverless-amplify-ui-vue-solution

Scanning for plugins...
Plugin scan successful
Note: Amplify does not have knowledge of the url provided
Cloning into '.'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 58 (delta 5), reused 58 (delta 5), pack-reused 0
Unpacking objects: 100% (58/58), done.
yarn install v1.22.4amplify init --app https://github.com/gsans/fullstack-serverless-amplify-ui-vue-solution
Scanning for plugins...
Plugin scan successful
Note: Amplify does not have knowledge of the url provided
Cloning into '.'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 58 (delta 5), reused 58 (delta 5), pack-reused 0
Unpacking objects: 100% (58/58), done.
yarn install v1.22.4
[...]
GraphQL endpoint: https://wjgztmlrmrdonelvjnltopmboy.appsync-api.eu-west-2.amazonaws.com/graphql
GraphQL API KEY: da2-g2qw2domr5bhjh4yvmkxdyc3zu
Hosting endpoint: http://amplifyapp-20200811152013-hostingbucket-sampledev.s3-website.eu-west-2.amazonaws.com

yarn run v1.22.4
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
An error occurred during the push operation: Command failed: yarn start
``` 

**Amplify CLI Version**
4.27.1 

**To Reproduce**
Run command below in an empty folder.

```
amplify init --app https://github.com/gsans/fullstack-serverless-amplify-ui-vue-solution
```

**Expected behavior**
Vue projects use `yarn serve` not `yarn start`.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v14.7.0

**Additional context**
NA

### PR DESCRIPTION
**Pull request by nikhname**
fix #5068

*Issue #, if available:*
#5068

*Description of changes:*
Use ```serve``` command if the script exists in package.json

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-cli/src/packageManagerHelpers.ts [hunk 1]
```diff
@@ -24,6 +25,28 @@ export async function getPackageManager() {
...
+ */
+export async function getPackageManagerCommand() {
+  let scripts;
+  if (fs.existsSync(packageJsonDir)) {
+    const pjson = fs.readFileSync(packageJsonDir).toString();
+    const parsedPjson = JSON.parse(pjson);
+    scripts = parsedPjson['scripts'];
+  }
+
+  if (scripts['start']) {
```
Comment (edwardfoyle) [inline packages/amplify-cli/src/packageManagerHelpers.ts:41]: if package.json doesn't exist or doesn't contain a "scripts" field this will error

File: packages/amplify-cli/src/packageManagerHelpers.ts [hunk 2]
```diff
@@ -24,6 +25,28 @@ export async function getPackageManager() {
...
+ *
+ * @return {string} 'serve' or 'start'
+ */
+export async function getPackageManagerCommand() {
+  let scripts;
+  if (fs.existsSync(packageJsonDir)) {
+    const pjson = fs.readFileSync(packageJsonDir).toString();
+    const parsedPjson = JSON.parse(pjson);
+    scripts = parsedPjson['scripts'];
+  }
```
Comment (edwardfoyle) [inline packages/amplify-cli/src/packageManagerHelpers.ts:39]: use JSONUtilities from `amplify-cli-core` for this

File: packages/amplify-cli/src/packageManagerHelpers.ts [hunk 3]
```diff
@@ -24,6 +25,28 @@ export async function getPackageManager() {
...
+
+  if (scripts['start']) {
+    return 'start';
+  } else if (scripts['serve']) {
+    return 'serve';
+  } else {
+    throw new Error('initialize script was not found');
```
Comment (edwardfoyle) [inline packages/amplify-cli/src/packageManagerHelpers.ts:46]:
```suggestion
    throw new Error('Did not find a "start" or "service" initialization script. Add a package.json file in the root of the project with one of these scripts.');
```

File: packages/amplify-cli/src/packageManagerHelpers.ts (hunk 1 above)
Comment (nikhname) [reply packages/amplify-cli/src/packageManagerHelpers.ts]: Changed to check if scripts exists and moved into package.json check.

File: packages/amplify-cli/src/packageManagerHelpers.ts (hunk 2 above)
Comment (nikhname) [reply packages/amplify-cli/src/packageManagerHelpers.ts]: Fixed

File: packages/amplify-cli/src/packageManagerHelpers.ts (hunk 3 above)
Comment (nikhname) [reply packages/amplify-cli/src/packageManagerHelpers.ts]: Changed the error message

File: packages/amplify-cli/src/packageManagerHelpers.ts [hunk 4]
```diff
@@ -24,6 +30,31 @@ export async function getPackageManager() {
...
+ * Determine the starting command of the current project
+ *
+ * @return {string} 'serve' or 'start'
+ */
+export async function getPackageManagerCommand() {
+  let scripts;
+  if (fs.existsSync(packageJsonDir)) {
+    const pjson = fs.readFileSync(packageJsonDir).toString();
+    const parsedPjson = JSONUtilities.parse<$TSAny>(pjson);
+    scripts = parsedPjson['scripts'];
```
Comment (edwardfoyle) [inline packages/amplify-cli/src/packageManagerHelpers.ts:43]: Can use
```suggestion
const scripts = _.get(JSONUtilities.readJson(packageJsonDir, {throwIfNotExist: false}), 'scripts')
```

File: packages/amplify-cli/src/packageManagerHelpers.ts [hunk 5]
```diff
@@ -24,6 +30,31 @@ export async function getPackageManager() {
...
+      } else if (scripts['serve']) {
+        return 'serve';
+      } else {
+        throw MISSING_SCRIPTS_ERROR;
+      }
+    } else {
+      throw MISSING_SCRIPTS_ERROR;
+    }
+  }
+}
```
Comment (edwardfoyle) [inline packages/amplify-cli/src/packageManagerHelpers.ts:56]:
```suggestion
return _.keys(scripts).find(scriptName => ['start', 'serve'].includes(scriptName)) || (() => {throw MISSING_SCRIPTS_ERROR})();
```
