### PR TITLE
fix: update CLI to handle UTF8 BOM

### LINKED ISSUE #1122: Amplify init fails on another machine
I'm at work right... I type amplify init, I do all my work, later at home, I pull the project from github and want to work on it... so I hit amplify add env, pick the env that I added at work... 

It complains, fails to compile, won't do a thing... how am I meant to do this correctly?

** Which Category is your question related to? **
amplify in general... 

** What AWS Services are you utilizing? **
amplify-cli

** Provide additional details e.g. code snippets **

### LINKED ISSUE #1355: "Unexpected token  in JSON at position 0" during amplify init
**Describe the bug**
During the execution of `amplify init` the console returns an error message: 

```
% amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project <MY PROJECT NAME>
? Enter a name for the environment dev
? Choose your default editor: None
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use <MY PROFILE NAME>
⠸ Initializing project in the cloud...
...
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
init failed
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at getCurrentAWSConfig (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:77:22)
    at createAWSConfig (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/frontend-config-creator.js:22:28)
    at Object.createFrontendConfigs (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/index.js:23:10)
    at Object.onCategoryOutputsChange (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.js:22:33)
    at initializeEnv (/Users/schmelte/.nvm/versions/node/v8.15.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:79:27)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**To Reproduce**
1. Clone [iOS EventsApp starter](https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios)
1. In project directory, issue `amplify init`

**Expected behavior**
Project initializes successfully

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Browser: N/A
 - Amplify Version: 1.6.5

**Contents of awsconfiguration.json:**

```json
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "Default": {
        "ApiUrl": "https://<MY API URL>.appsync-api.us-east-2.amazonaws.com/graphql",
        "Region": "us-east-2",
        "AuthMode": "API_KEY",
        "ApiKey": "<MY API KEY>"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by yuth**
Some editors and platforms can add UTF BOM at the begining of the file. Node JSON.parse doesn't
handle the BOM enchoding very well and chokes the CLI. Updating the CLI to use a util method which
can handle the BOM chars

fix #1355 and fix #1122

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-api/commands/api/add-datasource.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ module.exports = {
          */
         const currEnv = amplify.getEnvInfo().envName;
         const teamProviderInfoFilePath = amplify.pathManager.getProviderInfoFilePath();
-        const teamProviderInfo = JSON.parse(fs.readFileSync(teamProviderInfoFilePath));
+        const teamProviderInfo = context.amplify.readJsonFile(teamProviderInfoFilePath);
```
Comment (UnleashedMind) [inline packages/amplify-category-api/commands/api/add-datasource.js]: For consistency, use `amplify` directly without the `context.`

File: packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js [hunk 2]
```diff
@@ -287,13 +287,13 @@ function checkIfAuthExists(context) {
...
 
-function migrate(projectPath, resourceName) {
+function migrate(context, projectPath, resourceName) {
   const resourceDirPath = path.join(projectPath, 'amplify', 'backend', category, resourceName);
 
   // Change CFN file
 
   const cfnFilePath = path.join(resourceDirPath, 's3-cloudformation-template.json');
-  const oldCfn = JSON.parse(fs.readFileSync(cfnFilePath, 'utf8'));
+  const oldCfn = context.amplify.readJsonFile(cfnFilePath, 'utf8');
```
Comment (UnleashedMind) [inline packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js]: By default, the encoding is 'utf8', so the second argument is not needed. 
The second argument is in the method just in case people wanted to use other encodings. 
I think we can consistently remove the second argument when readJsonFile method is called.

File: packages/amplify-category-api/commands/api/add-datasource.js (hunk 1 above)
Comment (yuth) [reply packages/amplify-category-api/commands/api/add-datasource.js]: Lets do that later. If there are any problem in the `ServiceMetaData` the CLI will fail to start as they are at the top level

File: packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js (hunk 2 above)
Comment (UnleashedMind) [inline packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js]: The deleted comment is here, you don't need to use encoding if the encoding is 'utf8'.

File: packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js [hunk 3]
```diff
@@ -349,7 +349,7 @@ function migrate(projectPath, resourceName) {
 
   // Change Parameters file
   const parametersFilePath = path.join(resourceDirPath, parametersFileName);
-  const oldParameters = JSON.parse(fs.readFileSync(parametersFilePath, 'utf8'));
+  const oldParameters = context.amplify.readJsonFile(parametersFilePath, 'utf8');
```
Comment (UnleashedMind) [inline packages/amplify-category-storage/provider-utils/awscloudformation/service-walkthroughs/s3-walkthrough.js]: you don't need to use encoding if the encoding is 'utf8'.

File: packages/amplify-category-api/commands/api/add-datasource.js (hunk 1 above)
Comment (UnleashedMind) [reply packages/amplify-category-api/commands/api/add-datasource.js]: I see your point, but don't you think it's better that this is consistent across the whole project? currently, some are on top of the file direct using JSON.parse(fs.readFileSync(.)) directly, such as `amplify-category-analytics/commands/analytics/add.js'; and some are inside the run method using context.amplify.readJsonFile(.), such as `amplify-category-auth/commands/auth/enable.js`

Comment (yuth) [reply packages/amplify-category-api/commands/api/add-datasource.js]: Do you think that change belong in this PR? Each plugin has its own style and we could put effort to make them consistent. But should we bundle it here?
