### PR TITLE
fix: #6719 remove validator on function categories access prompt

### LINKED ISSUE #6719: Cannot remove access to another resource from lambda function
**Describe the bug**
I'm trying to remove Storage access from my pre-token cognito trigger function.

But when running `amplify update function`, I'm not able to deselect the API resource category:

```bash
 ⚙  god  ~/Git/resources.linaro.org   develop ±✚  aws2-wrap --profile ResourcesHubUser
--exec "amplify update function"
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update resourceshub5749acdaPreTokenGeneration
General information
| Name: resourceshub5749acdaPreTokenGeneration
| Runtime: nodejs

Resource access permission
- resourceStorage (read)

Scheduled recurring invocation
| Not configured

Lambda layers

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to.
 ◯ function
 ◯ ssm
 ◯ perms
 ◯ auth
 ◯ api
❯◯ storage
>> You must select at least one category
```

**Amplify CLI Version**
4.44.0

**To Reproduce**
Add a pre-token lambda trigger function. Add access to another resource category. Then try to remove this access. Instead you get a validation error stating that at least one must be selected?

**Expected behavior**
To be able to remove access to a resource.

### PR DESCRIPTION
**Pull request by PawanKolhe**
*Issue #, if available:* Fixes #6719 

*Description of changes:*

Package: amplify-category-function

Removes the validator for the prompt question: 'Select the categories you want this function to have access to.'
Fixes bug where user had to have atleast one category selected. This PR allows user to deselect all category options during that prompt.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts [hunk 1]
```diff
@@ -274,7 +274,6 @@ const selectCategories = (choices: DistinctChoice<any>[], currentPermissionMap:
   name: 'categories',
   message: 'Select the categories you want this function to have access to.',
   choices,
-  validate: answers => (_.isEmpty(answers) ? 'You must select at least one category' : true),
```
Comment (kaustavghosh06) [inline packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:277]: Can you please verify the flow where you add function -> Select add permission -> Don't select any category -> push? I think that flow would break with this change.

Comment (kaustavghosh06) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:277]: Did we verify this flow?

Comment (PawanKolhe) [reply packages/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/execPermissionsWalkthrough.ts:277]: I verified the flow. It seems to be working perfectly.

**Comment by sharmaaditya570191** [comment]
@kaustavghosh06 I was working on a related issue so tested this PR. It works fine but it still prints info to the terminal.

image

Should we ensure that it prints info only if `envVarStringList` is not empty in the `askExecRolePermissionsQuestions` function code?

image
